### ISSUE TITLE
Review scrollbar position in CodeWithResult component

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1015]
![image](https://user-images.githubusercontent.com/849648/99243269-bebb7780-2800-11eb-899d-78a2ff673a5a.png)

**Comment by hrescak** [comment]
@mhwelander is this hiding any content?

**Comment by carlagn** [comment]
Current behaviour:

![Image](https://github.com/prisma/docs/assets/14851246/b23846bd-fa6f-44ed-92cb-447668cef4ca)

Solution can stem from #1023 

page: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference
