### ISSUE TITLE
How to improve experience with narrow code blocks by avoiding horizontal scroll

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1023]
With the recent redesign of the docs, the middle column that contains the written content of the docs pages became a lot more narrow.

This also means that very often, code blocks need to be scrolled horizontally because they're cut off on the right. This is not a great experience and I'm wondering if we can somehow come up with a nice interaction that's "easier" than horizontal scroll that would at the same time expand and show the full code block at once.

One idea would be to introduce a simple kind of user interaction that would pop the code block into a modal that's super easy to close. That would allow the reader to shortly focus on the entire code block and then easily/quickly go back to the actual content of the page.

**Comment by nikolasburk** [comment]
Somewhat related to: https://github.com/prisma/docs/issues/1015

**Comment by hrescak** [comment]
How many code blocks currently have this issue?

**Comment by hrescak** [comment]
I'm asking because similar to the issue we had with large tables, I think we should do the most we can to prevent it from happening and then see if it makes sense to build an overlay solution on the remaining blocks.

**Comment by nikolasburk** [comment]
I've seen this quite a bit (basically any page where a horizontal scroll bar appears). Maybe @mhwelander has some thoughts about this as well?

**Comment by nikolasburk** [comment]
I think the reason why I'm really suffering from this is because I rarely have a window open as fullscreen width but 99% percent of the time have to windows that each take half of the width of the screen. 

So for me this really is a problem because almost all code blocks are cut off in some capacity... while this is my personal issue, I would assume that there might be more people that don't read the docs in full-screen width and for whom the middle column becomes really narrow.

An alternative solution to expanding code blocks could also be to hide TOC column if the screen is lower than a certain width to make more space for the middle column.

Also, as a reference, I noticed that dev.to implements a simple solution for exactly that problem (but I think we can probably do better than them):

![Kapture 2020-12-03 at 10 13 40](https://user-images.githubusercontent.com/4058327/100988669-410da080-3550-11eb-87cc-952b639888ef.gif)

**Comment by carlagn** [comment]
| currently | solution in blog |
| ----- | ----- |
| ![](https://user-images.githubusercontent.com/14851246/237418029-76aaebdd-566e-4ed9-ace7-bd258907662b.png) | ![Image](https://github.com/prisma/docs/assets/14851246/13e8e58f-bca1-4e1c-bbab-5c46e8b5508f) |

**Comment by nilubava** [comment]
@carlagn We need to document the `wrap` property for code blocks. @meletj We think it should be documented under https://www.prisma.io/docs/about/prisma-docs/docs-components/mdx-examples#code-blocks

**Comment by meletj** [comment]
> @carlagn We need to document the `wrap` property for code blocks. @meletj We think it should be documented under https://www.prisma.io/docs/about/prisma-docs/docs-components/mdx-examples#code-blocks

Ok, let's add it there. And as part of https://github.com/prisma/docs/issues/4924, we can check if any other property or similar needs to be added to the page.
