### ISSUE TITLE
TopBlock doesn't render Markdown links

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1046]
![image](https://user-images.githubusercontent.com/4058327/100605569-69a35980-3308-11eb-8caf-6a9958787d75.png)

Example: https://www.prisma.io/docs/guides/migrate-to-prisma/migrate-from-typeorm

![image](https://user-images.githubusercontent.com/4058327/100605611-7758df00-3308-11eb-9d2a-44670a25752d.png)

**Comment by hrescak** [comment]
This is baffling to me because I assumed that this is one of the limitations of MDX - whatever is 'inside' a component is no longer markdown so I'm surprised that last link is even working 🤣

**Comment by nikolasburk** [comment]
True, definitely wird! Maybe the last link works because it's linking internally do another docs page 🤔 

Also, it seems to dependent on the implementation, e.g. on the blog you can just use plain Markdown in the `<Abstract>` element: 

https://raw.githubusercontent.com/prisma/prisma-blog/master/posts/2020-11-03-prisma-studio.mdx?token=AA66ZV6W3ZE426BCOKEK2HS7ZYURE

**Comment by rahul3v** [comment]
It just needs **a newline between** the newBlock and the content to work fine
