### ISSUE TITLE
More extensive documentation of the return value of `$transaction` with example

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1054]
As requested on Slack [here](https://prisma.slack.com/archives/CKQTGR6T0/p1606971463193400).

![image](https://user-images.githubusercontent.com/4058327/100975574-8aed8b00-353e-11eb-81e1-3f8b393a53b7.png)

**Comment by ruheni** [comment]
This is currently documented on this page: https://www.prisma.io/docs/concepts/components/prisma-client/transactions#sequential-prisma-client-operations
