### ISSUE TITLE
Document percent encoding for uris

### ISSUE THREAD

**Issue by pantharshit00** [prisma/web#1057]
Whenever someone tries to use special characters in the their uri like `%` or `@`, they should be percent encoded.  https://en.wikipedia.org/wiki/Percent-encoding

Refer: https://github.com/prisma/prisma/issues/4455

**Comment by mhwelander** [comment]
Related: https://github.com/prisma/prisma/issues/5612#issuecomment-778108158

**Comment by mhwelander** [comment]
Mentioned for PostgreSQL and MySQL
