### ISSUE TITLE
Can't use arrow up/down keys to navigate search results

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1058]
It's awesome that I can open search by hitting `/` but once I typed my search keyword I'm forced to use my mouse again because I can't navigate the search results with my arrow up/down keys.

The docs would be even more awesome if that was possible :)

MartinaTest: Cannot use arrows, screen freezes.
MartinaTest2: Slow, and it maintains the 'select' between searches - e.g. search for 'sql', page down 3x, search for 'data', #3 is selected even though it's a new search

**Comment by meletj** [comment]
Fixed in the new search modal.
