### ISSUE TITLE
Clicking on "Prisma Migrate" under "Set up Prisma with your own database" doesn't honor the redirect

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/web#1064]
On https://www.prisma.io/docs/getting-started/quickstart-typescript#set-up-prisma-with-your-own-database
when clicking "Prisma migrate" I end up being scrolled back to the top with this URL: https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-prisma-migrate/ which shows me the old migrate guide.
When refreshing, it shows the newly updated guide.
I suspect that clicking the button doesn't honor the redirect while the reload does.

**Comment by nikolasburk** [comment]
Thanks for raising this, fixed via: https://github.com/prisma/docs/pull/1063
