### ISSUE TITLE
Env vars must be written inside quotes "" in shell/bash

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1065]
https://prisma-company.slack.com/archives/C5Z9TH6N9/p1607508776067500?thread_ts=1607508716.067200&cid=C5Z9TH6N9

About how to write an env var value in Bash

[...]
if you do this:
```
DATABASE_URL=postgresql://janedoe:my;;password;;yikes@localhost:5432/mydb
```
the variable will be `postgresql://janedoe:my` and the shell evaluates the rest as separate commands 

but if you wrap it with ", it will treat it as a string
because this is a valid way of using the shell:
```
DATABASE_URL=postgresql://foo:barr@localhost:5432/mydb; MY_OTHER_VAR=yikes
```

So we want " around env vars like connection strings to avoid anything like usernames and passwords using characters-with-shell-meaning (like ;) being evaluated as Not-A-String

yes, and ; means in the shell to end the current command, following up another one

[...]

**Comment by mhessdev** [comment]
Todo: Double-check examples in our docs.

**Comment by mhessdev** [comment]
Closing: not relevant

**Comment by janpio** [comment]
On page 1 of search results for .env files in the docs:
https://github.com/prisma/docs/blob/f32a5e31b1fecc1abb83b9b652128d0e70590a6f/content/200-orm/500-reference/380-connection-urls.mdx#L118
