### ISSUE TITLE
In the upgrade guide for Prisma Migrate Preview, recommend introspection only to those already using introspection flow

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/web#1068]
https://www.prisma.io/docs/guides/prisma-guides/prisma-migrate-guides/add-prisma-migrate-to-a-project/

![image](https://user-images.githubusercontent.com/24216/101625923-0f934a00-3a14-11eb-8295-61396694e534.png)

**Comment by ruheni** [comment]
We've since updated the docs and wording for this, and it's therefore not relevant anymore
