### ISSUE TITLE
Go client docs - defining how

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/web#1069]
We would need to figure out how we'll publish docs about the Go client on the Prisma.io docs.
Knowing that the Go client is in early access, and it may come with significant differences in certain aspects, we may consider the following:
* language switcher
* separate docs pages if it turns out the switcher makes things overly complicated

**Comment by steebchen** [comment]
One thing to consider is also that the Prisma CLI is executed differently in Go (`go run github.com/prisma/prisma-client-go generate`) vs. `prisma` or `yarn prisma`. This also applies to migrate, introspect, studio, and so on. Not sure if it's sufficient to just note that somewhere or if we would need to provide a language switcher for CLI commands as well.

**Comment by ruheni** [comment]
Closing this because we're not officially maintaining the Go Client documentation anymore.

See this issue for more information: https://github.com/prisma/prisma-client-go/issues/707
