### ISSUE TITLE
Review FAQ list

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1079]
Go through FAQ list and make sure all FAQs are still relevant.

**Comment by albertoperdomo** [comment]
Is this issue still relevant @mhwelander? If so, itwould be great to add some more info. Right now it doesn't look very actionable. Please reassign to me if still relevant.

**Comment by mhwelander** [comment]
@albertoperdomo I assigned this to you - FAQs just need a general check to make sure they're still all correct.

**Comment by meletj** [comment]
Not actionable as such.
