### ISSUE TITLE
Realistic use case for `$transaction`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1093]
The [current use case for the `$transaction` API](https://www.prisma.io/docs/concepts/components/prisma-client/transactions#the-transaction-api) that's shown in the docs doesn't make too mich sense since this would better covered with a nested write. We should probably include a more realistic example.

**Comment by ryands17** [comment]
A better example here would be:

- Filtering posts along with providing a total count:

```ts
const [posts, totalPosts] = await prisma.$transaction([
    prisma.post.findMany({ where: { title: { contains: 'prisma' } } }),
    prisma.post.count(),
])
```

**Comment by nikolasburk** [comment]
IMO we can still come up with a better default example than this one:

![image](https://user-images.githubusercontent.com/4058327/107645775-6ec24480-6c79-11eb-8fa1-8293849105ac.png)

**Comment by nikolasburk** [comment]
Maybe just use the example that Ryan suggested? (or add it as a second example snippet, since it primarily shows reads but transactions are often interesting in the context of writes as well)
