### ISSUE TITLE
development vs production documentation is bleak and shadow-databases also.

### ISSUE THREAD

**Issue by mnffaisy1** [prisma/web#1123]
please make it more comprehensive with examples...

**Comment by nikolasburk** [comment]
Hey @mnffaisy1, thanks a lot for opening this issue! Can you maybe share a few concrete questions you have that we can address in the docs?

**Comment by mnffaisy1** [comment]
@nikolasburk i saw the video on youtube whats new in prisma 2.13.0 which was comprehensive but docs are not. i think maybe u should make development and production clear with examples in docs. docs made me confused... and write more on shadow databases.
Thank you

**Comment by mnffaisy1** [comment]
working flow is missing in docs.
