### ISSUE TITLE
Recommend to set the env var NODE_ENV to ‘production’ for deployment

### ISSUE THREAD

**Issue by Jolg42** [prisma/web#1124]
About deployment / production a user asked me recommendations so I pointed them to https://www.prisma.io/docs/concepts/components/prisma-client/deployment/

I noticed that there is nothing about setting the env var NODE_ENV to ‘production’, which I think would be good to add.

**Comment by janpio** [comment]
How is that env var used by Prisma?

**Comment by Jolg42** [comment]
It looks like this is where it's used:

In Studio:
https://github.com/prisma/prisma/blob/490b701ebd26e8461ead0b060a7be90f785b1765/src/packages/cli/src/Studio.ts#L120-L131

In Client:
to change the errorFormat to `minimal`
https://github.com/prisma/prisma/blob/490b701ebd26e8461ead0b060a7be90f785b1765/src/packages/client/src/runtime/getPrismaClient.ts#L359-L363
also
https://github.com/prisma/prisma/blob/490b701ebd26e8461ead0b060a7be90f785b1765/src/packages/client/src/runtime/query.ts#L292-L297
and
https://github.com/prisma/prisma/blob/490b701ebd26e8461ead0b060a7be90f785b1765/src/packages/client/src/runtime/utils/printStack.ts#L88

@timsuchanek I think this is it.

**Comment by janpio** [comment]
That would be something to document then, the impact changing this setting has.

**Comment by mhwelander** [comment]
Related: #809
