### ISSUE TITLE
Document workaround for missing `createMany` operation

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1127]
Right now the docs don't give any results when someone is searching for `createMany` because this method doesn't exist in the Prisma Client API. Lots of people (see issues [here](https://github.com/prisma/prisma-client-js/issues/332), [here](https://github.com/prisma/prisma-client-js/issues/835) and [here](https://github.com/prisma/prisma/issues/4349)) need this functionality though, so we should document a workaround, e.g. using the `$transaction` API:

```ts
const userData: Prisma.UserCreateInput[] = [{
  name: 'James',
  email: 'james@prisma.io'
}, {
  name: 'Sarah',
  email: 'sarah@prisma.io'
}]

const createCalls: Promise<User>[] = []
for (let u of userData) {
  const c = prisma.user.create({ data: u })
  createCalls.push(c)
}
await prisma.$transaction(createCalls)
```

**Comment by matthewmueller** [comment]
FYI, I'd hold off on this as we'll be working on this very soon.

Internal proposal (not finished or vetted yet) is [here](https://www.notion.so/prismaio/Prisma-Client-Bulk-Insert-Proposal-892bc69a1f2d433a9e62e6376fe03c27):

**Comment by mhwelander** [comment]
No longer missing
