### ISSUE TITLE
Document missing code snippet

### ISSUE THREAD

**Issue by sthtnr** [prisma/web#1131]
In the
https://github.com/prisma/docs/blob/master/content/200-concepts/050-overview/100-what-is-prisma/index.mdx

There's a line

> Notice that the @prisma/client node module references a folder named .prisma\client. The .prisma\client folder contains your generated Prisma client, and is modified each time you change the schema and run the following command:

But right under this line, there's no code snippet.
Isn’t  something missing?

**Comment by ruheni** [comment]
Hey 👋

Thank you for sharing your feedback. Prisma Client has a `postinstall` hook that autogenerates Prisma Client types and methods after installing it. Currently, Prisma Client is generated "silently" — there is no message from Prisma Client, but it is generated. We have updated the wording. Let us know if you'd like us to make any further improvements to it too.

We have also added a code snippet that you could use to re-generate Prisma Client if you don't find the generated code. 🙂

Feel free to reopen the issue if you would like any further clarification.
