### ISSUE TITLE
Missing preview features

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1144]
It seems like the [documented list of preview features](https://www.prisma.io/docs/concepts/components/preview-features) is out of sync with the [actual preview features](https://github.com/prisma/prisma/issues/3108)

**Comment by mhwelander** [comment]
I linked to the GH issue instead - this is going to keep getting out of sync: https://github.com/prisma/docs/tree/master/content/200-concepts/100-components/07-preview-features
