### ISSUE TITLE
Make error to upgrade to Typescript 4.1 google-able 

### ISSUE THREAD

**Issue by matthewmueller** [prisma/web#1147]
Ryan ran into this today with Group by:

```
server.ts:6:25 - error TS2615: Type of property 'OR' circularly references itself in mapped type '{ [K in keyof { AND?: Enumerable<ProductScalarWhereWithAggregatesInput>; OR?: Enumerable<ProductScalarWhereWithAggregatesInput>; ... 4 more ...; category?: string | StringWithAggregatesFilter; }]: Or<...> extends 1 ? { ...; }[K] extends infer TK ? GetHavingFields<...> : never : {} extends FieldPaths<...> ? never : K...'.
6   const grouped = await prisma.product.groupBy({
                          ~~~~~~~~~~~~~~~~~~~~~~~~
7     by: ['category']
  ~~~~~~~~~~~~~~~~~~~~
8   });
  ~~~~
server.ts:6:48 - error TS2554: Expected 0 arguments, but got 1.
6   const grouped = await prisma.product.groupBy({
                                                 ~
7     by: ['category']
  ~~~~~~~~~~~~~~~~~~~~
8   });
  ~~~
```

He was using a globally-installed typescript 4.0.5. Upgrading to 4.1 fixed his problem.

It would be nice to be able to google `Type of property 'OR' circularly references itself in mapped type` and land on the System Requirements page or something that says hey you need to upgrade your Typescript implementation.

**Comment by matthewmueller** [comment]
Could also be a stackoverflow answer :-D

**Comment by mhwelander** [comment]
Added to system requirements page as its troubleshooting related to version used: https://github.com/prisma/docs/blob/master/content/400-reference/100-system-requirements.mdx
