### ISSUE TITLE
Trouble Querying Implicit Many to Many Relationship by specific IDs

### ISSUE THREAD

**Issue by mark-antony1** [prisma/web#1150]
Hello,

I am having trouble using the [implicit](https://www.prisma.io/docs/concepts/components/prisma-schema/relations#relation-tables) database many-many relationship within Prisma. It seems to me that Prisma is expecting an explicit relation-table to be created and accessible vs. building a join table on the fly.

I have a many-many relationship between houses and users. However, I haven't seen any clear examples in the [docs](https://www.prisma.io/docs/support/help-articles/working-with-many-to-many-relations#solution) for querying something where I want to get all the houses associated with a particular user.

I would like to understand how to set up the implicit many-many relationship so that I can query all the houses that are associated with a specific host/user that follows something like the syntax of 

```
				return await ctx.prisma.house.findMany({
					where: {
						hosts: {
							every: {
								email: email
							}
						}
					},
					orderBy: {
						date_to: "desc",
					},
				})
```

However, when I try to execute this^ database read, I get the following error message
`"[GraphQL] Invalid `prisma.house.findMany()` invocation: The table `public._houseTouser` does not exist in the current database."`

My Schema
```
model house {
  /// This field's default value can currently not be parsed: `gen_random_uuid()`.
  id             String          @id @default(dbgenerated())
  created_at     DateTime        @default(now())
  updated_at     DateTime        @default(now())
  address        String
  description    String
  minimum_nights Int             @default(0)
  date_from      DateTime
  date_to        DateTime
  name           String          @default("Default Name")
  hosts          user[]          
  bookings       booking[]
  house_amenities  house_amenity[]
  house_pictures house_picture[]
  rooms          room[]
}

model user {
  /// This field's default value can currently not be parsed: `gen_random_uuid()`.
  id             String    @id @default(dbgenerated())
  created_at     DateTime  @default(now())
  updated_at     DateTime  @default(now())
  email          String    @unique
  memberstack_id String    @unique
  is_host        Boolean
  first_name     String    @default("John")
  last_name      String    @default("Doe")
  guest_bookings booking[] @relation("booking_guest_idTouser")
  host_bookings  booking[] @relation("booking_host_idTouser")
  houses         house[]
}
```

**Comment by mark-antony1** [comment]
@pantharshit00 Have you found a way to do implicit many-many tables in the past without needing to explicitly create a relation-table?

**Comment by jharrell** [comment]
Closing this as completed by our documentation on [implicit many-to-many relations](https://www.prisma.io/docs/orm/prisma-schema/data-model/relations/many-to-many-relations#implicit-many-to-many-relations)
