### ISSUE TITLE
Document process.env.PRISMA_CLI_BINARY_TARGETS

### ISSUE THREAD

**Issue by Jolg42** [prisma/web#1152]
Used in the download binaries logic https://github.com/prisma/engines-wrapper/blob/master/packages/engines/src/download.ts#L24

```
PRISMA_CLI_BINARY_TARGETS=darwin,rhel-openssl-1.0.x npm install
```

Example from
https://github.com/prisma/prisma/issues/2980#issuecomment-665691866

In order for the CLI to work in AWS lambda, install it locally on your machine and upload it to the lambda function. Getting npx running did not work in our tests, as it needs to write to the filesystem.

To get the right binaries downloaded for Lambda, you need to provide the PRISMA_CLI_BINARY_TARGETS env var during npm install like:

`PRISMA_CLI_BINARY_TARGETS=darwin,rhel-openssl-1.0.x npm install`

Note, that you also need to provide your local platform, in my case darwin (macOS), a comma is used to separate targets.

Running execSync did not work to fork the command in my tests, instead it worked with execa:
```js
const execa = require('execa')

module.exports.hello = async (event) => {
  const { stdout, stderr } = await execa.command('node node_modules/prisma/build/index.js generate')
  console.log('stdout', stdout)
  console.log('stderr', stderr)

  return {
    statusCode: 200,
    body: JSON.stringify(
      {
        message: 'Hello! Your function executed successfully!',
        input: event,
        env: process.env,
      },
      null,
      2,
    ),
  }
}
```

**Comment by mhwelander** [comment]
Related: #809
