### ISSUE TITLE
Data integrity / SQLite 

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1155]
https://prisma-company.slack.com/archives/C5Z9TH6N9/p1610099930196400

>What I mean here is if a user has an SQLite database with schema that says a column is a boolean, but then there are string and whatnot weird values written to the fields, we fail to query that kind of data.
I'm writing a better error message here and would be great if I could point to our documentation.

**Comment by ruheni** [comment]
Add information on Data integrity with SQLite here: https://www.prisma.io/docs/concepts/database-connectors/sqlite

TODO
- [ ] Explore & document all the quirks of SQLite
- [ ] Add docs


![Image](https://github.com/prisma/docs/assets/33921841/1c2f9c14-f33d-44d3-8b0b-2dac6472970a)


Possibly related: https://github.com/prisma/docs/issues/2803

**Comment by nikolasburk** [comment]
Closing because:
- the origin of this issue was a problem with Prisma ORM: https://github.com/prisma/prisma/issues/4778
- we have docs for the data types in SQLite already
