### ISSUE TITLE
Group By search takes you to Group By FAQ

### ISSUE THREAD

**Issue by matthewmueller** [prisma/web#1157]
**Expect**

Top of the Group By page: https://www.prisma.io/docs/concepts/components/prisma-client/group-by

**Actual**

FAQ at the bottom of the Group By page: https://www.prisma.io/docs/concepts/components/prisma-client/group-by#faq

<img width="1274" alt="CleanShot 2021-01-08 at 14 53 59@2x" src="https://user-images.githubusercontent.com/170299/104023070-68940080-51c1-11eb-93cf-a27dceeb89a9.png">

**Comment by mhwelander** [comment]
![image](https://user-images.githubusercontent.com/849648/107116449-a5f8b600-6873-11eb-8004-5bec9a0b742e.png)
