### ISSUE TITLE
Many more broken links

### ISSUE THREAD

**Issue by janpio** [prisma/web#116]
- reference/prisma-cli/installation from reference/tools-and-interfaces/prisma-migrate
- reference/prisma-client/api from reference/database-connectors/connection-urls and reference/tools-and-interfaces/introspection
- reference/prisma-client/configuring-the-prisma-client-api from reference/tools-and-interfaces/introspection
- reference/prisma-client/connection-management from reference/database-connectors/mysql and reference/database-connectors/postgresql
- reference/prisma-client/query-engine from reference/database-connectors/database-features

**Comment by mhwelander** [comment]
All fixed
