### ISSUE TITLE
Improve $connect documentation

### ISSUE THREAD

**Issue by Jolg42** [prisma/web#1169]
https://prisma.slack.com/archives/CKQTGR6T0/p1610111259433700
User feedback for when a user was looking for $connect in search
- ended up to to $connect anchor
- missed the important paragraph that is actually at the top of the page

>Unless you want to employ a specific optimization, calling prisma.$connect() is not necessary thanks to the lazy connect behavior: The PrismaClient instance connects lazily when the first request is made to the API ($connect() is called for you under the hood).

Should we move that paragraph or mention something inside the $connect anchor block maybe so people don't miss that part?
<img width="633" alt="Screen Shot 2021-01-11 at 10 19 07" src="https://user-images.githubusercontent.com/1328733/104437498-20912700-558f-11eb-9375-2cd0e6afa5c6.png">

**Comment by mhwelander** [comment]
Improved: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-management#calling-connect-explicitly
