### ISSUE TITLE
Shaky sidebar

### ISSUE THREAD

**Issue by matthewmueller** [prisma/web#1178]
I tried recording a video, but my recording frame rate wasn't high enough to capture the shakiness 😅 Should be pretty easy to spot yourself if you just scroll.

https://cln.sh/HFTy96ACbhlPyDMCm8Tx

**Comment by matthewmueller** [comment]
https://www.prisma.io/docs/concepts/components/prisma-client/crud#updatemany

**Comment by mhwelander** [comment]
@matthewmueller Are you Windows or Mac? I see a more pronounced version of this on Windows (#931) but it couldn't be replicated.

**Comment by hrescak** [comment]
@matthewmueller can you take a look to see if it's better now?

**Comment by matthewmueller** [comment]
Sorry I missed this. Unfortunately, I'm still seeing this. Chrome  88 on Mac.

Looks like the problem is pixel value stuttering in the sidebar-holder. Possible solution, when you hit the scroll bottom of the sidebar then swap to fixed position.

https://user-images.githubusercontent.com/170299/106941337-fca2aa80-6722-11eb-996b-a3b6d1032deb.mp4

**Comment by hrescak** [comment]
This is definitely still an issue @nilubava.

https://user-images.githubusercontent.com/753458/111522940-2216d100-8731-11eb-8210-996ed675849c.mp4
