### ISSUE TITLE
Enable checkmarks as bullet points

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1180]
At the moment, we can only do bullet points as regular bullets. It would be nice to be able to have other characters, e.g. ✔  as bullet points too.

Context: https://github.com/prisma/docs/pull/1158/files#diff-660d9de0c55ea278cd6f7a8e0cf7324ac24b6e2f18589e32a7990eaf90576f29R534

![image](https://user-images.githubusercontent.com/4058327/104707138-50216a00-571c-11eb-9e8d-dbdca5bdf5e1.png)

**Comment by mhwelander** [comment]
I would love these two:

![image](https://user-images.githubusercontent.com/849648/104711389-975e2980-5721-11eb-92c1-c3273ea12683.png)
