### ISSUE TITLE
Document transaction failure example

### ISSUE THREAD

**Issue by ryands17** [prisma/web#1192]
As per [this](https://prisma.slack.com/archives/CKQTGR6T0/p1611092981087800) public Slack question:

![image](https://user-images.githubusercontent.com/19697099/105167390-a9cfcd00-5b3e-11eb-9554-89157a67b504.png)

There should be an example of the flow where a single operation in the `prisma.$transaction` fails and what would be the approach that Prisma takes.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
