### ISSUE TITLE
Docs homepage feedback

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1206]
* [x] Render `title`, `description`, `keywords` from `siteMetaData` in config.js. Currently site has no `title` or meta description.
* [x] Headings jump straight from h1 to h3 - promote current h3s to h2s, h4s to h3, and so on

**Comment by Jolg42** [comment]
- [x] 404 link on page text = FAQ - value = `https://www.prisma.io/about/faq`
- [x] canonical missing
