### ISSUE TITLE
Exclude 'TopBlock' from search results

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1208]
![image](https://user-images.githubusercontent.com/849648/105721752-31de1a00-5f25-11eb-9261-49f42a3396d2.png)

**Comment by ankur-arch** [comment]
Closing as outdated.

<img width="1134" alt="image" src="https://github.com/user-attachments/assets/0de608d9-9c64-42af-beeb-1b6a9fa5a2e8">
