### ISSUE TITLE
Exclude title suffix from Prisma docs homepage

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1211]
So that we can have `Prisma documentation` or similar as the title, not `Prisma documentation | Prisma docs`. Homepage should only render `title` from `siteMetadata` in `<title>` - no suffix or prefix.

If possible, change the title to `Prisma documentation` before merging PR!

**Comment by Jolg42** [comment]
Would be great if it fits in 60 chars (so not truncated by Google)
