### ISSUE TITLE
Enable inline code in <summary> tags

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1214]
When writing expandable blocks via `<details>` and `<summary>` tags, it's currently not possible to use inlince code. Fro example in this case, `User` and `@@unique` should be written as inline code:

![image](https://user-images.githubusercontent.com/4058327/105833838-0eb97600-5fca-11eb-87d9-e761bf7de069.png)

For example like this:

```
<details><summary>Expand for example <InlineCode>User</InlineCode> model with an <InlineCode>@@id</InlineCode> block</summary>
```

**Comment by nilubava** [comment]
@nikolasburk This is already available in the docs. You can use:

```
<details><summary>Expand for example <inlineCode>User</inlineCode> model with an <inlineCode>@@id</inlineCode> block</summary>
```

**Comment by nikolasburk** [comment]
Ah that's great to know, thanks 👍
