### ISSUE TITLE
Run Prettier in GitHub action

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1215]
Sometimes the docs use hyphens and sometimes asterisks for bullet points. We should:

- make a decision which one to use across the entire docs and persist it in the style guide
- go through the docs to update all inconsistent usages

**Comment by johannesschobel** [comment]
This can be fixed by prettier

**Comment by nikolasburk** [comment]
This doesn't seem to be fixed throughout the entire docs yet, e.g. this page still uses [hyphens](https://raw.githubusercontent.com/prisma/docs/master/content/200-concepts/050-overview/100-what-is-prisma/index.mdx) and this [page](https://raw.githubusercontent.com/prisma/docs/master/content/200-concepts/100-components/02-prisma-client/000-working-with-prismaclient/015-instantiate-prisma-client.mdx) uses asterisks. 

Personally I prefer hyphens, but care more about the consistency. Once we made a decision, we should probably also include this in the style guide. (And yeah, as @johannesschobel pointed out this can ideally even be automated 🙂 )

**Comment by mhwelander** [comment]
Ahh, I see the problem, Prettier is not run on deploy. It already changes * to -, but you have to run it locally. @nilubava Can we format on build or is that not recommended?

**Comment by johannesschobel** [comment]
spoiler: i am not a prisma member

i would suggest 
a) to run prettier when making the PR within a github action
b) add a `husky` `pre-commit` (or `pre-push`) hook that runs prettier

however, i would not add it to the build process. For example, if prettier is misconfigured (as it was before), this would fail your build pipeline or corrupt your page!

**Comment by mhwelander** [comment]
That sounds like a good plan, @johannesschobel 🤗

Moving this to web engineering.
