### ISSUE TITLE
Text "Show CLI output" should be configurable

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1218]
Right now the text "Show CLI output" is fixed on `CmdResult` elements, but it's now always fully appropriate. E.g. sometimes it's not the CLI output but the value of a variable that is shown, e.g. [here](https://deploy-preview-1014--prisma2-docs.netlify.app/reference/api-reference/prisma-client-reference#select-the-name-and-profileviews-fields-of-a-single-user-record):

![image](https://user-images.githubusercontent.com/4058327/105837346-e122fb80-5fce-11eb-8c7d-861f7ff0a587.png)

**Comment by mhwelander** [comment]
Part of: #1393

**Comment by mhwelander** [comment]
https://github.com/prisma/docs/pull/1393/files?file-filters%5B%5D=.tsx#diff-8144f382bd8535867018074ce77506d0ba7fae62f630699c503746896cdb56e0
