### ISSUE TITLE
Document best practice and anti-patterns for development workflows (SQLite in dev, Postgres in prod)

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1233]
Lots of people are used to working with SQLite in development and then switching to a "proper" DB like Postgres in production.

This is a workflow that's not straightforward to achieve with Prisma (mostly because the `provider` of a `datasource` can't be set dynamically). Further, it's actually considered not a good practice because:

-  Prisma schema capabilities (as well as the generated Prisma Client code) change depending on the `provider` (e.g. `enum` definitions are possible with Postgres but not SQLite; the goal of Prisma is to be able to expose the _specific_ features of the underlying DB, and since SQLite doesn't natively support enums, Prisma does not allow their usage in the Prisma schema either)
- there is a _potential_ for a mismatch in behaviour when going from development to production that should rather be avoided

More context in this [Slack convo](https://prisma.slack.com/archives/CA491RJH0/p1611774026074700):

![image](https://user-images.githubusercontent.com/4058327/106119036-06da0d00-6155-11eb-8089-2b0020bd4b2c.png)

**Comment by nikolasburk** [comment]
Even more context here: https://github.com/prisma/prisma/issues/3834

**Comment by nikolasburk** [comment]
another related convo: https://twitter.com/benediktms/status/1359844377091338245

![image](https://user-images.githubusercontent.com/4058327/107637875-16864500-6c6f-11eb-9f65-a54a6595c7b9.png)

**Comment by cupcakearmy** [comment]
Is there any progress/recipe on this? Having to spin up a "full" db for local dev. is a bit overkill for most use cases.

**Comment by tanberry** [comment]
Thanks for bumping this one, @cupcakearmy; it does look like a good topic for the Docs team to explain more fully, about why one would not want to switch to diff DB when moving to Prod. We will  pull it in and triage it soon.

**Comment by syenchuk** [comment]
If prisma devs ever consider supporting sqlite in dev, postgres in prod, in my opinion, this would be very helpful, and is achievable, Django devs did it and it works well:

https://docs.djangoproject.com/en/5.0/topics/migrations/

The main idea is to have abstract migration files, instead of raw SQL (and backend-specific) queries:

https://docs.djangoproject.com/en/5.0/topics/migrations/#migration-files
