### ISSUE TITLE
Document how to use interactive CLI commands like migrate dev when using Docker

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/web#1236]
Additional context:

>Hello, is it possible to get arround "Error: We detected that your environment is non-interactive. Running this command in not supported in this context."? We use prisma migrate in docker to build, not local.
https://prisma.slack.com/archives/CKQTGR6T0/p1611660799182300

https://github.com/prisma/prisma/issues/4669#issuecomment-767545954

**Comment by molebox** [comment]
Closing as addressed in #1749
