### ISSUE TITLE
pool_timeout connection string flag

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1237]
https://prisma-company.slack.com/archives/CEYCG2MCN/p1611854772073200

**Comment by Jolg42** [comment]
//! - `pool_timeout` defined in seconds. If all connections are in use, the
//!   database will return a `PoolTimeout` error after waiting for the given time.
//!   If set to zero, no timeout.
https://github.com/prisma/quaint/blob/79130113115d4a5f016e7d447b13a81aa778d59e/src/pooled.rs#L59-L61

Note: It is by default 5s, 0 = turning it off
