### ISSUE TITLE
Prisma 1 docs pages result in 404

### ISSUE THREAD

**Issue by schickling** [prisma/web#124]
When searching for `default selection set prisma client` on Google and clicking on the result, I'm getting a blank 404 page. We should look into this urgently.

![image](https://user-images.githubusercontent.com/1567498/78288188-b2a8d100-7521-11ea-87f0-7d6dfec3f85d.png)

![image](https://user-images.githubusercontent.com/1567498/78288398-c3594700-7521-11ea-97c5-acbbc13b8166.png)

**Comment by janpio** [comment]
Search result is different now, but the URL from the screenshot now works: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/generating-prisma-client
