### ISSUE TITLE
If page appears to not exist, link checker should see if page exists if you remove list of X suffixes (generated by tech switcher)

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1242]
The following links are always going to be broken because the `typescript-postgres` part is not part of the .mdx file name. Can we get the link checker to do something like:

If linked page does not exist, check if it _would_ exist if you remove any of the following suffixes: postgres, postgres-typescript, etc etc. If page exists minus suffix, then the link isn't broken.

**Comment by janpio** [comment]
This would probably need to be implemented in https://github.com/prisma/docs/blob/0f9af5eff81605c5d718247b0534ca537bf7a969/plugins/gatsby-remark-check-links-numberless/index.js#L121-L141 When that code decides that it is indeed a broken link, we should modify the URL by removing the known suffixes of the tech switcher, and check again (which should pass as the file exists).

**Comment by ankur-arch** [comment]
Closing as outdated.
