### ISSUE TITLE
Missing scalar field in one-to-many self-relation example

### ISSUE THREAD

**Issue by ranjan-purbey** [prisma/web#125]
Thanks to https://github.com/prisma/prisma/issues/2044#issuecomment-607966032 for pointing this out.

The example https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#one-to-many-self-relations is missing the scalar field `teacherId Int` and the `@relation` directive on `teacher` field has wrong value for `fields` (is `[id]`, should be `[teacherId]`)

**Comment by mhwelander** [comment]
Fixed by #375 - pardon delay and thank you! 💚
