### ISSUE TITLE
Generated types / Prisma validator

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1265]
For context, see: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1612447130099700

* Business use case: People want to re-use a `select` or `include` across their app
* `PrismaValidator` is a function that helps you do that & makes sure that the object you create is valid
* Suggest we add a section /h2 to the [generated types docs](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-generated-types)

**Comment by molebox** [comment]
This is really cool, i had a little play around with it...

```
    const createUserAndPost = Prisma.validator<Prisma.UserCreateInput>()({
        name: 'Emelie',
        email: 'ems@boop.com',
        posts: {
            create: {
                title: 'Hello World'
            }
        },
        profile: {
            create: {
                bio: 'Is a nurse'
            }
        }
    })

    const userProfileAndPosts = Prisma.validator<Prisma.UserInclude>()({
        posts: true,
        profile: true
    })

    await prisma.user.create({ data: createUserAndPost })

    const allUsers = await prisma.user.findMany({ include: userProfileAndPosts })
    console.dir(allUsers, { depth: null })
```

There are a ton of these helpers though, should i document them all in this issue?
