### ISSUE TITLE
[Help article] Document raw query pattern for "filter by relation count"

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1279]
We currently don't support [filtering by relation count](https://github.com/prisma/prisma/issues/3821) so we should document how to achieve this using the raw API.

**Comment by ruheni** [comment]
We added support for filter by relation count and it's documented here: https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing#filter-the-relation-count
