### ISSUE TITLE
Getting started tutorial refers to incorrect model author instead of post

### ISSUE THREAD

**Issue by jojo1311** [prisma/web#128]
## Bug description
https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-sql

## How to reproduce

1.- Go to  the section #Write date into the database
2.- Change author
![Screen Shot 2020-04-02 at 6 51 06 PM](https://user-images.githubusercontent.com/2288586/78307211-6b1b4880-7513-11ea-9086-de61ebcd010e.png)

## Expected behavior
It should be posts

## Environment & setup

- OS: [Mac OS]
- Javascript
- Database: [MySQL]

**Comment by nikolasburk** [comment]
Resolved thanks to your PR 🎉 🎉 🎉
