### ISSUE TITLE
[Help article] Document "default schema" pattern

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1280]
Currently we don't supported to "unselect" fields from a query (see this GitHub [issue](https://github.com/prisma/prisma/issues/3796)). This pattern (discussed on the [public Slack](https://prisma.slack.com/archives/CA491RJH0/p1612853767386400?thread_ts=1612836270.383400&cid=CA491RJH0)) enables developers to unselect fields:

![image](https://user-images.githubusercontent.com/4058327/107329576-a16d1100-6ab0-11eb-835c-4f2fdcfded21.png)

**Comment by ruheni** [comment]
The workaround guide on how to exclude fields can be found here: https://www.prisma.io/docs/concepts/components/prisma-client/excluding-fields.
