### ISSUE TITLE
CompoundUniqueInput not documented

### ISSUE THREAD

**Issue by jeremygottfried** [prisma/web#1283]
In order to run a `findUnique` query on a table with a multi-field ID, you need to use the following format--

```prisma
// Table schema

model MyModel {
  @@id([firstId, secondId])
  @@unique([firstId, secondId])
}
```

```js
// Query
prisma.myModel.findUnique({
  where: {
    firstId_secondId: {
      firstId,
      secondId,
    }
  }
})
```

```ts
// Type Definition
  export type MyModelWhereUniqueInput = {
    firstId_secondId?: MyModelFirstIdSecondIdCompoundUniqueInput
  }
```

I couldn't find documentation for this anywhere. 
I had to go into index.d.ts in the prisma client files and search for the format in the type definition.
Seems like there should be more thorough documentation on how compound (multi-field) IDs work with the prisma client.
If there's already documentation on this, maybe we could improve the SEO so it comes up on a google search?

**Comment by mhwelander** [comment]
Related: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1614583931048800

**Comment by mhwelander** [comment]
Now covered here: https://www.prisma.io/docs/concepts/components/prisma-client/crud#get-record-by-compound-id-or-unique-identifier

**Comment by SH4DY** [comment]
Hi everybody. I just stumbled upon this. It seems the documentation for these generated compound fields was lost again. In the link above I couldn't find any explanation of `CompoundUniqueInput`? @mhwelander @jeremygottfried

**Comment by janpio** [comment]
The old PR was here: https://github.com/prisma/docs/pull/1371/files#diff-246d7ca369d24765bce5e9caa7770e683db61bb263962471d0e640f42882c1e2R257
No idea where that content went.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
