### ISSUE TITLE
Google Cloud (GCP) Deployment Guide

### ISSUE THREAD

**Issue by matthewmueller** [prisma/web#1287]
We don't yet have a GCP deployment guide: https://www.prisma.io/docs/guides/deployment

We've been getting some SSL + GCP issues recently: https://github.com/prisma/prisma/issues/1228

I think people are running the `openssl` command here: https://www.prisma.io/docs/concepts/database-connectors/mysql#configuring-an-ssl-connection and getting confused that google doesn't trust their certificate.

It'd be good to properly document this.

**Comment by 2color** [comment]
@matthewmueller 
My suggestion would be to add a section in the [general deployment docs](https://www.prisma.io/docs/guides/deployment). 

As for the recommendation, based on https://github.com/prisma/prisma/issues/1228#issuecomment-767110358 it seems that the current solution is to add `sslaccept=accept_invalid_cert` to the connection string. Is that correct?

**Comment by matthewmueller** [comment]
My feeling is that `sslaccept=accept_invalid_cert` with a self-signed openssl certificate shouldn't be the default and that we should really recommend they connect with a trusted certificate `sslaccept=strict`. 

I think we should confirm that this works with Prisma though. Basically this setup: https://cloud.google.com/sql/docs/mysql/configure-ssl-instance

I believe @pantharshit00 will double-check, but if you're writing this already, please reach out to both of us.

**Comment by 2color** [comment]
Would be great if @pantharshit00 could confirm this. I haven't written anything yet.

**Comment by janpio** [comment]
What product of GCP?

**Comment by ruheni** [comment]
We currently don't have plans for adding this to the docs.
