### ISSUE TITLE
Doc request: Postinstall workaround for the Vercel guide

### ISSUE THREAD

**Issue by ryands17** [prisma/web#1300]
As per this discussion: https://github.com/prisma/prisma/discussions/5140

We should add the `postinstall` workaround that needs to be added to Vercel deployments as a point to note so that users are not stuck. Ideally should be added to this guide: https://www.prisma.io/docs/guides/deployment/deploying-to-vercel

**Comment by ruheni** [comment]
This is now documented here: https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/vercel-caching-issue
