### ISSUE TITLE
Bug report: Replace README.md with the correct reference

### ISSUE THREAD

**Issue by ryands17** [prisma/web#1304]
As per [this](https://prisma.slack.com/archives/CA491RJH0/p1613405464019000) discussion, the `README.md` text in [this](https://www.prisma.io/docs/reference/api-reference/command-reference#db-push-and-migrate-preview) section is incorrect and should be referenced to the correct DDL statement.

**Comment by Jolg42** [comment]
Closed by https://github.com/prisma/docs/pull/1305
