### ISSUE TITLE
Allow navigation in folders by adding content

### ISSUE THREAD

**Issue by janpio** [prisma/web#131]
Our content is pretty hierarchical, which is also represented in the "folder" structure of URLs:

https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/advanced-usage-of-generated-types

It would be nice we could also navigate through the docs by removing levels in the URL directly:

https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client
https://www.prisma.io/docs/reference/tools-and-interfaces
https://www.prisma.io/docs/reference

Right now these are all 404s as the content does not exist.

**Comment by nikolasburk** [comment]
What kind of content would you expect on these pages?

**Comment by janpio** [comment]
Probably a list of subpages with a short introduction for context.
