### ISSUE TITLE
Doc request: Update recommended workaround with NextJS & Prisma in development

### ISSUE THREAD

**Issue by sdnts** [prisma/web#1311]
Our docs have this section describing how to work around the `There are already 10 PrismaClients running` error during development with NextJS: https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices

In practice, there were a few more changes required to get this working correctly to make `tsc` happy:

```
declare global {
  var globalPrisma: PrismaClient
}

let prisma: PrismaClient
if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient()
} else {
  if (!global.globalPrisma) {
    global.globalPrisma = new PrismaClient()
  }
  prisma = global.globalPrisma
}
export { prisma }
```

Here are the two changes:

1. We have to add a `declare global` block
2. We need to call this global `prisma` instance something else, otherwise `tsc` thinks we're redeclaring `prisma`. This can also work the other way around, we can rename the real prisma variable `localPrisma` or something and rename it while exporting.

**Comment by mhwelander** [comment]
Also requires update in docs
