### ISSUE TITLE
Doc request: document empty conditionals

### ISSUE THREAD

**Issue by matthewmueller** [prisma/web#1315]
| Name |     0 Filter      |        1 Filter        |       2 Filter       |
| :--: | :---------------: | :--------------------: | :------------------: |
|  OR  | return empty list | validate single filter | validate all filters |
| AND  | return all items  | validate single filter | validate all filters |
| NOT  | return all items  | validate single filter | validate all filters |

Context: https://github.com/prisma/prisma/issues/4784#issuecomment-779845616

Perhaps on this page: https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined

Details: https://www.notion.so/prismaio/Filter-condition-reduction-behavior-450c7baa5c5d4835a2c5dcc49c3eb494

**Comment by mhwelander** [comment]
* Suggest adding a section to prisma.io/docs/concepts/components/prisma-client/null-and-undefined about the effects of `null` on conditionals
* Suggest adding one example to each reference section (`OR`, `AND`, `NOT`) with a link to the general explanation: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#and
