### ISSUE TITLE
Doc request: Add example on how to have a deeply nested variation of a generated model type

### ISSUE THREAD

**Issue by tgeorgiadis** [prisma/web#1317]
For the solution of **Problem: Using variations of the generated model type** on this [page](https://github.com/prisma/docs/blob/master/content/200-concepts/100-components/02-prisma-client/052-working-with-generated-types.mdx#solution
), it would be good to have an example of how we can have a deeply nested variation.

For the solution provided there

```
import { Prisma } from '@prisma/client'

// Define a type that includes the relation to `Post`
type UserWithPosts = Prisma.UserGetPayload<{
  include: { posts: true }
}>
```
Could we have an example of how to incorporate a type like the following into the `UserWithPosts` type?

```
type PostWithComments = Prisma.PostGetPayload<{
  include: {comments: true}
}>
```

**Comment by ankur-arch** [comment]
@tgeorgiadis this should be covered [here](https://www.prisma.io/docs/orm/prisma-client/type-safety). Closing this as it's slightly outdated.
