### ISSUE TITLE
Search results that include tech switcher pages do no redirect to -typescript-postres 

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1320]
Originally posted in Slack https://prisma-company.slack.com/archives/C5Z9TH6N9/p1613572820188600
and
https://prisma-company.slack.com/archives/C5Z9TH6N9/p1614878783076700

**Comment by Jolg42** [comment]
Note in the network tab when passing the mouse over the link from the search result this happens

<img width="1582" alt="Screen Shot 2021-02-17 at 15 59 31" src="https://user-images.githubusercontent.com/1328733/108236538-4f2e8e80-7147-11eb-8cc3-a77324fb1abe.png">

- 200 GET https://www.prisma.io/docs/page-data/app-data.json
- 404 GET https://www.prisma.io/docs/page-data/getting-started/setup-prisma/start-from-scratch/page-data.json
- 200 GET https://www.prisma.io/docs/page-data/404.html/page-data.json
- 404 HEAD https://www.prisma.io/getting-started/setup-prisma/start-from-scratch

Note the last url is missing `/docs/` somehow
