### ISSUE TITLE
@map attributes should be properly explained 

### ISSUE THREAD

**Issue by omar-dulaimi** [prisma/web#1333]
Hello,
I'm in the process of upgrading our prisma1 project to prisma 2. While the upgrade cli can be helpful, it's still far from perfect and have multiple issues.
One of the issues I'm facing is that I couldn't get the purpose of the @map attribute, especially when used in the context of self relations. 

So it would be great to have it explained in a section on this page: 
https://www.prisma.io/docs/concepts/components/prisma-schema/relations

**Comment by janpio** [comment]
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#map does not give you the information you are looking for? (Found via searching for `@map` in the docs)

**Comment by omar-dulaimi** [comment]
@janpio I honestly remained confused even after reading the explanation. It's also not clear whether renaming all underscored names to Prisma conventions would delete/drop data/tables in database or not.
