### ISSUE TITLE
Doc request: CONTRIBUTING.md 

### ISSUE THREAD

**Issue by Swapnull** [prisma/web#1335]
Hey, 

I have just opened a small PR against this repo to fix some incorrect documentation. I basically had to look up what other people were doing in terms of naming branches and pull requests, although there is no particular consensus. 

We should add a CONTRIBUTING.md which either includes how you would like this information delivered like the main repo has, or some text saying that it can come however the individual likes.

**Comment by ankur-arch** [comment]
Closing this as we have a contributing [guide now](https://github.com/prisma/docs/blob/main/CONTRIBUTING.md).
