### ISSUE TITLE
Doc request: Missing Json field access - Docs only show creating and filtering

### ISSUE THREAD

**Issue by danwetherald** [prisma/web#1337]
The docs here: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-advanced-types#working-with-json

These docs oddly only show how to create records with Json and filter them by that Json. It is missing the most important part, data access.

Why does this not show how to access the Json attributes once you have found the record?

This should also be specific to Typescript being that Prisma advertises that it's an ORM for Typescript.

**Comment by nikolasburk** [comment]
(see my closed issue for a code example: https://github.com/prisma/docs/issues/1338)
