### ISSUE TITLE
Doc request: Document the types exported under the `Prisma` namespace

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1339]
We should have proper docs (probably a reference) for all types that are exported under the `Prisma` namespace (e.g. `Prisma.JsonObject`).

**Comment by ankur-arch** [comment]
@nikolasburk I think we can close this as the pages below should have that information:

https://www.prisma.io/docs/orm/prisma-schema/data-model/models
https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types

WDYT?
