### ISSUE TITLE
Bug report: Schema incompatibilities page shows wrong example for MySQL

### ISSUE THREAD

**Issue by omar-dulaimi** [prisma/web#1340]
Hello,

I have been going through the page while in the process of upgrading from Prisma 1 to 2, and I came across this issue where the suggested fix does not get recognized as a MySQL syntax. Only then I noticed that it is actually meant for Postgres.

So the entire workaround section should be changed to MySQL.

Example:
```
CREATE TYPE "Role" AS ENUM ('CUSTOMER', 'ADMIN');
```

should be changed to:
```
ALTER TABLE `TABLE_NAME` CHANGE `role` `role` ENUM('CUSTOMER', 'ADMIN');
```

**Comment by ankur-arch** [comment]
You have to use the techswicther to get the [right example](https://www.prisma.io/docs/orm/more/upgrade-guides/upgrade-from-prisma-1/schema-incompatibilities-mysql#workaround-4).
