### ISSUE TITLE
Bug report: [Help article] Should I use `select` in GraphQL resolvers.

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1343]
This question comes up repeatedly so we should be able to point to our docs to answer it.

Here is an example from Slack: https://prisma.slack.com/archives/CKQTGR6T0/p1614079245143600

![image](https://user-images.githubusercontent.com/4058327/108837357-67ccf780-75d2-11eb-829c-5c55a99988e2.png)

**Comment by mhwelander** [comment]
@nikolasburk Could you explain a bit more how this is related to n+1? I'm writing those docs right now, but my only point is to use `findUnique` because they get batched by the dataloader. This sounds like it's about the size of the returned object.

**Comment by mhwelander** [comment]
Answered in Slack. :)

**Comment by mhwelander** [comment]
Related: #1244

**Comment by mhwelander** [comment]
@ryands17 Did you want to write a separate help article specifically for this combination of keywords (`select`, GraphQL resolvers, SDL, etc)? I'm going to write general performance advice about a limited `select` probably not making a huge difference in most cases.

**Comment by nikolasburk** [comment]
Just adding this as more context as to what should be documented:

![image](https://user-images.githubusercontent.com/4058327/108870566-86de8000-75f8-11eb-8034-58214ae8c05c.png)

![image](https://user-images.githubusercontent.com/4058327/108870587-8b0a9d80-75f8-11eb-85a3-7bc969411949.png)
