### ISSUE TITLE
Bug report: Relations page should be provided in MySQL as well

### ISSUE THREAD

**Issue by omar-dulaimi** [prisma/web#1349]
Hello, 
I just noticed that this page https://www.prisma.io/docs/concepts/components/prisma-schema/relations examples are all Postgres, and it would be nice to have the toggle button at the top of the page to switch examples/explanations.

**Comment by ankur-arch** [comment]
They are for relational dbs and mongo. The schema blocks have a switcher in them.
https://www.prisma.io/docs/orm/prisma-schema/data-model/relations
