### ISSUE TITLE
Doc request: Document Migrate workflow for adding DB triggers

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1358]
We should an example migration flow for creating a SQL trigger in a DB.

**Comment by mhwelander** [comment]
How to work around unsupported features with Prisma Migrate: https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/add-prisma-migrate-to-a-project#work-around-features-not-supported-by-prisma-schema-language

**Comment by janpio** [comment]
A trigger might be common enough request that we could document this as an example (or similar to how we document the views workaround).
