### ISSUE TITLE
Implements the document search

### ISSUE THREAD

**Issue by adrianoresende** [prisma/web#137]
When I need to look for some information in the documentation, it is sometimes difficult to find where to talk about it.

For better UX, why not implement search as an example Vue Documentation?

![image](https://user-images.githubusercontent.com/798755/78461294-10fabe80-769e-11ea-862f-98bb9fa6ea46.png)

**Comment by nilubava** [comment]
@adrianoresende This is already a work in progress, and will be available soon! Here is how it will look like: 
![image](https://user-images.githubusercontent.com/8801572/78544380-53d1a900-77fa-11ea-95af-73216e9e442f.png)

**Comment by adrianoresende** [comment]
Why you don't move search to inside navigation where have position stick?
When I scroll down, every time I scroll up to click search.
