### ISSUE TITLE
Doc request: Guide for "DB migrations without downtime"

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1376]
Based on this user's question: https://prisma.slack.com/archives/CA491RJH0/p1614705197214700

![image](https://user-images.githubusercontent.com/4058327/109765059-9d866780-7bf4-11eb-95c6-b00beb72fb38.png)

**Comment by ruheni** [comment]
We may have documented (this but not extensively) here: https://www.prisma.io/docs/guides/migrate/developing-with-prisma-migrate/customizing-migrations#example-use-the-expand-and-contract-pattern-to-evolve-the-schema-without-downtime. 

I think we could make it easy to find by making it a separate guide.

**Comment by nikolasburk** [comment]
Actually I think that should be enough 👍
