### ISSUE TITLE
Doc request: Add note to fluent API section that DataLoader batches queries

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1377]
Based on this input from a user on Slack: https://prisma.slack.com/archives/CCWDULGUW/p1614721662029000

![image](https://user-images.githubusercontent.com/4058327/109765227-daeaf500-7bf4-11eb-9d8f-24f368930ef8.png)

**Comment by mhwelander** [comment]
It's not specifically the fluent API that enables batching of queries - we always batch `findUnique`, so the somewhat counterintuitive `prisma.user.findUnique(...).posts()` it's the only option for GraphQL resolvers (better to have 2 queries than n+1). If we batched `findMany`, you would not have to do this.

I have added an explanation here: https://www.prisma.io/docs/guides/prisma-guides/query-optimization-performance#do-i-have-to-use-the-fluent-api-to-enable-batching-of-queries

And linked to the n+1 doc from the fluent API docs as a use case.
