### ISSUE TITLE
Troubleshooting: Environment is “non-interactive” when using `prisma migrate dev`

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/web#1379]
When running `prisma migrate dev` or any other interactive Migrate command with docker, it may complain about the environment being non-interactive:

```
Error: We detected that your environment is non-interactive. Running this command in not supported in this context.
```

Workaround for Docker:

```
docker run --interactive --tty <image name>
# or
docker -it <image name>

# Example
docker run -it node 
```

Other: Users should open an issue or suggest a workaround.

More context: https://github.com/prisma/prisma/issues/4669

**Comment by albertoperdomo** [comment]
Related to https://github.com/prisma/docs/issues/610

**Comment by molebox** [comment]
Popping this SO question here as it holds some handy knowledge about these recommended flags: https://stackoverflow.com/questions/59965032/docker-run-with-interactive-and-tty-flag
