### ISSUE TITLE
Add some documentation on advisory locking 

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/web#1381]
Migrate has an advisory locking mechanism since 2.17 implemented by @tomhoule

see prisma/prisma-engines#1118

Why a locking in Migrate?

Because migrations should not be running concurrently on the same database, becausing running migrations concurrently can be really dangerous, especially in production.

I think it would be great to document this and have an answer for

What happens if two migrate deploy command run simultaneously? One gets the lock and the other fails?
Does it uses timeouts? Is it configurable?

**Comment by Jolg42** [comment]
@tomhoule would be the good person to ask for the details / timeout.

**Comment by albertoperdomo** [comment]
On MySQL and PostgreSQL, Prisma Migrate uses a database feature called advisory locks when attempting to run a migration, to prevent concurrent migrations from trying to modify the database simultaneously.

What is an advisory lock?

Databases have different lock modes to control concurrent access to tables and data. Avisory locks are a convenient way for the application layer (in this case Prisma Migrate) to acquire a lock.

The lock is acquired when starting and released when exiting and completely application-enforced. This enables Prisma Migrate to ensure it won't concurrently without actually locking the database for writing or having any noticeable user-facing impact.

Helpful resources (for us to document):

* https://github.com/rails/rails/pull/22122
* https://blog.saeloun.com/2019/09/09/rails-6-disable-advisory-locks.html

**Comment by Jolg42** [comment]
Note: it's only used in `migrate resolve` and `migrate deploy`

**Comment by doflo-dfa** [comment]
This mechanism can hang all subsequent migrations if you suffer a broken connection mid migration ... ( which is probably good )

this doc helped me quite a bit.

https://aws.amazon.com/premiumsupport/knowledge-center/rds-aurora-postgresql-query-blocked/

**Comment by janpio** [comment]
Do you think that is a problem in our implementation? If so, please open an issue in the main prisma/prisma repo and provide all the information you have backing that. Happy to take a look. (But here in the docs repo it will be missed as we can not prioritize these issues for our Engineering teams).

**Comment by doflo-dfa** [comment]
@janpio I am not sure how an implementation change would really solve the issue as for all intents and purposes it worked as designed. 

It can and has left our DB in a state that was unworkable until additional steps were taken to resolve it however. 

Which is what the document I sent helped us reason through ... obvious issue here is that it is rather specific ... but I also thought maybe a footnote about how deadlocking after a broken (disconnect mid-migration) migration could lead to a state that requires manually clearing the locks could help someone in the future. I will open a prisma/prisma issue around the possibility of a deploy argument that would clear these locks via the CLI in the rare cases they occur.

**Comment by hussamkhatib** [comment]
@doflo-dfa Did you manage to open a Issue for this ?
