### ISSUE TITLE
Suggested fix for "Best practice for instantiating PrismaClient with Next.js"

### ISSUE THREAD

**Issue by devuxer** [prisma/web#1391]
The code provided in https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices generates an error with TypeScript in strict mode.

I would suggest something like this instead:

```ts
import { PrismaClient } from "@prisma/client";

// add prisma to the NodeJS global type
interface CustomNodeJsGlobal extends NodeJS.Global {
    prisma: PrismaClient;
}

// prevent multiple instances of Prisma Client in development
declare const global: CustomNodeJsGlobal;
const prisma = global.prisma || new PrismaClient();
if (process.env.NODE_ENV === "development") global.prisma = prisma;
export default prisma;
```

**Comment by meotimdihia** [comment]
I have got this error: `Namespace 'NodeJS' has no exported member 'Global'.` with @types/node@^16. 

Downgrade to @types/node@^15 to work again.

**Comment by trentprynn** [comment]
In case anyone runs into this while updating `@types/node` to version 16, I got around this error by replacing the above code (which works with `@types/node<16`) with the following

```js
import { PrismaClient } from '@prisma/client'

// add prisma to the NodeJS global types to
// prevent multiple instances of prisma client
// get created by hot-reloading in development
declare global {
    var prisma: PrismaClient
}

const prisma = global.prisma || new PrismaClient()

if (process.env.NODE_ENV === 'development') {
    global.prisma = prisma
}

export default prisma
```

You can see it in context [here](https://github.com/trentprynn/habitapper.com/blob/master/prisma/client.ts) where I'm using prisma for database interaction for an open source habit tracking web app I'm working on 

EDIT: [The documentation](https://www.prisma.io/docs/support/help-articles/nextjs-prisma-client-dev-practices) is now updated with a similar (probably better) solution

**Comment by Emnalyeriar** [comment]
@trentprynn Thanks for the code snippet, it works great. The documentation link you provided shows the updated code but the example code shown in section "[Prevent hot reloading from creating new instances of PrismaClient](https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#prevent-hot-reloading-from-creating-new-instances-of-prismaclient)" still shows the old code.

**Comment by janpio** [comment]
Can you quickly open a new issue about that @Emnalyeriar? Thanks.

**Comment by sindrebakk1** [comment]
Is there a similar workaround for vanilla js? I guess you could just declare it as a global var while in development, but is there a nice way of doing it conditionally like the ts example provided?

**Comment by madfcat** [comment]
Here is the way they do it in [shopify template](https://github.com/Shopify/shopify-app-template-remix/blob/main/app/db.server.ts):

```
import { PrismaClient } from "@prisma/client";

declare global {
  var prismaGlobal: PrismaClient;
}

if (process.env.NODE_ENV !== "production") {
  if (!global.prismaGlobal) {
    global.prismaGlobal = new PrismaClient();
  }
}

const prisma = global.prismaGlobal ?? new PrismaClient();

export default prisma;

```
