### ISSUE TITLE
Quickstart querying and inserting data not working

### ISSUE THREAD

**Issue by twice** [prisma/web#1401]
Hi, I followed the quickstart from scratch js version of docs. But the node index.js file prisma client examples do not work for me. 
The console statement to print `allUsers` just hangs indefinitely and doesn't print anything. The same goes for the create example. 

When I try to use the prisma example, it only show empty database tables and when I try to view queries they indicate a `Prisma client error - Unable to run script`. 

The studio console is displaying the following message

```
Message: Unable to communicate with Prisma Client. Is Studio still running? You may need to restart it using `npx 'prisma studio' 

Query:
prisma.post.findMany({
  take: 100,
  skip: 0,
  select: {
    id: true,
    createdAt: true,
    updatedAt: true,
    title: true,
    content: true,
    published: true,
    author: true,
    authorId: true,
  }
})
``` 

By the way the error messages displayed don't seem to be much helpful.

I'm running prisma versions (cli+client) 2.18.0, node version 11.14.0 on High Sierra.

By the way you have one of the best docs around but my experience so far is that the software doesn't seem to tally with the quality of the docs :(

**Comment by twice** [comment]
Thanks so much. It was my fault. Your node suggestion worked. It now works!!
Your documentation and resources are top notch. It's what attracted me.
Thanks.

**Comment by Jolg42** [comment]
Glad it worked! <3
