### ISSUE TITLE
Hooks / hooking into Prisma Client

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1402]
## Suggested action

Create a "Hooking into PrismaClient" page that mentions:

* Middleware
* The `beforeExit` hook

This is mostly for Google-foo - folks sometimes look for 'hooks' when they want middleware.

**Comment by ankur-arch** [comment]
I'm closing this issue as [Middlewares](https://www.prisma.io/docs/orm/prisma-client/client-extensions/middleware) is now deprecated 🙏.
