### ISSUE TITLE
Inconsistent casing in some titles 

### ISSUE THREAD

**Issue by molebox** [prisma/web#1418]
Some of the title on the docs ages have inconsistent casing, for example:

- Prisma Client API Reference
- Prisma Client error reference
- Prisma schema API reference

We should choose one or the other, neither is wrong but mixing them looks odd

**Comment by mhwelander** [comment]
Good spot, Prisma Client API Reference> **Prisma Client API reference** for sure - we should use sentence case.

Prisma Client is capitalized because it's a product name, but Prisma schema is not a product but an underlying concept, so we don't capitalize that at the moment.

**Comment by molebox** [comment]
> Good spot, Prisma Client API Reference> **Prisma Client API reference** for sure - we should use sentence case.
> 
> Prisma Client is capitalized because it's a product name, but Prisma schema is not a product but an underlying concept, so we don't capitalize that at the moment.

Cool, i havent dived into how many other places this might be, it could be that its a simple fix with just that one instance, i can assign myself to this.

**Comment by molebox** [comment]
Fixed in #1428
