### ISSUE TITLE
Squashing migrations

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1421]
## Context

https://github.com/prisma/prisma/issues/5226#issuecomment-790662655

## Suggested action

Add as a separate guide here: https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate - "Squashing migrations"

**Comment by ruheni** [comment]
Covered here: https://www.prisma.io/docs/guides/migrate/developing-with-prisma-migrate/squashing-migrations
