### ISSUE TITLE
Document how to deal with provider mismatch when using Prisma Migrate

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/web#1435]
In https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-limitations-issues#you-cannot-switch-database-providers we mention the limitation of not being able to switch provider, but we don't explain how to resolve it.

The process consists basically:
1. Get rid of the migrations directory, either by removing it (it should be versioned you can always to back to git history if you want to look at old migrations) or moving it to a separate directory
2. Start a new migration history with `prisma migrate dev`. Note this will create one single new migration and previous customizations done to SQL migrations will obviously be missing.

Addressing potential concerns users may have:
* "But I lose my entire migration history!" If you are switching databases, the migration history for the previous RDBMS is probably not so useful. You can still check it out on git if it's valuable. Over time, migrations become less interesting. Rarely does one go back 6 months ago to understand how a specific change was made. Changes are relevant mostly in the present.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
