### ISSUE TITLE
Include sample output for re-introspection

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1444]
## Suggested action 

Introspect, edit a schema, and introspect again. Show what 'warnings' look like - for example, Prisma will copy from old schema to 'new' introspected schema. Add section here: https://www.prisma.io/docs/concepts/components/introspection#introspection-with-an-existing-schema

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
