### ISSUE TITLE
Please give an example with String

### ISSUE THREAD

**Issue by BertCatsburg** [prisma/web#1447]
This page:
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#attribute-functions
Only examples are with autoincrement(). 
But how to specify a string is not clear from your documentation. 

Please give more examples, and not only the obvious and simple ones.

**Comment by janpio** [comment]
The page and section you link to is explicitly about attribute functions - but you are right, we do not have any `@default` example anywhere else as well:

https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#default
https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#defining-a-default-value

It is mentioned in the text that you can use static values as Strings or Ints - but there is nothing in the example that would illustrate that. We should add that.

**Comment by janpio** [comment]
Update: The API reference actually has examples for all kinds of types, I just did not see that as I was distracted by the function in between: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#examples-7

**Comment by molebox** [comment]
Hey @BertCatsburg, did you manage to check out the page @janpio linked above? Does it provide the information you're looking for?

**Comment by ankur-arch** [comment]
Closing this issue as this section has all the other [options](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#examples-7) listed.
