### ISSUE TITLE
Website bug report: Padding in CLI result missing

### ISSUE THREAD

**Issue by timsuchanek** [prisma/web#1467]
https://www.prisma.io/docs/concepts/components/prisma-client/crud#create-a-single-record-using-generated-types

![image](https://user-images.githubusercontent.com/1094804/111980140-31699600-8b06-11eb-9e71-7aa4d1cda1fc.png)

I would expect the `Show CLI results` to have a bit more padding to the top.
This happens on Chrome and Mac.

**Comment by meletj** [comment]
Already fixed 

![Image](https://github.com/prisma/docs/assets/70962362/0e7f9ff1-95c0-42a6-948b-0da8f6396d7e)
