### ISSUE TITLE
"Deployment platforms" page

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1471]
* List deployment platforms that we test (see e2e tests in related thread - no need to specify that we test them)  and all 'combos' - e.g. vercel + redwood, vercel + nextjs https://github.com/prisma/e2e-tests/tree/dev/platforms
* Check with team if there are any other platforms we should list (maybe ones we don't support & why)
* Move AWS beanstalk section in 'Deployment overview' to this page
* Document #841 under AWS Lambda section (AWS Lambda + WebPack combination)
* If we have a deployment guide, link to it

Related context: https://prisma-company.slack.com/archives/CEYCG2MCN/p1616411590042800

**Comment by molebox** [comment]
Im going to hold of documenting https://github.com/prisma/docs/issues/841 as there are many other issues in the same space that are up in the air. We (Prisma) have been working on a [patch](https://github.com/prisma/prisma/issues/6051) for one such issue but others remain. The linked issue is now 1 year old and according to other more recent issues, out of date.
