### ISSUE TITLE
Split CRUD into sections based on operations

### ISSUE THREAD

**Issue by molebox** [prisma/web#1487]
The [CRUD](https://www.prisma.io/docs/concepts/components/prisma-client/crud) page is becoming a beast, lets tame it by splitting it up into sections based on the operations.

**Comment by molebox** [comment]
Didnt you do this in a PR @mhwelander ?

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
