### ISSUE TITLE
Website bug report: link to "start from scratch" broken

### ISSUE THREAD

**Issue by fnune** [prisma/web#1495]
Hey there,

In this URL: https://www.prisma.io/docs/getting-started/quickstart-typescript

I clicked on this link:

![image](https://user-images.githubusercontent.com/16181067/112749573-763c7380-8fc3-11eb-913c-4d417af3fa53.png)

It led me here: `https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-typescript-postgres-typescript-postgres/` which 404s.

It seems like the right URL would be `https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-typescript-postgres`

**Comment by rahul3v** [comment]
is working fine now ...!
