### ISSUE TITLE
vertical spacing of numbered lists

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#150]
Is this the right spacing for a numbered list? ([sample page](https://www.prisma.io/docs/guides/upgrade/upgrading-from-prisma-1#main-differences-between-prisma-1-and-prisma-20))

![image](https://user-images.githubusercontent.com/4058327/78645156-5219eb00-78b7-11ea-9493-58306c300c81.png)

Seems like there could be a bit more vertical space between the list items.

~~~
Based on these differences, the high-level steps to upgrade a project from using Prisma 1 are as follows:

1. Install the new Prisma 2.0 CLI as a development dependency
1. Use the Prisma 2.0 CLI to introspect your Prisma 1 database and generate your Prisma schema
1. Install and generate Prisma Client 2.0
1. Adjust your application code, specifically replace the API calls from the Prisma client 1.0 with those of Prisma Client 2.0
~~~

**Comment by nikolasburk** [comment]
While at it, we should also fix the vertical spacing when there's a line break in the sidenav

![image](https://user-images.githubusercontent.com/4058327/82420652-50c80a80-9a80-11ea-86cf-70c92470df97.png)

**Comment by matthewmueller** [comment]
**First Part**

For this, we just need to treat `<ol>` tags in the same way that we treat `<ul>` tags. Concretely this means we need to add 10px to the top of each list item in an ordered list:

```css
ol li {
  margin-top: 10px;
}
```

Source: https://www.prisma.io/docs/guides/upgrade-from-prisma-1/should-you-upgrade#upgrade-path

**Second Part**

Add `line-height: 1.25` to each of the list items in the sidebar

<img width="251" alt="CleanShot 2020-05-26 at 14 58 13@2x" src="https://user-images.githubusercontent.com/170299/82903542-65654080-9f61-11ea-9ad4-2678b0c1e1a1.png">

---

@nilubava would know best on how to add this to our current setup.
