### ISSUE TITLE
Case sensitive links in markdown are rendered in lowercase

### ISSUE THREAD

**Issue by 2color** [prisma/web#1518]
Some links are case sensitive, for example: 
- This works https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey
- But this doesn't: https://docs.aws.amazon.com/iam/latest/userguide/id_credentials_access-keys.html#using_createaccesskey

Unfortunately, when adding a link with uppercase characters in markdown, the markdown renderer converts the link to lowercase which breaks the link.

The current workaround I found is to use `<a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey">AWS Docs</a> in the markdown.

Example of the workaround in the docs: https://github.com/prisma/docs/blame/fc389a7d392a44268d7ecceba3550aa6a0af75cd/content/300-guides/200-deployment/400-deploying-to-aws-lambda.mdx#L39

Would be good to get this fixed so we don't have to use the workaround.

**Comment by janpio** [comment]
Still the case and causing problems like https://github.com/prisma/docs/issues/2697 and requiring workaround like https://github.com/prisma/docs/pull/2698
