### ISSUE TITLE
process.exit() and $disconnect

### ISSUE THREAD

**Issue by jplindstrom** [prisma/web#1528]
Reading this page: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-management

It would be nice with some guidance regarding `$disconnect` in conjunction with cli scripts that use `process.exit(1)` to exit with a certain exit code.

(Normally I would expect that exiting a process with a database connection would close that connection, but it seems like there's another process hanging around with the connection that never gets closed (so eventually the db has no more free connections to use).)

**Comment by molebox** [comment]
Hey @jplindstrom! Thanks for opening this issue, wouldyou be able to provide us with some more details please? It would be great if you could provide:
- Your dev environment
- A repo that replicates the issue.

`process.exit(1)` should terminate the child process (the query engine) which should close the connextion to the database.

Thanks! And happy friday! 🙌

**Comment by ruheni** [comment]
👋

We've added some context on the page on scenarios of when to disconnect explicitly and how to do that in our docs. Could you let me know if our provided information answers your question? Feel free to reopen the issue if your question hasn't been answered. 🙂

<img width="483" alt="CleanShot 2023-05-25 at 14 44 40@2x" src="https://github.com/prisma/docs/assets/33921841/9856ff8a-ca33-4585-9c30-86f37039b30a">
