### ISSUE TITLE
Doc request: Document how you can extend PrismaClient when using event based logging. 

### ISSUE THREAD

**Issue by pantharshit00** [prisma/web#1564]
You will need to use a generic when doing this which is not clear in first go to beginners so we should document this. 

More information here: https://github.com/prisma/prisma/issues/6279#issuecomment-808702894

Example here: https://github.com/prisma/prisma/issues/4746#issuecomment-750949556

**Comment by pantharshit00** [comment]
Another variant of the same topic: https://github.com/prisma/prisma/issues/6774#issuecomment-876498070

**Comment by prithvihv** [comment]
@pantharshit00 https://github.com/prisma/prisma/issues/15309#issue-1372169392 might this be related?

**Comment by nikelborm** [comment]
May be related https://github.com/prisma/prisma/pull/24133

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
