### ISSUE TITLE
Feedback on "Atomic number operations"

### ISSUE THREAD

**Issue by janpio** [prisma/web#1577]
https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#atomic-number-operations

- Can this only be used with ´findMany`?
- What data structure will this return? 
- - Will I be able to see the updated # or just how many it updated?

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
