### ISSUE TITLE
Website bug report: When using right sidebar toc navigation, both sidebars disappear until I scroll a bit

### ISSUE THREAD

**Issue by janpio** [prisma/web#1586]
This is happening sometimes:
When I click a link in the right sidebar table of content navigation, I jump to the anchor, but both sidebars are invisible until I scroll a bit.

![image](https://user-images.githubusercontent.com/183673/115426787-212a0100-a201-11eb-9cde-9f7e3f75f4b4.png)
![image](https://user-images.githubusercontent.com/183673/115426803-28510f00-a201-11eb-9b0c-15f6368e2f86.png)

Now when I try to reproduce this, I can not.

**Comment by meletj** [comment]
@janpio can I check if you faced that issue again? I've tried to reproduce on different browsers but didn't happen.

**Comment by janpio** [comment]
Not that I am aware of recently.
