### ISSUE TITLE
Video tutorials

### ISSUE THREAD

**Issue by SilentShroud** [prisma/web#1591]
it will be more helpful to include video tutorials for those that are more visual learners

**Comment by mhwelander** [comment]
Hi @SilentShroud! Adding more video content to the docs is certainly something we would like to do. I can direct you to what we have currently - here the playlist of short Prisma Guides: https://www.youtube.com/watch?v=FMnlyi60avU&list=PLn2e1F9Rfr6mmmlwyxznax1HjnaiLBEy4 But 

We embed those videos in the docs: https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#sort-by-relation-aggregate-preview

Is there a specific topic you think would be easier to digest as video content?

**Comment by ankur-arch** [comment]
Closing as we have our videos in youtube.
