### ISSUE TITLE
pgBouncer / Migrate workaround

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1596]

**Comment by tomhoule** [comment]
Migrate uses transactions for checking out the current state of the database and the migrations table. We have special connection management code in Client (Query Engine) to make transactions work with PgBouncer, but not in Migrate (Migration Engine), meaning you can run into confusing errors if you use Migrate with a Postgres database behind PgBouncer. Migrate only needs a single connection to the database, so it does not use or support connection pooling: users should connect directly to the database server without going over PgBouncer. How to achieve this depends on the particular setup or cloud provider ([example](https://github.com/prisma/prisma/issues/6701), [other example](https://github.com/prisma/prisma/issues/6157)).

Related issues:

- https://github.com/prisma/prisma/issues/6480
- https://github.com/prisma/prisma/issues/6053
- https://github.com/prisma/prisma/issues/4752

**Comment by janpio** [comment]
Example for an error that would pop up if you use Migrate with a PgBouncer connection:

```
Error querying the database: db error: ERROR: prepared statement "s0" already exists
```

**Comment by Euregan** [comment]
Hello, are you sure this is working as intended? I am using version 2.30.0 of Prisma, and I still get the same error when migrating over pgbouncer

**Comment by janpio** [comment]
Migrate can not run reliably over PgBouncer with Prisma unfortunately - optimally use the unpooled connection string: https://www.prisma.io/docs/guides/performance-and-optimization/connection-management/configure-pg-bouncer#prisma-migrate-and-pgbouncer-workaround You can follow https://github.com/prisma/prisma/issues/6485 for updates if we can improve this on our side.
