### ISSUE TITLE
eslint for multiple PrismaClient

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1600]
## Context

https://prisma-company.slack.com/archives/C5Z9TH6N9/p1619094480454000?thread_ts=1619093858.452200&cid=C5Z9TH6N9

## Suggested action

Add as a tip to this section: http://prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/instantiate-prisma-client#the-number-of-prismaclient-instances-matters

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
