### ISSUE TITLE
Type tooltips for Prisma Client results

### ISSUE THREAD

**Issue by janpio** [prisma/web#1609]
https://twitter.com/orta/status/1385196377714700291

![image](https://user-images.githubusercontent.com/183673/115893727-d3a7d100-a458-11eb-869a-fb3c45e66788.png)

Internal discussion: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1619098745455900

**Comment by molebox** [comment]
This would be cool, we could use [tippy js](https://atomiks.github.io/tippyjs/)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
