### ISSUE TITLE
Download SQLite starter project & install dependencies

### ISSUE THREAD

**Issue by o-t-w** [prisma/web#1623]
I am trying to do the quickstart tutorial with Javascript 

I am using Windows. On PowerShell the curl command
```
curl https://codeload.github.com/prisma/quickstart/tar.gz/master -o master.tar.gz && tar -zxvf master.tar.gz quickstart-master/javascript/starter && move quickstart-master\javascript\starter starter && rmdir /S /Q quickstart-master && del /Q master.tar.gz
```
gives me the error 'the token && is not a valid statement separator in this version.'

I tried it in the Ubuntu shell on Windows instead and it says "Command 'move' not found"

**Comment by ruheni** [comment]
Hi 👋

We've revamped the quickstart guide and used a different format now. This should be resolved. Let us know if you run into any issues.
