### ISSUE TITLE
wrong form URL on https://www.prisma.io/docs/concepts/database-connectors/mongodb

### ISSUE THREAD

**Issue by bttmly** [prisma/web#1624]
page in question: https://www.prisma.io/docs/concepts/database-connectors/mongodb

here in the github repo the link is correct: `https://prisma103696.typeform.com/to/FriDuIeM`
it seems when the site it built, the link is downcased, resulting in `https://prisma103696.typeform.com/to/friduiem` (note the last part of the path) while Typeform appears to be case-sensitive – if you click the link on the prisma.io page, you wind on on a generic Typeform sales page: https://www.typeform.com/explore/?utm_source=typeform.com&utm_medium=typeform&utm_content=typeform-incorrectURL&utm_campaign=viral_expt (note the query param `utm_content=typeform-incorrectURL`)

**Comment by mhwelander** [comment]
Good catch! Seems our Markdown links get turned into lower case - changed to regular HTML and it works now. Thanks you for reporting it!
