### ISSUE TITLE
Page for schema examples that cover real-world scenarios

### ISSUE THREAD

**Issue by m-abdelwahab** [prisma/web#1626]
While the `User` and `Post` models are [great for understanding concepts](https://www.prisma.io/docs/about/about-the-docs#overview), it would be nice to have examples of Prisma schemas that show different real-world scenarios. These examples can be used as a starting point and help save time when building apps using Prisma.

Ideas should be collected in this issue ⬇️

**Comment by molebox** [comment]
Im currently using a light ecommerce schema for integration testing guide. This includes:
- Customer
- Product
- Order
- OrderDetails
- Invoice

By light, i mean that its still not a terribly in depth schema but i think an ecommerce schema that has cart and accounts etc.. would be of great value to people

**Comment by Yasir5247** [comment]
may be showing how to do more complex queries.

**Comment by m-abdelwahab** [comment]
@Yasir5247 the goal of this page wouldn't be focused on querying, but the actual database schema design

**Comment by ruheni** [comment]
This is not within the scope of our docs. However, you can find "grab-and-go" schemas here in this project
Website: https://grab-and-go-prisma-schemas.vercel.app/docs/intro
Repo: https://github.com/sethdavis512/grab-and-go-prisma-schemas
