### ISSUE TITLE
Make the example projects more visible

### ISSUE THREAD

**Issue by molebox** [prisma/web#1629]
Currently the [example projects](https://www.prisma.io/docs/about/example-projects) are hidden in the about section. I didnt even know it existed.

I think this is a great opportunity to showcase Prisma. We could consider moving this to a more visible place so our readers can better find it.

Internal convo: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1620029298002300

**UPDATE** 
Blocked by #4877

**Comment by ankur-arch** [comment]
Closed as this is now outdated. 

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/ac709ea3-98b7-46a7-bdde-81f856e5608b">
