### ISSUE TITLE
Document SIGTERM/SIGINT behaviour

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1640]
Prisma Client [swallows](https://github.com/prisma/prisma/issues/2917) SIGTERM/SIGINT. We should clearly document this behaviour.

Based on this [user's request](https://prisma.slack.com/archives/C01739JGFCM/p1620095606010100):

![image](https://user-images.githubusercontent.com/4058327/116975378-dcea3680-acbf-11eb-90b6-46f9954b8667.png)

**Comment by janpio** [comment]
This might actually be something to be reconsidered at the Prisma Client side... if we get an issue we can toally look into that magic behavior and make sure it actually achieves the goals we thought it would.
