### ISSUE TITLE
Update CLI show/hide text for all examples

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1641]
## Suggested action

Specify `showText` and `hideText` that is relevant to the example. For instance:

```
<CodeWithResult showText="Show migration SQL" hideText="Hide migration SQL">
```

Default is 'Show CLI', which doesn't always make sense.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
