### ISSUE TITLE
Split relation queries into sub-pages

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1645]
## Suggested action

Relation queries page is quite long - suggest splitting into 'nested reads' and 'nested writes'

**Comment by ankur-arch** [comment]
@nikolasburk @jharrell  I think a long page is fine.

Do you have any arguments why we may want to split it up?

https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries

**Comment by ankur-arch** [comment]
Closing this as unplanned, we can reopen if needed.
