### ISSUE TITLE
List reserved database names (e.g. system db = mysql)

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1647]

**Comment by molebox** [comment]
I fell for this the other day. This would be super handy to have in the docs. BUT, now that i think about it, are we now documenting how to work with databases in general? 

We do mention reserved words [here](https://www.prisma.io/docs/concepts/components/prisma-client/crud/#deleting-all-data-with-raw-sql--truncate). It feels like a potential rabbit hole if we start documenting specific database stuff

**Comment by janpio** [comment]
Context here might be that if you do not supply a database in a MySQL connection URL, it uses `mysql` as the default (similar to `public` schema for Postgres). While `public` is fine to use, you do not want to do stuff with the `mysql` system db as things break.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
