### ISSUE TITLE
Implement Anchor redirect component

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1648]
I would like a way to redirect old anchors on a page (e.g. /relations#one-to-one) to an entirely new page (/relations/one-to-one) - this is only important for significant refactors where you move sections to pages that aren't obvious.

```
<AnchorRedirects>
<Anchor from="the-anchor" to="the-new-page">
</AnchorRedirects>
```

Script: https://raw.githubusercontent.com/fastlane/docs/92dae6e0252d4bb1024efc19a273b976ae21de4c/docs/advanced.md

**Comment by zachtil** [comment]
@janpio it seems like this was resolved? Should we close this one?

**Comment by janpio** [comment]
I don't know. Is there some documentation on how to use it?

**Comment by meletj** [comment]
This can be done by adding the needed redirect in https://github.com/prisma/docs/blob/a114584a9b2800b686eaaa7f388c683e61a350d4/static/_redirects rather than directly on the page. 

Will close as not planned for now until we see a need to have this specifically.
