### ISSUE TITLE
Sort by an aggregate value

### ISSUE THREAD

**Issue by O4epegb** [prisma/web#1652]
[Docs mention](https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#can-i-sort-by-an-aggregate-value-for-example-by-users-post-count) that it is not possible right now to sort by an aggregate value (https://github.com/prisma/prisma/issues/3821), but it seems like it is possible already with this flags enabled: `previewFeatures = ["selectRelationCount", "orderByRelation"]`

Query example:

```js
  const players = await prisma.player.findMany({
    include: {
      _count: {
        select: {
          game: true,
        },
      },
    },
    orderBy: {
      game: {
        count: 'desc',
      },
    },
  });
```

**Comment by mhwelander** [comment]
Good spot - removed the FAQ. The doc is here but did not say 'aggregate value', just 'aggregate'. Updated that too: https://github.com/prisma/docs/blob/main/content/200-concepts/100-components/02-prisma-client/050-filtering-and-sorting.mdx#sort-by-relation-aggregate-value-preview Thanks!
