### ISSUE TITLE
Document how to work with postgres extensions in migrate

### ISSUE THREAD

**Issue by tomhoule** [prisma/web#1654]
The migrations team should draft something for the migrate troubleshooting docs.

Related issues: https://github.com/prisma/prisma/issues/6822

**Comment by mhwelander** [comment]
@tomhoule I've documented this here https://www.prisma.io/docs/concepts/components/prisma-schema/features-without-psl-equivalent#native-database-functions - what do you think?

**Comment by tomhoule** [comment]
It's the right information, perfect. I only wonder if there's a "troubleshooting" kind of page for people who encounter a problem with extensions and the shadow database and don't know where to look.

**Comment by keerlu** [comment]
This is now covered by the new PostgreSQL extensions page and the cross-links in #4063
