### ISSUE TITLE
Concepts / Components / Prisma schema / Data sources: Explain connection string / `url` a bit

### ISSUE THREAD

**Issue by janpio** [prisma/web#1678]
https://www.prisma.io/docs/concepts/components/prisma-schema/data-sources has no explantion of "Connection String" or similar, although that is the most important bit of a data source next to the provider. Linking to the different arugments for the different databases would probably be useful. Should then also link to how to set via ENV var etc.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
