### ISSUE TITLE
Use Anchor redirect component

### ISSUE THREAD

**Issue by janpio** [prisma/web#1680]
When https://github.com/prisma/docs/issues/1648 is implemented, the following redirects could be added:

**Comment by janpio** [comment]
https://www.prisma.io/docs/guides/deployment/deployment#aws-rds-proxy
What used to be there, can now be found at https://www.prisma.io/docs/guides/deployment/deployment-guides/caveats-when-deploying-to-aws-platforms#aws-rds-proxy

**Comment by janpio** [comment]
https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-management#connection-pool
Probably moved to https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool

**Comment by zachtil** [comment]
@janpio We should probably close this one too in relation with #1648 ?

**Comment by janpio** [comment]
The 2 links above do not redirect but are still on the old pages with anchor where the content is not actually present.

**Comment by nilubava** [comment]
@janpio Adding it to the `redirects` array in `config.ts` will work. Just like shown in the PR

**Comment by janpio** [comment]
Yes, but I assume #1648 was suggested as an alternative for a reason? (One _might_ be that the redirect should actually live where the content (used to) live. )

**Comment by nilubava** [comment]
@janpio Okay, so to confirm - It would be a **hidden** component just to make sure we have redirects in the same place as the original link used to be, right?

**Comment by janpio** [comment]
That is how I understand https://github.com/prisma/docs/issues/1648, yes. 
This issue here is just about using that component to make sure certain redirects are then implemented via that mechanism.

If what you mentioned above has the same effect and already works, this issue her can probably be closed.

**Comment by nilubava** [comment]
@meletj to see if this is relevant

**Comment by meletj** [comment]
@nilubava looks good to me. Jan needs to review this PR https://github.com/prisma/docs/pull/4936 

Please also document how to use the redirect component from anchor to full page.

**Comment by janpio** [comment]
I don't think this works, you can only point to anchors, but not react to certain anchors: https://prisma-company.slack.com/archives/C06F2DJ49K6/p1713980036600259?thread_ts=1713979210.690349&cid=C06F2DJ49K6

**Comment by meletj** [comment]
Maybe I misunderstood this issue. It sounds different than the request on Slack, which is about defining custom anchors. I'll leave this one as closed as Jon will have a new one up that matches the latest conversation. Hope that's ok.

**Comment by janpio** [comment]
Yep, ignore me. I didn't actually read the full issue, just the title - which was bad. I think the ones here are properly covered.
