### ISSUE TITLE
Migration from sequelize to Prisma does not tell anything about migrations & seeds

### ISSUE THREAD

**Issue by villesau** [prisma/web#1692]
I think the migration guide from Sequelize to Prisma is one of the best i've seen: https://prisma.io/docs/guides/migrate-to-prisma/migrate-from-sequelize

However it does not cover one of the key aspects: Migrations & seeds. How do you migrate Sequelize migrations and seeds from Sequelize to Prisma? What strategies are used?

**Comment by ruheni** [comment]
👋

Prisma has a different seed workflow compared to Sequelize. From Sequelize's docs, one can seed and un-seed a database on every migration. Prisma currently supports having a single seed file — more details on Prisma seed on [this page in the docs](https://www.prisma.io/docs/guides/migrate/seed-database)

For the queries in the seed file, you can replace your Sequelize queries with Prisma Client queries.
