### ISSUE TITLE
Document thenable nature of Prisma Client queries

### ISSUE THREAD

**Issue by janpio** [prisma/web#1695]
https://github.com/prisma/prisma/discussions/7033 + https://prisma-company.slack.com/archives/CUXLS0Z6K/p1620760435005700

**Comment by mhwelander** [comment]
Related, I think: #800

**Comment by mhwelander** [comment]
https://prisma-company.slack.com/archives/CUXLS0Z6K/p1622119096024300

**Comment by janpio** [comment]
Additional context how this is _not_ the case for `$connect()` and `$disconnect()`: https://prisma-company.slack.com/archives/C016KUHB1R6/p1623999600168300

**Comment by Jolg42** [comment]
@molebox In the PR it could be misunderstood that all client methods are thenable but actually it's all except `$connect()` and `$disconnect()`

**Comment by Jolg42** [comment]
Actually there are also `$on()` and `$use()` that don't fit the thenable description.

Better to say maybe:
The following methods are thenable (...)
- All model queries like `.create()`. `.update()` ....
- $executeRaw()
- $queryRaw()
- $transaction()

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
