### ISSUE TITLE
Add a note that relations will only be picked if foreign keys are set

### ISSUE THREAD

**Issue by pantharshit00** [prisma/web#1702]
Re: https://github.com/prisma/prisma/issues/6827

In this page: https://www.prisma.io/docs/concepts/components/introspection#introspection-with-an-existing-schema we should add a note that relations between model will only be picked if a foreign key exists between the tables on a database level.

**Comment by janpio** [comment]
Technically the relation only exists when there is a foreign key... but seems we definitely should make this explicit.
