### ISSUE TITLE
Special characters used in bullet lists not rendered correctly

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1705]
Sometimes special characters used in bullets don't seem to be rendered correctly, e.g. [here](https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#serverless-environments-faas):

![image](https://user-images.githubusercontent.com/4058327/118467648-4462a600-b704-11eb-97ad-919b931c3d34.png)

I have the same issue in the [raw source](https://raw.githubusercontent.com/prisma/docs/main/content/300-guides/100-performance-and-optimization/150-connection-management/index.mdx) on GitHub:

![image](https://user-images.githubusercontent.com/4058327/118467843-75db7180-b704-11eb-9109-fa800c63e439.png)

**Comment by janpio** [comment]
These are actually the characters in the source of the file - so it is rendering exactly what it sees.
Maybe these should look like checkboxes and are actually intended this way?

**Comment by mhwelander** [comment]
🙈 They are supposed to be checkboxes, yes.

**Comment by janpio** [comment]
I think I did not get that becuase the normal list bullet is still there - without that I might have gotten it.

**Comment by nikolasburk** [comment]
fixed this a while ago
