### ISSUE TITLE
Document that the view workaround does not work with introspection/migrate

### ISSUE THREAD

**Issue by tomhoule** [prisma/web#1708]
The [SQL views workaround in the docs](https://www.prisma.io/docs/guides/database/advanced-database-tasks/sql-views-mysql) is causing confusion, [as reported by users](https://github.com/prisma/prisma/issues/6015).

I think we should add the following to limitations:

- Models created for views using this workaround will be "deleted" from your schema the next time you introspect, because they do not correspond to tables in the database.
- Migrate will treat these views as tables and try to create them, leading to crashes. If you have view models, you cannot use migrate with them.

**Comment by tomhoule** [comment]
I added candidate labels to get some attention, feel free to remove them if it doesn't fit the docs team's process :)

**Comment by tomhoule** [comment]
Also note I'm available if this needs more details.

**Comment by janpio** [comment]
We should make it much clearer that this is a _workaround_ for missing functionality in Prisma, and that https://github.com/prisma/prisma/issues/678 is the issue to follow and subscribe for the real implementation. Right now one could get the impression this is really how Prisma and Views work - but in reality it is a pretty ugly hack that makes it work in some way.
