### ISSUE TITLE
Improve elastic beanstalk docs

### ISSUE THREAD

**Issue by pantharshit00** [prisma/web#1709]
Re: https://github.com/prisma/prisma/issues/6216#issuecomment-841840515

> The key to the issue is that by default an Elastic Beanstalk installs dependencies with npm install --production, which does not install devDependencies.

> The @prisma/client postinstall.js script (which generates the client) requires the Prisma CLI to be installed either locally or globally.

This comment mainly needs to be documented: https://github.com/prisma/prisma/issues/6216#issuecomment-818729723 in this section: https://www.prisma.io/docs/guides/deployment/deployment-guides/caveats-when-deploying-to-aws-platforms#aws-elastic-beanstalk

**Comment by janpio** [comment]
Can you suggest a wording for the documentation?
