### ISSUE TITLE
Document reasoning behind not supporting dynamic datasource providers

### ISSUE THREAD

**Issue by janpio** [prisma/web#1716]
Sometimes people want to develop with SQLite, then deploy with Postgres. We used to support this with dynamic `provider` properties in the schema (which could even be set via an env var), but that had all kinds of problem. Especially Migrate that generates migrations in one specific SQL variant could not work that way.

We should write that down in one location we can refer to.

Previously:
https://github.com/prisma/prisma/issues/3834
https://www.notion.so/prismaio/Multi-data-source-strategy-f85e8ae9d5004bdaa0d884c211105d25

Triggered by internal discussion: https://prisma-company.slack.com/archives/CGMCB82N8/p1621326114004700

**Comment by mhwelander** [comment]
We link to the GH issue in the docs - is that enough @janpio? https://www.prisma.io/docs/concepts/components/prisma-schema/data-sources

**Comment by janpio** [comment]
If you think that is good enough 🤷 No objections.

**Comment by janpio** [comment]
Actually I think fishing out the real reason of that and putting it as an explanation why we need a static value there might be nice.

**Comment by vintprox** [comment]
It could use some more clarification. Because what I see now is a simple redirect to a closed issue. Two points should be made clear:
- the scope of deprecation,
- what are alternative ways to achieve datasource interchangeability.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
