### ISSUE TITLE
prisma db seed --preview-feature fails with JSON error on nextjs app

### ISSUE THREAD

**Issue by topheroes** [prisma/web#1725]
Hello,

I have the following scripts in package.json:
```
 "ts-node": "ts-node --compiler-options '{\"module\":\"CommonJS\"}'",
    "seed": "prisma db seed --preview-feature"
```
When running npm run seed I get the following error:

`SyntaxError: Unexpected token ' in JSON at position 0`

The versions are:
Window 10, 19042.928, Node 14.16.1

Here is the repo which reproduces the problem:
[https://github.com/topheroes/prisma-bug-reproduce](https://github.com/topheroes/prisma-bug-reproduce)

Please advice,
Thank you!

**Comment by molebox** [comment]
Are we suggesting to change the doc from
this:
`"ts-node": "ts-node --compiler-options '{\"module\":\"CommonJS\"}'"`
to this:
`"ts-node": "ts-node --compiler-options {\\\"module\\\":\\\"commonjs\\\"}",` ?

**Comment by janpio** [comment]
Not sure if this works on Linux and MacOS or has other side effects. But what we document should usually work on all operating system (as it otherwise causes issues like this one).
