### ISSUE TITLE
Inconsistent SQL pronunciation

### ISSUE THREAD

**Issue by imchairmanm** [prisma/web#173]
Currently, when writing SQL alone or as a component of other words (for example "SQLite"), there is some inconsistency in the way that "SQL" is assumed to be pronounced

* Sometimes, it is proceeded by an "a", indicating a "sequel" pronunciation ("a SQL database")
* Other times it is proceeded by an "an", indicating an "S-Q-L" pronunciation ("an SQL database")

As far as which is correct, there's no real consensus.  Apparently "SQL" was originally intended to be SEQUEL, but was changed due to copyright issues.  This ISO doc seems to use the S-Q-L pronunciation: https://www.iso.org/standard/53681.html

As far as SQLite specifically, the author also seems to have intended the S-Q-L pronunciation: http://sqlite.1065341.n5.nabble.com/SQLite-Pronunciation-tp88186p88194.html

In general, no one seems to really mind either pronunciation, so rather than this being an issue with correctness, it's just one of consistency  For "SQLite", I suggest we follow the author's original intention since we don't have a clear reason not to.  For standalone "SQL", let's just pick one and use it consistently.

**Comment by mhwelander** [comment]
Changed to 'a'.
