### ISSUE TITLE
Prisma Generate Docs Possible Typo

### ISSUE THREAD

**Issue by GargantulaKon** [prisma/web#1744]
I think there might be a typo on https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client.

> Note also that prisma generate is automatically invoked when you're installing the @prisma/client npm package. So, when you're initially setting up Prisma Client, you can typically save the third step from the list above.

It should say the fourth step since that's where the generate command is run.

**Comment by jboxman** [comment]
@GargantulaKon it looks like the note block is breaking the numbering:

>We recommend that you keep both the prisma and @prisma/client packages in sync to avoid any unexpected errors or behaviors.

It goes 1,2,3,1,2 but probably should be 1-5.
