### ISSUE TITLE
Shadow database 'resolve error' list update

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1748]
## Context

https://prisma-company.slack.com/archives/C5Z9TH6N9/p1621929601052600

**Comment by nikolasburk** [comment]
- validate the info [here](https://www.prisma.io/docs/concepts/components/prisma-migrate/shadow-database#shadow-database-user-permissions):
<img width="605" alt="image" src="https://user-images.githubusercontent.com/4058327/231215347-86348a6d-c30b-45b2-abdd-aac951b3d5cc.png">
- expand list of DB providers with Supabase and Digital Ocean

**Comment by janpio** [comment]
(Supabase does not require manual handling of shadow databases any more, it should just work)

**Comment by ruheni** [comment]
The information on the page is up to date. I've created a PR to make a few minor adjust wording and expand the example hosted DB providers
