### ISSUE TITLE
Replace "updatedAt" with "createdAt" in diagram of "Data model" page

### ISSUE THREAD

**Issue by chaficnajjar** [prisma/web#1753]
The diagram in the [Data model](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model) page shows a "Post" table with an "updatedAt" field but the schema above that diagram shows that the "Post" table has a "createdAt" field.

Screenshot of the diagram:

![screenshot](https://user-images.githubusercontent.com/1498164/119771325-319b5e80-bec6-11eb-8863-5a72943f0f64.png)

Screenshot of the schema:

![screenshot](https://user-images.githubusercontent.com/1498164/119771297-234d4280-bec6-11eb-8c34-d745e7cbf40a.png)

The diagram should be updated to show the "Post" table having a "createdAt" field instead of an "updatedAt" field. Alternatively, the schema can be updated such that the "Post" table has an "updatedAt" field instead of a "createdAt" field.

**Comment by nikolasburk** [comment]
two todos to make the example right:
- [x] add `updatedAt` to the data model in code
- [x] add `createdAt` to the schema
