### ISSUE TITLE
Where I get more details about filter of type?

### ISSUE THREAD

**Issue by adrianoresende** [prisma/web#178]
In https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/crud#findmany 
I don't found about how this filter work, what is difference between`every` and `some`?

![image](https://user-images.githubusercontent.com/798755/79028887-4c96fc00-7b68-11ea-9433-32c9ad3aef21.png)

**Comment by mhwelander** [comment]
Now documented (every, some, none): https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/filtering#filter-on-related-records
