### ISSUE TITLE
Order of execution of multiple nested queries

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1782]
## Context

https://github.com/prisma/prisma/discussions/7388

## Suggested action

Document what the order of execution is for multiple nested queries. In this code snippet, `deleteMany` is always executed before `updateMany`:

```ts
await prismaClient.user.update({
  where: {
    id: userId,
  },
  data: {
    userRecords: {
      deleteMany: { /* delete all */  },
     /* or */ 
     // updateMany: { where: {}, data: { isActive: false }  } 
      create: {
           content: 'the only or the only active record',
           isActive: true,
      },
   },
 },
});
```

> As per the latest ECMAScript standard, object keys are run in the order of what you specify, so in the above example `deleteMany` will run before `create`. 
> From linked issue

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
