### ISSUE TITLE
The database feature matrix does not include introspection/migrate support

### ISSUE THREAD

**Issue by tomhoule** [prisma/web#1783]
The [database features](https://www.prisma.io/docs/reference/database-reference/database-features) page lists database features and whether they are supported in client, but what Client support entails is not clear. For example, table inheritance might technically work with Client, but there is no introspection or migration support for it, so users would have to get the schema right by hand (same for database views). This can be confusing for users; see for example https://github.com/prisma/prisma/issues/6808

I think that the best short term fix would be to mark table inheritance as not supported.

**Comment by janpio** [comment]
I think was supposed to be covered by the "Prisma Schema" column?

**Comment by meotimdihia** [comment]
Prisma client doesn't work with inheriting table if we use Prisma migration.

**Comment by rohanrajpal** [comment]
Has anyone figured out how to use Table inheritance with prisma & postgres btw?

**Comment by janpio** [comment]
That is not supported yet in Prisma. See the issues here: https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+inheritance%22+sort%3Aupdated-desc

**Comment by rohanrajpal** [comment]
My bad, i saw the tick next to inheritance and thought documentation was the only issue. Just realized its not supported. Let me see if I can contribute to these issues in any way.
