### ISSUE TITLE
Debugging instructions unclear

### ISSUE THREAD

**Issue by janpio** [prisma/web#1837]
https://www.prisma.io/docs/concepts/components/prisma-client/debugging#overview does not mention where to run the actual commands and how you can check if it works. This is a new concept to many users and should be explained.

Example: https://github.com/prisma/prisma/issues/7476#issuecomment-855238208

**Comment by ruheni** [comment]
Related: https://github.com/prisma/docs/issues/1857

Existing work in progress: https://github.com/prisma/docs/pull/4657

**Comment by ankur-arch** [comment]
We do state you can execute them in bash. 
<img width="444" alt="image" src="https://github.com/user-attachments/assets/b60d91be-eae3-408a-adf6-c506933e7fc0">
