### ISSUE TITLE
Consider adding logging info to "Debugging" page

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1857]
The [Debugging](https://www.prisma.io/docs/concepts/components/prisma-client/debugging) page currently only covers the `DEBUG` env var.

I think it should at least also mention the possibility of using `log: ['error']` when instantiating `PrismaClient` that's explained [here](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging) so that people don't have to look through different pages to get all potential debugging info that's relevant for them.

**Comment by janpio** [comment]
I often have to refer to these two pages to get what I need (as I always forget again 5 minutes later), so at least cross linking them explicitly make so much sense.

**Comment by ruheni** [comment]
TODO:
- [ ] Add a new section that shows the logging option
- [ ] Link to the logging page
