### ISSUE TITLE
Improve case sensitivity section for SQLite provider

### ISSUE THREAD

**Issue by m-abdelwahab** [prisma/web#1858]
![image](https://user-images.githubusercontent.com/27310414/121334792-47733f80-c91a-11eb-8ac7-60a18a1fd9bf.png)

This [section](https://www.prisma.io/docs/concepts/components/prisma-client/case-sensitivity#sqlite-provider)'s wording is a bit confusing on whether or not SQLite supports case-insensitive filtering or not.
It should be clear that the default filtering mode is case-sensitive and that SQLite supports case insensitive only if your data is pure ASCII characters.

It's also not clear how I would actually use this workaround:

```SQL
CREATE TABLE mytable (
    sample TEXT COLLATE NOCASE   /* collating sequence NOCASE */
);
```

So might be a good idea to include a resource that clarifies where to include this snippet

**Comment by CanRau** [comment]
Found this as I have no idea how to use `COLLATE NOCASE`

As I'm needing this only for the name field for now I think I store a separate `nameLower` or something which always holds the username in lowercase for searching purposes.
