### ISSUE TITLE
Prisma + Supabase

### ISSUE THREAD

**Issue by janpio** [prisma/web#1864]
Using a Supabase database with Prisma has a few things that do not work or only work in a specific ways, but also things one just might benefit from knowing. We should have a guide for that.

- One example: https://github.com/prisma/prisma/issues/7489#issuecomment-857266071
- Another example: conneciton pooled connection string for Client, the non pooled one for Migrations and Introspection
- Non support of multi schema queries, or using `SET` for the Supabase row based auth thing

**Comment by ruheni** [comment]
Closed via https://github.com/prisma/docs/pull/4740
