### ISSUE TITLE
Document community middleware (similar to community generators)

### ISSUE THREAD

**Issue by janpio** [prisma/web#1868]
First example: https://www.npmjs.com/package/prisma-lrucache-middleware

**Comment by ankur-arch** [comment]
I'm closing this issue as [Middleware's](https://www.prisma.io/docs/orm/prisma-client/client-extensions/middleware) have been deprecated in favour of [Prisma Client extensions](https://www.prisma.io/docs/orm/prisma-client/client-extensions).
