### ISSUE TITLE
Constraint names

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1869]
Required steps:

- [ ] Replace 2.XX.0 (search and replace) with whatever the version is when this is released

**Comment by molebox** [comment]
Is this related to https://github.com/prisma/docs/issues/1842 ?

**Comment by janpio** [comment]
Yes.

**Comment by mhwelander** [comment]
@janpio Assigning this to you as I'm not sure Rich will be back in time for whenever this feature becomes available.
