### ISSUE TITLE
Document why Prisma Migrate does not support down migrations and rollbacks

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/web#1873]
We currently have this, which feels quite scarce: https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-limitations-issues#lack-of-rollbacks--down-migrations

Trying to collet a list of the explanations we've made so far:

https://news.ycombinator.com/item?id=26890202

![image (13)](https://user-images.githubusercontent.com/24216/121688357-42012b00-cabb-11eb-9073-cc3aebcf4fad.png)

**Comment by tomhoule** [comment]
Relevant: explanation by Hervé https://github.com/prisma/prisma/issues/4531#issuecomment-746793577

Also if I remember correctly, I expanded in two comments in the above HN thread. Also, it was a quick comment written on the side during a zoom call so it's not great writing.

**Comment by keerlu** [comment]
I think this can be closed now? More docs mentions would still be good, but we now have:
- [Generating down migrations](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/generating-down-migrations)
- [Fixing failed migrations](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/generating-down-migrations)
