### ISSUE TITLE
Smart tabs: Default to the relevant tab for operating system tabs

### ISSUE THREAD

**Issue by janpio** [prisma/web#1875]
- On Windows the Windows tab should be chosen as default
- On Linux and Mac the respective one

Otherwise tabs kinda highlight one specific platform solution, which is not good if the user is on the other platform.

**Comment by mhwelander** [comment]
Looks like a `website` feature to me, changing tag

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
