### ISSUE TITLE
Link to Introspection broken

### ISSUE THREAD

**Issue by luisejrobles** [prisma/web#188]
Navigating through 
https://www.prisma.io/docs/understand-prisma/introduction
At the *Getting a data model* section when you click **introspecting** it's broken since it sends you to:
https://www.prisma.io/reference/tools-and-interfaces/introspection
instead of:
https://www.prisma.io/docs/reference/tools-and-interfaces/introspection

![image](https://user-images.githubusercontent.com/3373127/79081829-78d88700-7ce6-11ea-9df2-6161a763587f.png)

**Comment by mhwelander** [comment]
Pardon delay in closing issue - this is now fixed 💚
