### ISSUE TITLE
Explain what "arity" means in the context of data modeling and migrations

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1883]
When detecting drifts, `prisma migrate` uses the term "arity", e.g.:

```
[*] Altered column `isGoodDog` (arity changed from Nullable to Required, default changed from `None` to `Some(Value(Boolean(true)))`)
```

We shouldn't expect users to understand what arity is and (assumed we keep this terminology in the migrate output), should explain it in our docs.

**Comment by molebox** [comment]
The migrations team are removing this terminology, we can close this issue
