### ISSUE TITLE
PostgreSQL extensions are not added when you introspect

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1885]
Context: https://twitter.com/sachr_/status/1400912049362722820

If you are using `some()` function from `some` extension, it is not added when you introspect. However, you can represent unsupported functions in the schema with `dbgenerated()` and by manually adding to migration files: https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/enable-native-database-functions/

## Suggested action

On introspection page, state that unsupported functions aren't added to the schema when you introspect. If [you are introspecting to create your first migration](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/add-prisma-migrate-to-a-project#introspect-to-create-or-update-your-prisma-schema), you might need to manually update your schema to include your db-level functions if you want to see them in the schema. Suggest checking this with Migrations team: If I'm adding Migrate to an existing project, and I introspect to create my schema, should I then manually add in any `dbgenerated(myfunction())` things that I know I have defined in my DB for visibility?

**Comment by keerlu** [comment]
This is now covered by the new PostgreSQL extensions page and the cross-links in #4063
