### ISSUE TITLE
Links to Prisma migrate broken

### ISSUE THREAD

**Issue by luisejrobles** [prisma/web#189]
Navigating through
https://www.prisma.io/docs/understand-prisma/introduction
At the *Getting a data model* section when you click *Prisma Migrate* it's broken since it sends you to:
https://www.prisma.io/reference/tools-and-interfaces/prisma-migrate
instead of:
https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-migrate

![image](https://user-images.githubusercontent.com/3373127/79081877-e2589580-7ce6-11ea-9e83-0f1e50f251aa.png)

**Comment by AryanJ-NYC** [comment]
This is fixed and this issue can now be closed. Link for the lazy: https://www.prisma.io/docs/understand-prisma/introduction#getting-a-data-model
