### ISSUE TITLE
Need to add `await prisma.$disconnect()` when seeding

### ISSUE THREAD

**Issue by m-abdelwahab** [prisma/web#1921]
In this [section](https://www.prisma.io/docs/guides/database/seed-database#requirements-for-seeding-with-typescript-or-javascript), we need to add `await prisma.$disconnect()` to the seeding function. Otherwise, the process won't terminate and users would need to `ctrl+c` after running the seed script, which is not optimal.

![image](https://user-images.githubusercontent.com/27310414/123139495-8fd04880-d456-11eb-91ba-00e6a0a79a4d.png)

Suggested changes:

## An export named seed

```ts
export async function seed() {
  // Prisma create query to seed models in database
  await prisma.$disconnect()
}
```

```js
async function seed() {
  // Prisma create query to seed models in database
  await prisma.$disconnect()
}

module.exports = {
  seed
}

```

## A default export

```ts
async function seed()  {
  // Prisma create query to seed models in database
  await prisma.$disconnect()
}

export default seed
```

```js
async function seed()  {
  // Prisma create query to seed models in database
  await prisma.$disconnect()
}

module.exports = seed

```

**Comment by janpio** [comment]
That will be a _very_ common failure mode then, as you usually do not have to do that when you have a Prisma script, right? Should this be something that is tackled in the actual feature, so probably as feedback in https://github.com/prisma/prisma/issues/5161

**Comment by ruheni** [comment]
Updated ✅
