### ISSUE TITLE
A section on updating foreign keys directly (`uncheckedInputs`)

### ISSUE THREAD

**Issue by ryands17** [prisma/web#1925]
As per this Slack convo, we should have a section on when to use `connect` and when to set the foreign key directly. Also that section should include a note where using both `connect` and directly adding the foreign key is not possible.

https://prisma.slack.com/archives/CA491RJH0/p1624483349077900
![image](https://user-images.githubusercontent.com/19697099/123205084-e3827680-d4d6-11eb-8f7c-b4114fb8368f.png)

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
