### ISSUE TITLE
ONGOING: Example schemas and queries

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1927]
The **Example schemas and queries** is a directory of schemas that go beyond the basic `User` and `Post` models used for simple examples, and the kinds of queries the schema supports. Add your example and create a pull request! 🚀 For example, you might design a schema and queries for:

* A hotel room booking system
* A ticket booking system that supports reserving a ticket for 10 minutes
* An ecommerce website

## Where should I add my page?

Add your contributions under [Guides > Samples](https://github.com/prisma/docs/tree/main/content/300-guides/010-schema-query-examples) as a separate page. 

![image](https://user-images.githubusercontent.com/849648/123228117-8803b900-d4d5-11eb-906a-d3a2e437eb9d.png)

## What format should I use?

Use the following basic template as a starting point:

````
Introduction here

## Scenario

This schema models followers/following - a many-to-many relationship.

## Schema

```prisma
Your schema here
```

## Example queries

Example queries here - the more advanced and peculiar the better.

````

**Comment by ruheni** [comment]
This is out of the scope of the current docs. 

However, if anyone would be interested in example schemas, we have this ongoing project by a community member: https://grab-and-go-prisma-schemas.vercel.app/
