### ISSUE TITLE
Using Prisma with Google Cloud SQL

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1938]
## Context

https://prisma-company.slack.com/archives/C5Z9TH6N9/p1624464292357500

## Suggested action

As discussed in the thread, let's add this page to the Deployment > Deployment guides section. It does not need to be a fully fledged tutorial.

Also add a new section here named **Database providers**: https://www.prisma.io/docs/guides/deployment/deployment-guides

**Comment by Sytten** [comment]
Happy to help on that if you need, it is my primary stack

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
