### ISSUE TITLE
Development environment section in guides

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1939]
## Context

https://prisma-company.slack.com/archives/C5Z9TH6N9/p1624520976365200?thread_ts=1624464292.357500&cid=C5Z9TH6N9

## Suggested action

A new section under Guides named "Development environment" that includes:

~~* Env vars (currently under 'More')~~
* Workspaces #1910 
~~* Editor setup (currently under 'More')~~

**Comment by molebox** [comment]
Linking https://github.com/prisma/docs/issues/1887
