### ISSUE TITLE
Document scalar arrays

### ISSUE THREAD

**Issue by steebchen** [prisma/web#194]
We support scalar arrays with Postgres. That means the user can write the following:

```
model User {
  id @id
  names String[]
}
```

However, this is only support by some databases such as Postgres and not MySQL/SQLite. It would be great if we could add "scalar arrays" in a separate section under "Reference"->"Prisma Schema" of how it works, and also noting for what databases this works.

**Comment by mhwelander** [comment]
Documented here: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/models#lists
