### ISSUE TITLE
Using multiple PrismaClient instances

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1940]
## Context

https://prisma-company.slack.com/archives/C5Z9TH6N9/p1624863600370600 (@janpio will provide a use case)

## Suggested action

* A new page under this section named 'Using multiple instances of PrismaClient' or similar: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient (nav title can be 'Multiple instances'
* In every location where we mention using one instance, link to this page with a short explanation of when you might use more than one

**Comment by nikolasburk** [comment]
Another data point that this would be useful: https://github.com/prisma/prisma/discussions/17855#discussioncomment-4952250

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
