### ISSUE TITLE
Change the recommended workflow for dealing with failed migrations

### ISSUE THREAD

**Issue by tomhoule** [prisma/web#1978]
In https://www.prisma.io/docs/guides/database/production-troubleshooting#option-1-mark-the-migration-as-rolled-back-and-re-deploy — when we recommend an order for rolling back migrations, marking the migration as rolled back before rolling it back is a bit dangerous, since you tell migrate (with `resolve --rolled-back`) you fixed the state of the database before actually doing it. The steps should be the following:

1. Figure out where the error came from (from `migrate status`, the `logs` column, etc.).
2. Fix the root cause in the migration script if applicable
3. Revert what the migration did, so the schema is in the same state it was before the migration was run. If you are on postgres or SQL server and you run your migrations inside transactions (by adding `BEGIN;` and `COMMIT;`, then the database already automatically did that for you.
4. Mark the migration rolled back with `migrate resolve --rolled-back <migration-name>`
5. `migrate deploy`

It's not necessary to spend a ton of time on this since I hope we'll have a different, better workflow soon.

I'm here for any questions if any more details or a review is needed :) Thanks!

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
