### ISSUE TITLE
`smooth-scroll` makes clicking a link on the ToC and navigating there super slow

### ISSUE THREAD

**Issue by Sparragus** [prisma/web#1996]
Hey hey! Thanks for the great work. :)

I've noticed a recent change in hash anchor links. If you click it, it ~smoothly~ slowly moves to that part of the page. If the section is far from the current scroll position, the transition is very slow.

I believe this was introduced in https://github.com/prisma/docs/commit/9f8d8d0ba79c28263cae7ce49d324d5aca466923#diff-0b75a532e530ce749a966d77dffeea3593e67560e5894213143637ee1d84aef5R119

To reproduce it, go to https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference and click on `enum` in the ToC on the right side.

I've only tested this on a laptop-sized screen.

Here's a demo: https://www.loom.com/share/22946890eaaa4f7fb392d351e2e92247

**Comment by Sparragus** [comment]
Some ideas:
- Remove the smooth-scrolling effect
- Adjust the speed settings: https://github.com/cferdinandi/smooth-scroll#scroll-speed

I'm inclined to remove it, but first I'd like to discuss it with the community before sending a PR.

**Comment by janpio** [comment]
Haha, on the schema reference this is comically slow indeed. 

I think for now just removing it is a viable solution, and then we can figure out what we want to do long term with it. So go ahead and create that PR 👍 

cc @molebox @nilubava

**Comment by Sparragus** [comment]
> I think for now just removing it is a viable solution, and then we can figure out what we want to do long term with it. So go ahead and create that PR 👍

Here's the PR: https://github.com/prisma/docs/pull/1997

:)

**Comment by molebox** [comment]
😅 OH dear. I'll fix it tomorrow morning unless you feel like making that PR. Either way, thanks for raising this!
