### ISSUE TITLE
Do not rebuild full Algolia index all the time

### ISSUE THREAD

**Issue by janpio** [prisma/web#2014]
From a support request to Algolia:

me:
> our list of "Top results" only contains "Missing or deleted record" and IDs with a count, but no information about _what_ the results are. Is this normal? How can we change it to be more useful?
>
> https://www.algolia.com/apps/MK4LNFW4EO/analytics/results/prisma2-docs?from=2021-06-30&to=2021-07-06
> ![image](https://user-images.githubusercontent.com/183673/125131248-b357ec00-e102-11eb-9711-9db2c3f30b61.png)

reply:
> This list of search results matches onto a objectId of a record which matches the search query. Looking at you main product index, I can see that it appears to be being rebuilt on a regular basis.
>
> Have you cleared out your index and rebuilt it as part of one of these build operations?
>
> The objectIds that are listed no longer appear to be in your index, which is why this message is being shown. If you clear out your index and don't retain the objectId which is tied to a record then all your analytics data will be invalid as the searches are linked to a record. If you are completely rebuilding your index you will need to be able to maintain the objectId as it is in Algolia in order to be able to maintain this analytics data.

So it would be great if we could find a way not to do that, and gain information about our most popular results.

**Comment by janpio** [comment]
Possibly: https://github.com/algolia/gatsby-plugin-algolia#partial-updates

**Comment by ankur-arch** [comment]
Closing as this is outdated.
