### ISSUE TITLE
Track clicks on search results

### ISSUE THREAD

**Issue by janpio** [prisma/web#2015]
From a support request to Algolia:

> I am trying to understand why I only see "There is no data yet" in our Analytics dashboard: https://www.algolia.com/apps/MK4LNFW4EO/analytics/overview/prisma2-docs?from=2021-06-30&to=2021-07-06

reply:

> Looking at your site, I can see that you have the Algolia search within the docs area of the site. However, it doesn't look like you are tracking any click events on these searches.
> 
> In order to collect the click position you need to tell Algolia that you want to track click events.
> 
> Some useful guides to setting this up can be found within our documentation:
> 
> https://www.algolia.com/doc/guides/getting-insights-and-analytics/search-analytics/click-and-conversion-analytics/
> 
> In addition to this, here is how you can track your click and conversion events.
> 
> Check from the source:
> 
> The first step is to use the Insights Validator plugin: https://www.algolia.com/doc/guides/getting-insights-and-analytics/search-analytics/click-through-and-conversions/in-depth/insights-validator-plugin/
> 
> This plugin tracks the click and conversion events in your developer tools, I recommend first checking it with a application with working click and conversion analytics like this one:https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/InstantSearch.js/algolia-insights
> 
> and checking that your own application is recording click and conversion events in the same way:
> 
> ![image](https://user-images.githubusercontent.com/183673/125131483-1f3a5480-e103-11eb-8c00-918a06dcc633.png)
> 
> Once you see events coming through ok, the next place to check is your insights events logs on your dashboard: https://www.algolia.com/monitoring/insights
> 
> ![image](https://user-images.githubusercontent.com/183673/125131457-15185600-e103-11eb-92b3-0a0192a4e680.png)

Tracking the clicks would allow us to understand the click position of the results.

**Comment by ankur-arch** [comment]
Closing this as it's outdated.
