### ISSUE TITLE
Following the docs for "prisma client instantiation" is producing an error with the recent update of `@types/node` (v16). With the previous version (v15) it was working fine

### ISSUE THREAD

**Issue by jakegiri** [prisma/web#2018]
I'm getting this error

```
error TS2694: Namespace 'NodeJS' has no exported member 'Global'.
4 interface CustomNodeJsGlobal extends NodeJS.Global 
```
While running this (as docs suggested https://www.prisma.io/docs/guides/performance-and-optimization/connection-management/#prismaclient-in-long-running-applications)

```
import { PrismaClient } from "@prisma/client";

// add prisma to the NodeJS global type
interface CustomNodeJsGlobal extends NodeJS.Global {
  prisma: PrismaClient;
}

// Prevent multiple instances of Prisma Client in development
declare const global: CustomNodeJsGlobal;

const prisma = global.prisma || new PrismaClient();

if (process.env.NODE_ENV === "development") global.prisma = prisma;

export default prisma;
```
**IT'S THE PROBLEM WITH @types/node VERSION.**
--> With "@types/node": "^15.4.0" (i don't remember precisely but it started from 15 (15.x.x))
--> The error is shown after updating to the latest version "@types/node": "^16.3.0"

**What is the standard way to make it work with the latest version "@types/node": "^16.3.0", ?**

I got it working with the accepted answer after i posted in stackoverflow https://stackoverflow.com/questions/68322578/recent-updated-version-of-types-node-is-creating-an-error-the-previous-versi

**Comment by matthieu-locussol** [comment]
I encountered the same problem, I fixed it this way:
```typescript
import { PrismaClient } from '@prisma/client';

type CustomGlobal = typeof globalThis & {
   prisma?: PrismaClient;
};

declare const global: CustomGlobal;

const prisma = global.prisma || new PrismaClient();

if (process.env.NODE_ENV === 'development') {
   global.prisma = prisma;
}

export default prisma;
```

**Comment by jakegiri** [comment]
@matthieu-locussol Yeah that make sense. Though i found another way (seems more elegant to me)
For more details beind the issue and why this solution works check here https://stackoverflow.com/questions/68322578/recent-updated-version-of-types-node-is-creating-an-error-the-previous-versi

```
import { PrismaClient } from "@prisma/client";

declare global {
  var prisma: PrismaClient;
}

const prisma = global.prisma || new PrismaClient();

if (process.env.NODE_ENV === "development") global.prisma = prisma;

export default prisma;
```

**Comment by jakegiri** [comment]
@matthieu-locussol Yeah that make sense. Though i found another way (seems more elegant to me)
For more details beind the issue and why this solution works check here https://stackoverflow.com/questions/68322578/recent-updated-version-of-types-node-is-creating-an-error-the-previous-versi

```
import { PrismaClient } from "@prisma/client";

declare global {
  var prisma: PrismaClient;
}

const prisma = global.prisma || new PrismaClient();

if (process.env.NODE_ENV === "development") global.prisma = prisma;

export default prisma;
```

**Comment by ruheni** [comment]
This is now documented here: https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#prevent-hot-reloading-from-creating-new-instances-of-prismaclient
