### ISSUE TITLE
Add back the scalar to client language mapping

### ISSUE THREAD

**Issue by Sytten** [prisma/web#2022]
I am writing a very extensive prisma training guide for a client and I remember that doc had a mapping of scalars to JS/TS types at some point. I cannot find it anymore and I think it would be valuable to add it back.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
