### ISSUE TITLE
Meta tags not picked up on Twitter

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#203]
Meta tags (title, description, image) don't seem to be picked up on Twitter, see this tweet: https://twitter.com/nikolasburk/status/1249797446458368003?s=12

More context in this [internal Slack conversation](https://prisma-company.slack.com/archives/C5Z9TH6N9/p1586813020007900).

**Comment by janpio** [comment]
https://metatags.io/ picks up the description only, which Twitter surprisingly also does not show.
