### ISSUE TITLE
Mention prisma.$disconnect in export seed function documentation

### ISSUE THREAD

**Issue by yue4u** [prisma/web#2030]
I read [requirements-for-seeding-with-typescript-or-javascript](https://www.prisma.io/docs/guides/database/seed-database#requirements-for-seeding-with-typescript-or-javascript) and wrote my seed function. However, when I try to run `prisma migrate reset ` command, it does not exit after execution. Then I realize I have to call `await prisma.$disconnect();` inside the seed function after reading  [seeding-your-database-with-typescript](https://www.prisma.io/docs/guides/database/seed-database#seeding-your-database-with-typescript). I feel it will be better to be more clear about that user should include the `$disconnect` inside the exported seed function.

**Comment by ruheni** [comment]
This has been documented and added to the docs 🙂
