### ISSUE TITLE
Linkable troubleshooting section on how to workaround the MongoDB ReplicaSet error

### ISSUE THREAD

**Issue by matthewmueller** [prisma/web#2039]
You'll see this error (from [this issue](https://github.com/prisma/prisma/issues/8289))

```
PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: 
Invalid `prisma.post.create()` invocation in
/Users/ali/Documents/Work/ViaVid/Prisma/blog/index.ts:9:21

   6 await prisma.$connect()
   7 
   8 // Create the first post
→  9 await prisma.post.create(
  Error in connector: Database error. error code: unknown, error message: Transactions are not supported by this deployment
    at cb (/Users/ali/Documents/Work/ViaVid/Prisma/blog/node_modules/@prisma/client/runtime/index.js:34804:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.27.0'
}
```

There's some workarounds described in [this issue](https://github.com/prisma/prisma/issues/8266)

**Comment by janpio** [comment]
Now documented at https://pris.ly/d/mongodb-troubleshooting-transactions

**Comment by mandeepsingh10** [comment]
I was facing the same issue trying to dockerize a full stack app which was originally developed using React, Tailwind, Next, Prisma, Mongo Atlas, NextAuth.
https://github.com/mandeepsingh10/chwitter
The docker-compose.yml spins up mongoDB replica along with the nextjs-frontend.  
The code can be used to fix the connectivity issue between prisma and MongoDB replicasets.
