### ISSUE TITLE
Make search box sticky

### ISSUE THREAD

**Issue by schickling** [prisma/web#204]
We've recently introduced the sticky scroll side navigation (which is great 👏) however the search box is not yet sticky. I'm not sure whether this was intentional but I'm proposing to make the search box sticky as well.

![image](https://user-images.githubusercontent.com/1567498/79203894-fc57bc80-7e3b-11ea-900c-4ce8b88f78b9.png)

cc @kuldar @nilubava @nikolasburk

**Comment by zebapy** [comment]
Yes, this. It's a pain being way down on the page and wanting to search. I did discover you can press `/` to focus the input like most modern doc search sites are coming to add, but there's no communication to the user that you can do so. I started to open a PR to add `Press "/" to focus` to the placeholder but there's no room for it. It would be great to 1) make it sticky 2) add the focus hint
