### ISSUE TITLE
Percy: Images sometimes do not load

### ISSUE THREAD

**Issue by janpio** [prisma/web#2041]
Sometimes the tests on Percy, https://percy.io/6faef5e0/prisma-docs, do not load images although they should, which leads to diffs to be accepted and checked.

![image](https://user-images.githubusercontent.com/183673/125828869-b5e5768d-5aaa-4032-99d7-816f577c314f.png)
![image](https://user-images.githubusercontent.com/183673/125828915-1bdf2710-2a1e-49c3-a421-32c72f940825.png)

**Comment by avocadowastaken** [comment]
I never has this issue before, maybe it's because of `gatsby-image` plugin, which adds multiple `srcset` variants, and Percy has problems with it? I think asking them directly from the intercom of the failed snapshot should help

**Comment by avocadowastaken** [comment]
But you can't do it in Safari 😄 it blocks segment, which loads Intercom

<img width="367" alt="image" src="https://user-images.githubusercontent.com/4734297/125901236-5fb21db0-7983-441d-9b18-19f6b8115a41.png">

That's why I could ask them myself, at first I thought it's because of lack of permissions

**Comment by avocadowastaken** [comment]
Scratch it, seems like they completely removed realtime intercom support, and you have to submit tickets in https://www.browserstack.com/contact?ref=percy#technical-support 😕

**Comment by janpio** [comment]
I did send them a ticket now with a link to this issue. Let's see if they have an idea how to debug and resolve this.

**Comment by nikshiko** [comment]
@janpio any updates on this issue?

**Comment by janpio** [comment]
No, we made images invisible to Percy to avoid this.
