### ISSUE TITLE
Help article for "Querying models based on their relations existence" only describes list relationships

### ISSUE THREAD

**Issue by hiddenist** [prisma/web#2042]
https://www.prisma.io/docs/support/help-articles/finding-entities-based-on-relation

This help article only explains how to query existence on a list relationship, but not if the related model is singular.

Using the same example schema:

```prisma
model User {
  id    Int    @id @default(autoincrement())
  name  String
  posts Post[]
}

model Post {
  id     Int   @id @default(autoincrement())
  user   User? @relation(fields: [userId], references: [id])
  userId Int?
}
```

How would one write a query on all posts that have a user? Or that don't have a user?

```typescript
await prisma.post.findMany({
  where: { user: /* user exists? */ },
})
```

```typescript
await prisma.post.findMany({
  where: { user: /* user does not exist? */ },
})
```

**Comment by hiddenist** [comment]
Still wondering about this. Is this the correct syntax?

```typescript
await prisma.post.findMany({
  where: {
    user: { isNot: null }
  },
})
```

```typescript
await prisma.post.findMany({
  where: {
    user: { is: null }
  },
})
```

**Comment by ruheni** [comment]
Hey 👋

Apologies for the delayed response. You can filter for null if a relation is singular as follows:

```ts
await prisma.post.findMany({
  where: {
    author: null
  }
})
```

We'll add this to the docs soon. 🙂
