### ISSUE TITLE
Incorrect example queries in the next steps page of the MongoDB Getting Started guide 

### ISSUE THREAD

**Issue by TasinIshmam** [prisma/web#2049]
### Context

The [Next Steps page](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/mongodb/next-steps-typescript-mongodb) in the MongoDB getting started guide has a number of example queries under the subsection **Expand for more Prisma Client API examples**.  However, most of these queries do not match the schema provided in the [Creating the Prisma schema](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/mongodb/creating-the-prisma-schema-typescript-mongodb) page of the same guide.  This is true for both the javascript and typescript tutorials. 

This might be confusing for new users. 

### Details

```javascript
const filteredPosts = await prisma.post.findMany({
  where: {
    OR: [{ title: { contains: 'hello' } }, { content: { contains: 'hello' } }],
  },
})
```
- Tries to use the  ```content``` field, which does not exist in ```post```. Should be ```body```. 

```javascript
const post = await prisma.post.create({
  data: {
    title: 'Join us for Prisma Day 2020',
    author: {
      connect: { email: 'alice@prisma.io' },
    },
  },
})
```
- Tries to connect to the ```author``` relation field which does not exist in ```post```. Should be ```user```. 
- Missing mandatory fields ```slug``` and ```body``` 

```javascript
const posts = await prisma.profile
  .findUnique({
    where: { id: 1 },
  })
  .user()
  .posts()
```
- No model called ```profile``` in the schema. 

_I would be happy to make a PR to fix this._

**Comment by janpio** [comment]
PR would be great indeed @TasinIshmam

**Comment by TasinIshmam** [comment]
Great, I'll update with a fix :smile:  @janpio
