### ISSUE TITLE
Left align table content

### ISSUE THREAD

**Issue by schickling** [prisma/web#207]
For horizontally "narrow" tables the content currently feels very "stretched out". I suggest to rather left align the table content. ([Example link](https://www.prisma.io/docs/getting-started/quickstart#download-starter-project--install-dependencies))

![image](https://user-images.githubusercontent.com/1567498/79218410-a80b0780-7e50-11ea-85e8-55e0f141a58a.png)

**Comment by janpio** [comment]
Problem fundamentally still exists.
