### ISSUE TITLE
MSSQL: (Nice to have) Consider adding limitation of raw SQL execution for SQL Server (e.g. `SET`...) on this page

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/web#2089]
https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
