### ISSUE TITLE
MSSQL: Update the cascading rules section to point to the usage of referential actions as a solution instead of manual update of the migration file

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/web#2091]
https://www.prisma.io/docs/concepts/components/preview-features/sql-server/#cascading-rules

**Comment by keerlu** [comment]
Closing this - it's an old link that no longer exists and the current version of the connector has a [section](https://www.prisma.io/docs/concepts/database-connectors/sql-server#cyclic-references) on using referential actions for cyclic references.
