### ISSUE TITLE
MSSQL: (Getting started) Move this "start from scratch" page and merge it in the main one from our "Getting started" section

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/web#2095]
Part to move: https://www.prisma.io/docs/concepts/components/preview-features/sql-server/sql-server-start-from-scratch-typescript
Where to move it to: https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases-typescript-postgres

**Comment by molebox** [comment]
Continuation of this issues is dependent on https://github.com/prisma/prisma/issues/8764 being solved so we can use `prisma migrate` in the guide, instead of `introspect`
