### ISSUE TITLE
MSSQL: Figure out where to place the guides to set MSSQL up locally or using Docker

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/web#2096]
Guide about local: https://www.prisma.io/docs/concepts/components/preview-features/sql-server/sql-server-local
Guide about Docker: https://www.prisma.io/docs/concepts/components/preview-features/sql-server/sql-server-docker

**Comment by janpio** [comment]
Dataguide could be a good location for these honestly.

**Comment by ruheni** [comment]
This is now documented here: https://www.prisma.io/dataguide/mssql/setting-up-a-local-sql-server-database
