### ISSUE TITLE
Add more information about the `--name` flag when running the migration CLI command

### ISSUE THREAD

**Issue by molebox** [prisma/web#2101]
When running a migration we use the `--name` flag to help distinguish between migration histories. This is noted [here](https://www.prisma.io/docs/reference/api-reference/command-reference#arguments-6)  and briefly [here](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate#first-migration-initialize-migration-history). 

Even though the CLI prompts the user for a name after a change to the schema has been made, it might be helpful to briefly mention why in these places:

- [docs/guides/database/developing-with-prisma-migrate](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate)
- [docs/concepts/components/prisma-migrate](https://www.prisma.io/docs/concepts/components/prisma-migrate)

**Comment by keerlu** [comment]
Looks like the first one got done:
- https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate#:~:text=Note%3A%20If%20you%20do%20not%20provide%20a%20%2D%2Dname%2C%20the%20CLI%20will%20prompt%20you%20for%20a%20name.
