### ISSUE TITLE
Unit testing documentation not working because of a breaking change in jest-mock-extended v.2.0.0

### ISSUE THREAD

**Issue by fbennets** [prisma/web#2109]
### Bug description

The [documentation for unit testing](https://www.prisma.io/docs/guides/testing/unit-testing#mocking-the-prisma-client) is currently not working due to typescript errors.

Version 2.00 of jest-mock-extended, which is used in the documentation, contains some breaking changes, the [changelog](https://github.com/marchaos/jest-mock-extended/releases/tag/2.0.0) states: `Potential backwards compatibility issues for use of mock() where deepMock() may be required. This may result in TS errors`.

A quick fix is to just install  version 1.0.18 using:

`npm install jest-mock-extended@1.0.18 --save-dev`

It would be a good idea to update the documentation [here](https://www.prisma.io/docs/guides/testing/unit-testing#mocking-the-prisma-client).

### How to reproduce

1. Follow the documentation for unit testing.
2. Typescript throws an error when trying to call `prismaMock.user.create.mockResolvedValue(user)` as mockResolvedValue is not available.

### Prisma information

Irrelevant

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v14.17.3

### Prisma Version

```
prisma               : 2.27.0
@prisma/client       : 2.27.0
```

**Comment by molebox** [comment]
Hey @fbennets thanks for this. Im currently talking with another user and came to the same conclusion. Will update the docs today. 🙌

**Comment by fbennets** [comment]
Thanks! But I noticed that the changed docs still don't work for me when using jest-mock-extended 2.0.2-beta2.

`import { DeepMockProxy } from "jest-mock-extended/lib/Mock";` gives me the following error: `Cannot find module 'jest-mock-extended/lib/Mock' or its corresponding type declarations.`

It works when importing from the sub-folder /mjs/:
`import { DeepMockProxy } from "jest-mock-extended/lib/mjs/Mock";`

But maybe it's just some misconfiguration on my side.
