### ISSUE TITLE
Update docs to reflect that `prisma introspect` gets deprecated in favor of `prisma db pull`

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/web#2115]

**Comment by Jolg42** [comment]
Docs can be done anytime, preferably before Prisma 3 is released. (Note for @molebox)

db pull was introduced with 2.18.0 https://github.com/prisma/prisma/releases/tag/2.18.0

The deprecation notice in the CLI will be part of 2.30 release
https://github.com/prisma/prisma/issues/8078
