### ISSUE TITLE
Make additional changes to the Enabling `namedConstraints` page

### ISSUE THREAD

**Issue by molebox** [prisma/web#2120]
The Enabling `namedConstraints` page needs some additional work. 

See comments in code and on this PR: https://github.com/prisma/docs/pull/2102

**Comment by janpio** [comment]
Also https://prisma-company.slack.com/archives/C5Z9TH6N9/p1628598128076300

**Comment by 2color** [comment]
We need to add the `name` and `map` arguments to the following page: https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#id 

For the following attributes: 
- `@id`
- `@@id`
- `@unique`
- `@@unique`
- `@@index`
- `@relation`

**Comment by do4gr** [comment]
I also added referential actions to `@relation` and the `map` argument to `@default` for Sqlserver (starting w. 2.30)
