### ISSUE TITLE
Change images that use `prisma introspect` to use `prisma db pull`

### ISSUE THREAD

**Issue by molebox** [prisma/web#2135]
List of images that need changes, check figma files: 
 

- [ ] https://imgur.com/f7itiYw.png from https://www.prisma.io/docs/concepts/components/introspection
- [ ] https://imgur.com/ToNkpb2.png from https://www.prisma.io/docs/concepts/components/introspection
- [ ] https://www.prisma.io/docs/concepts/overview/what-is-prisma

Add more if you find them

**Comment by thebiglabasky** [comment]
@julietacurdi Would we have a link to the figma files? This looks like something we could do ourselves without bothering Tara and team :)

**Comment by julietacurdi** [comment]
@thebiglabasky @molebox 
Here're those listed on the ticket updated:
- <img width="800" alt="introspection" src="https://user-images.githubusercontent.com/20726387/129399378-d5fcfb09-4018-4e6e-ba3e-dcc1a032dcba.png">
- <img width="800" alt="workflow" src="https://user-images.githubusercontent.com/20726387/129399424-a4e6c9a3-cb69-40e8-8a07-9f2b3cfee697.png">


This is the Figma File where i found them. Warning its super messy, let me know if you need help. I'll take a look at organizing it a bit
https://www.figma.com/file/Mnxg1PktDeysCi8IhnWUp50Z/Diagrams?node-id=1311%3A2676
