### ISSUE TITLE
Update Prisma Schema reference, attributes signatures for GA

### ISSUE THREAD

**Issue by janpio** [prisma/web#2168]
Remove all "As of ..." with small notes "(Until 3.0.x, ... was not available)" (or similar)

**Comment by molebox** [comment]
Do you mean to add a note saying that before 3.0, was not available? Are you referring to https://github.com/prisma/docs/pull/2166

**Comment by janpio** [comment]
> Are you referring to #2166

Yes, that is the PR that added these notes.

> Do you mean to add a note saying that before 3.0, was not available?

The docs always reflect the latest state by default. After 3.x these things will be available by default. So adding a `(Until 3.x, `map` was not available)` for the cases where we added it with 3.x should suffice to replace all the preview feature flag variants and also enable user of older versions to figure out what is available or not.
