### ISSUE TITLE
Fix TOC default depth so that we see nested children when viewing page.

### ISSUE THREAD

**Issue by molebox** [prisma/web#2169]
The TOC now only opens up its child elements as you scroll to them. This is a little odd when coming to the page via a link, or indeed when on the page and wanting to get an overview of what's on the page via looking at the TOC.

One possible solution is to check the url params for the `references` key word, which indicates the user is on the references section of the docs and the child elements on the TOC should **_not_** be expanded. On any other route we should expand them to the depth stated on the `tocDepth` prop on the frontmatter

**Comment by meletj** [comment]
Stale
