### ISSUE TITLE
“Was this helpful buttons” bug on firefox

### ISSUE THREAD

**Issue by Jolg42** [prisma/web#217]
Only in Firefox / works on Chrome

On https://www.prisma.io/docs/ when I click on the “Was this helpful buttons” it doesn’t work (looks like the sentiment is sent though)

<img width="890" alt="Screen Shot 2020-04-15 at 10 45 59" src="https://user-images.githubusercontent.com/1328733/79323646-c33c4c80-7f0e-11ea-927a-f530b3f98af0.png">
<img width="160" alt="Screen Shot 2020-04-15 at 10 46 40" src="https://user-images.githubusercontent.com/1328733/79323650-c5061000-7f0e-11ea-935b-37260081a359.png">

**Comment by janpio** [comment]
Can confirm.

The request is successful:
![image](https://user-images.githubusercontent.com/183673/79348191-f72a6880-7f34-11ea-972d-97d87abbaca7.png)

But the console still shows this error:
![image](https://user-images.githubusercontent.com/183673/79348218-04dfee00-7f35-11ea-8e0f-bee2efac809b.png)
