### ISSUE TITLE
Link preview component

### ISSUE THREAD

**Issue by molebox** [prisma/web#2176]
I saw [this video](https://twitter.com/swyx/status/1428149223850012673?s=20) from [swyx](https://twitter.com/swyx) today and this would be a cool feature for us to add in our docs imo. 

The basic premise is that you create a new tag called whatever you like, he called it `preview` and you a new component that wraps all links, or certain links. This component shows a preview excerpt from the linked page on hover in the form of a small popup. 

The could be helpful to add a little more context to links.

**Comment by katungi** [comment]
Hey @molebox , I just saw the video and I completely agree that this would be a cool feature to add to the docs. Context switching is usually distracting and more information on the links would be a good addition. 

I am willing to help implement this if you are up for it 🥳

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
