### ISSUE TITLE
"Prisma resolves SSL certificates relative to the `./prisma` directory."

### ISSUE THREAD

**Issue by janpio** [prisma/web#2194]
I do not think this is correct. Most probably it resolves them relative to the (configured) schema location. (Needs to be confirmed by looking at code and optimally confirming via tests)

e.g. mentioned on https://github.com/prisma/docs/blob/1ec190902eedcb5cb30e79a63d754e31c323e048/content/200-concepts/100-components/01-prisma-schema/02-data-sources.mdx

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
