### ISSUE TITLE
Docs for advanced type safety incorrect

### ISSUE THREAD

**Issue by timsuchanek** [prisma/web#2197]
### Bug description

https://www.prisma.io/docs/concepts/components/prisma-client/advanced-type-safety#importing-generated-types

![image](https://user-images.githubusercontent.com/1094804/130087976-911a45ae-0728-4828-8633-41fa969585e5.png)

The whole docs page is doing explicit type casts. Those will however lose the type information.
The example in the screenshot is additionally incorrect.
When only querying posts, you'd have profile only.

We used to have some utility types for these cases.
@millsp probably knows where we have them.

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by molebox** [comment]
Hey @timsuchanek ! Hmm, I tested this and you do get both profile and posts in the `userPosts` type:

![prisma-typescript](https://user-images.githubusercontent.com/22930449/130618872-7592e2d8-d9be-47e2-846c-9cddc07df33f.gif)

I'll chat with @millsp though 😀

**Comment by millsp** [comment]
cc @andrew-walford-prisma @tanberry

**Comment by ankur-arch** [comment]
@millsp could you help me understand what the issue is here?

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
