### ISSUE TITLE
Lack of Explicit Many-to-Many relation example in Self Relation Docs

### ISSUE THREAD

**Issue by TasinIshmam** [prisma/web#2201]
In the [Self-Relation](https://github.com/prisma/docs/blob/8f1f1b01657b5263b622fffeef458ee528184c88/content/200-concepts/100-components/01-prisma-schema/06-relations/400-self-relations.mdx) guide, there is no example of explicit many-to-many self-relation. 

This makes the proper syntax for explicit many-to-many self relations potentially confusing, especially to new users. An explicit version of the many-to-many schema that's already provided in the article looks like this: 

```prisma
model User {
  id            String  @id @default(autoincrement())
  name          String
  followedBy    Follows[] @relation("follower")
  following     Follows[] @relation("following")
}

model Follows {
  follower    User @relation("followedBy", fields: [followerId], references: [id])
  followerId  String
  following   User @relation("following", fields: [followingId], references: [id])
  followingId String

  @@id([followerId, followingId])
}
```

This example can be added along with a link to the [many-to-many concept guide](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations/#explicit-many-to-many-relations). I believe this would make the article more comprehensive. 

Would love to hear thoughts/feedback on this!

**Comment by TasinIshmam** [comment]
Hi @molebox, could you provide your thoughts? 

I'd be happy to make a PR if you approve the change.

**Comment by molebox** [comment]
![looks-good](https://user-images.githubusercontent.com/22930449/130738982-af155251-2c00-40d5-adf8-40011e6a66c9.gif)
