### ISSUE TITLE
PostgreSQL gen_random_uuid() does no longer require the pgcrypto extension

### ISSUE THREAD

**Issue by benkroeger** [prisma/web#2209]
I crossed this in the documentation quite a few times: Docs say that you would need the `pgcrypto` extension in order to run the native database function `gen_random_uuid()` in postgres.
As of Postgres 13, that is [no longer true](https://www.postgresql.org/docs/13/pgcrypto.html).

As this info is spread across multiple pages in the docs, I figured it'd be best for you guys to decide where / how to reflect this info properly

![image](https://user-images.githubusercontent.com/7782055/130828769-f0ddbb60-224f-46b5-b124-b7a3b299bc4f.png)

**Comment by molebox** [comment]
Hey @benkroeger , thanks for opening this issue, we'll look into it 😎

**Comment by tomhoule** [comment]
We support postgres starting with 9.4, and many installations are on older versions, so I don't think we should aim to document the latest version exclusively. We could note that the `CREATE EXTENSION` is not needed on pg 13+ though.

**Comment by benkroeger** [comment]
yep, the mentioning of 13+ is what I was hoping for.

**Comment by keerlu** [comment]
As part of #4063 I've added notes that this only applies to PostgreSQL versions before 13 - closing now.

**Comment by pspsdev** [comment]
so is gen_random_uuid is still cryptographically secure?
