### ISSUE TITLE
Algolia: Do not reset search index, update

### ISSUE THREAD

**Issue by janpio** [prisma/web#2219]
My question to Algolia support:

> our list of "Top results" only contains "Missing or deleted record" and IDs with a count, but no information about _what_ the results are. Is this normal? How can we change it to be more useful?
>
> https://www.algolia.com/apps/MK4LNFW4EO/analytics/results/prisma2-docs?from=2021-06-30&to=2021-07-06
> ![image](https://user-images.githubusercontent.com/183673/131160568-21f49921-c459-4587-befd-dff35a79a6b4.png)

Their response:

> This list of search results matches onto a objectId of a record which matches the search query. Looking at you main product index, I can see that it appears to be being rebuilt on a regular basis.
> 
> Have you cleared out your index and rebuilt it as part of one of these build operations?
> 
> The objectIds that are listed no longer appear to be in your index, which is why this message is being shown. If you clear out your index and don't retain the objectId which is tied to a record then all your analytics data will be invalid as the searches are linked to a record. If you are completely rebuilding your index you will need to be able to maintain the objectId as it is in Algolia in order to be able to maintain this analytics data.

So to achieve better analytics on our records that are found via the search, we would need to change how we update our search index.

**Comment by ankur-arch** [comment]
@jharrell is this still relevant?

**Comment by ankur-arch** [comment]
Closing as it's outdated.
