### ISSUE TITLE
Algolia: Implement click events tracking on searches

### ISSUE THREAD

**Issue by janpio** [prisma/web#2220]
My question to Algolia support:

> I am trying to understand why I only see "There is no data yet" in our Analytics dashboard: 
> ![image](https://user-images.githubusercontent.com/183673/131160790-58b99eee-7820-42b2-82d4-5961ad6aad38.png)
> https://www.algolia.com/apps/MK4LNFW4EO/analytics/overview/prisma2-docs?from=2021-06-30&to=2021-07-06

Their response:

> Looking at your site, I can see that you have the Algolia search within the docs area of the site. However, it doesn't look like you are tracking any click events on these searches.
> 
> In order to collect the click position you need to tell Algolia that you want to track click events.
> 
> Some useful guides to setting this up can be found within our documentation:
> 
> https://www.algolia.com/doc/guides/getting-insights-and-analytics/search-analytics/click-and-conversion-analytics/
> 
> In addition to this, here is how you can track your click and conversion events.
> 
> Check from the source:
> 
> The first step is to use the Insights Validator plugin: https://www.algolia.com/doc/guides/getting-insights-and-analytics/search-analytics/click-through-and-conversions/in-depth/insights-validator-plugin/
> 
> This plugin tracks the click and conversion events in your developer tools, I recommend first checking it with a application with working click and conversion analytics like this one:https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/InstantSearch.js/algolia-insights
> 
> and checking that your own application is recording click and conversion events in the same way:
> 
> ![image](https://user-images.githubusercontent.com/183673/131160865-1cbfb1ba-6464-45c6-bcc9-df801f863cc2.png)
> 
> Once you see events coming through ok, the next place to check is your insights events logs on your dashboard: https://www.algolia.com/monitoring/insights
> 
> ![image](https://user-images.githubusercontent.com/183673/131160878-80f38709-3e63-4e5e-beb3-29a12dfca860.png)

**Comment by molebox** [comment]
Oh sweet, this looks good

**Comment by ankur-arch** [comment]
Closing as it's outdated.
