### ISSUE TITLE
CLI Output of `Log info, warn, and error events to console` only shows `info`

### ISSUE THREAD

**Issue by janpio** [prisma/web#2232]
https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#log-info-warn-and-error-events-to-console

As it only outputs two `info` logs, it is not really clear what the difference is to just documenting `info` alone. Even the difference to https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#log-a-query-event-to-console is not really clear.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
