### ISSUE TITLE
full-text search: Add a section on how to search for multiple words

### ISSUE THREAD

**Issue by matthewmueller** [prisma/web#2233]
We should document how you should search for multiple words

```ts
const results = await prisma.post.findMany({
  where: {
    body: {
      search: "second post".split(" ").join(" & "),
    },
  },
});
```

More Context: https://github.com/prisma/prisma/issues/8939

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
