### ISSUE TITLE
Search Box reloads page after hitting enter

### ISSUE THREAD

**Issue by do4gr** [prisma/web#224]
I ran into an issue with the search box:

I was entering a search term and hitting enter which led to the page just reloading and deleting the entered term. This led me to believe that search was broken. Only after others told me it's working for them did I wait long enough for results to show up and did NOT hit enter. 

Since I'm probably not the only one running into this we should maybe ignore enter in this case to allow time to load results?

**Comment by janpio** [comment]
I can confirm this.

We should probably also add some instant feedback that the search will start when a first input into the field was done. Right now it really feels "slow". (Update: Now an issue at https://github.com/prisma/prisma2-docs/issues/225)

**Comment by Jolg42** [comment]
I also ran into this multiple times. It's confusing 🤯
