### ISSUE TITLE
Move Prisma Client generator reference to own page

### ISSUE THREAD

**Issue by janpio** [prisma/web#2261]
Right now most of https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#generator is actually not about the `generator` block, but about the custom properties that the `prisma-client-js` generator  allows to be used and their valid values.

We should move all non generic fields an explanations and almost all examples (except first and last right now) to a new "Prisma Client Generator reference" or "`prisma-client-js` reference" (and add an explanation of generator specific fields and add an example of their usage). That would make the `generator` block rather short, but allow us to create a much more authoritative (and shorter, readable) page for `prisma-client-js` that is not hidden and linked prominently as the prime example from the schema reference.

**Comment by ankur-arch** [comment]
I'm closing this issue as the current page correctly serves as a proper [reference](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#generator).
