### ISSUE TITLE
Double check and update all "Code with output component" usages

### ISSUE THREAD

**Issue by janpio** [prisma/web#2294]
https://github.com/prisma/docs/issues/2271 + https://github.com/prisma/docs/pull/2279 added customizable text for "Code with output component". We should make sure we use it appropriately everywhere we use this component.

**Comment by Swastyy** [comment]
Hi @janpio , Can I work on this?

**Comment by janpio** [comment]
I think that would be nice. 

To repeat: The goal here is to add `outputResultText` to files using `CodeWithResult` where the output shown is not actually "CLI output" so the rendered text is more accurate.

**Comment by tanberry** [comment]
This sounds good to me too... a few questions please, @janpio and @Swastyy (since I am new to Prisma docs and new to to these types of interactive components within a markdown file):
-- is `CodeWithResult` the same thing as "code with comments"?
-- what is the diff between  `<cmdResult>` and  `<outputResultText >` or are they very different components?
-- @janpio your point above about the goal... is the output displayed in the CLI, or... where?
-- @Swastyy could you do an audit of where all in the docs you find the use of `CodeWithResult`, and list them here, or do you see value in identifying those first, before starting the work?
Thanks, sorry so many questions!

**Comment by janpio** [comment]
> -- is CodeWithResult the same thing as "code with comments"?


`CodeWithResult` is a component we can use in the docs to achieve a specific component to be rendered.
Examples here: https://www.prisma.io/docs/about/prisma-docs/style-guide/mdx-examples#code-with-output

Not sure what you refer to with `code with comments` - maybe a typo and you meant `code with output`? Then the answer would be "Yes" 👍 

> -- what is the diff between <cmdResult> and <outputResultText > or are they very different components?

- `cmdResult` is part of the `CodeWithResult` component - it is one of the inner elements needed.
- `outputResultText` on the other hand is an optional attribute of `CodeWithResult` - see the second example in the page i linked above where it shows its usage under the text "Example with custom output text" (which is a terrible example because it _also_ shows CLI output as the example...)

> -- @janpio your point above about the goal... is the output displayed in the CLI, or... where?

When we introduced the `CodeWithResult` component, we assumed we would always display a CLI command and its putput in the docs, so e.g. `npx prisma -v` and then 
```
prisma                  : 3.4.0
@prisma/client          : Not found
Current platform        : windows
Query Engine (Node-API) : libquery-engine 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 1c9fdaa9e2319b814822d6dbfd0a69e1fcc13a85
Studio                  : 0.438.0
```

But later this component was also used to show user input/commands and output. The original issue does not mention exactly what other types we have in the docs unfortunately and I do not recall - figuring this out is part of the work here.

> -- @Swastyy could you do an audit of where all in the docs you find the use of CodeWithResult, and list them here, or do you see value in identifying those first, before starting the work?

That would make a lot of sense. 
If there are no locations where we do show non-CLI output, there is actually nothing to do.

**Comment by Swastyy** [comment]
> When we introduced the `CodeWithResult` component, we assumed we would always display a CLI command and its putput in the docs,
> But later this component was also used to show user input/commands and output. The original issue does not mention exactly what other types we have in the docs unfortunately and I do not recall - figuring this out is part of the work here.

Hi @janpio , the CLI output we are seeing in the above link you attached is because the function returns that. How changing the docs will change the function's o/p? Do I have to make changes only to the docs for website? Or we need to create a new function/method `outputResultText` ? because I can see `outputResultText` is already implemented.

**Comment by janpio** [comment]
This issue is only about updating the content of the docs website, to use `CodeWithResult` with `outputResultText` where appropriate (vs. `CodeWithResult` without the additional `outputResultText` right now).

**Comment by Swastyy** [comment]
> This issue is only about updating the content of the docs website, to use `CodeWithResult` with `outputResultText` where appropriate (vs. `CodeWithResult` without the additional `outputResultText` right now).

Ohhkay, thanks for helping @janpio . I'll do it.

**Comment by ankur-arch** [comment]
Hey @Swastyy 👋, I'm closing this issue for reasons as this seems outdated, but please feel free to open other issues in the future if you notice anything that can be improved in the Prisma docs 🙏
