### ISSUE TITLE
Create page for `filterJson` preview feature

### ISSUE THREAD

**Issue by molebox** [prisma/web#2295]
We dont seem to have any information at all on the `filterJson` preview feature

----
Andrew: We now have docs on this:
[Filter on a Json field](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filter-on-a-json-field)

As a result, I'm closing this issue.

**Comment by Jolg42** [comment]
Since v4.0.0 the feature is GA.
I'm not sure what this issue is about, docs are here https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filter-on-a-json-field
