### ISSUE TITLE
Database matrix page to update with full text search support in preview

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/web#2302]
https://www.prisma.io/docs/reference/database-reference/database-features currently shows that Phrase full text search isn't supported by Prisma client which isn't true anymore since adding support in preview. We should consider mentioning that and linking to the full text search documentation section.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
