### ISSUE TITLE
Wrong comment description in landing page

### ISSUE THREAD

**Issue by arvindell** [prisma/web#233]
It's right here:
<img width="808" alt="Screen Shot 2020-04-17 at 18 18 18" src="https://user-images.githubusercontent.com/29064411/79621151-f8e06180-80d7-11ea-90a6-a26f09720078.png">
I believe it should say `Intro`

**Comment by nikolasburk** [comment]
Thanks a lot for catching this @alexvilchis, this should now be fixed 🙏  (fix currently deploys)
