### ISSUE TITLE
Document new supported DBs

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#236]
![image](https://user-images.githubusercontent.com/4058327/79761385-a6928100-8321-11ea-837f-6df6cb40f8ec.png)

We now also support:

- MySQL 5.6

And therefore also support:

- AWS Aurora Serverless

**Comment by Jolg42** [comment]
Based on https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.html
It looks like we support AWS Aurora MySQL and AWS Aurora Serverless (MySQL) (all versions)

And based on https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Updates.20180305.html
It looks like we support AWS Aurora PostgreSQL and AWS Aurora Serverless (PostgreSQL) (all versions)
