### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#244]
> According to @janpio's report

Docs starts page on Windows:

![image](https://user-images.githubusercontent.com/4058327/79953938-eae66400-847c-11ea-88c8-bcf04287d8f1.png)

And clicking on "Quickstart" links to https://www.prisma.io/docs/getting-started/quickstart which then breaks my back button with a redirect:
I keep getting redirected to https://www.prisma.io/docs/getting-started/quickstart?lang=typescript when using the Back button.

**Comment by nilubava** [comment]
Resolved in https://github.com/prisma/prisma2-docs/commit/0b6a296f4c7fa51250660c514fa92b724947042d and https://github.com/prisma/prisma2-docs/commit/8bc93f00e41f928c02edea02ccc711a288017070

**Comment by janpio** [comment]
Can confirm. Thanks!
