### ISSUE TITLE
How does the Prisma client talk to the Prisma Rust engine binaries?

### ISSUE THREAD

**Issue by benmccann** [prisma/web#248]
How does the Prisma client talk to the Prisma Rust engine binaries?

I'm assuming the engine binaries talk to the database over TCP using the standard database connection string.

It'd be nice to document how the communication happens on https://www.prisma.io/docs/understand-prisma/under-the-hood

**Comment by tanberry** [comment]
Hullo, the Prisma Docs team is closing older tickets that might be stale or no longer relevant. If you feel we have closed this Issue in error, please feel free to re-open it, or create a new Issue to update the topic. Thank you for being involved in our docs!
