### ISSUE TITLE
Description about Prisma's dataloader / 1+n problem

### ISSUE THREAD

**Issue by ryands17** [prisma/web#252]
I have seen a lot of questions regarding how Prisma2 solves the (n + 1) problem. We could have a section in the docs about the working of Prisma's dataloader so that users can understand better.

**Comment by nikolasburk** [comment]
This should also address the question of this user: https://prisma.slack.com/archives/CKQTGR6T0/p1587637023135500

**Comment by nate-anderson** [comment]
As pointed out in a comment on #798 there is a [YouTube video](https://www.youtube.com/watch?v=7oMfBGEdwsc) in which a Prisma engineer explains how the N+1 problem is solved in Prisma. It would be nice if this were officially part of the docs, which are already a strength of the package IMO

**Comment by Jolg42** [comment]
Note: the current dataloader is for findUnique queries (but not multiple findMany queries)

**Comment by mhwelander** [comment]
Documented here: https://www.prisma.io/docs/guides/prisma-guides/query-optimization-performance
