### ISSUE TITLE
Selectively add drop-shadow to images

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#26]
![image](https://user-images.githubusercontent.com/4058327/77551886-24927200-6eb3-11ea-8c71-561f462bb159.png)

```
Daniel Norman  12:18 PM
Btw, quick tip on window screenshots: disable shadow. Gatsby image processing makes them look really bad
https://www.macobserver.com/tmo/article/how-to-disable-screenshot-shadows-in-yosemite-and-mavericks (edited) 
macobserver.commacobserver.com
How To Disable Screenshot Shadows in Yosemite and Mavericks – The Mac Observer
Today's tip comes from Charles Edge, author and long time Mac admin. If you're looking to forsake the drop shadows in screen shots, you can do so with a simple Terminal command. Kelly breaks it all down for you.

nikolas:expressionless:  12:21 PM
Hmm do you know if that can be fixed on the Gatsby-side? I think having this is actually quite nice but I agree that the current rendering is rather off-putting :thinking_face:

Daniel Norman  12:31 PM
Gatsby’s image optimiser could probably be configured. We can address that at some point
:+1:
```

**Comment by mhwelander** [comment]
@nikolasburk I set `disableBgImageOnAlpha` to `false` a while back because images with transparency got a very strange smudgy background.

Can I close this or do we plan to manually add drop-shadows to screenshots (specifically screenshots)?

**Comment by nikolasburk** [comment]
So, Mac OS can add drop shadows to screenshots (of full windows) automatically and I've been doing that pretty consistently (I think it's a much nicer visual than without...). Does `disableBgImageOnAlpha` set to `false` mean that we can't display drop shadows?

**Comment by mhwelander** [comment]
I don't think so - it just stops this from happening:

![image](https://user-images.githubusercontent.com/849648/85412607-0b5c9880-b56a-11ea-97d4-a94aa89b896f.png)

I'll experiment with adding a class, markdown apparently supports that.

**Comment by mhwelander** [comment]
Ability to add drop shadow to *some* images - not required for transparent diagrams. Suggest a class or some flag.
