### ISSUE TITLE
Automate prettier

### ISSUE THREAD

**Issue by schickling** [prisma/web#266]
Since we're using `prettier` to auto-format MDX I suggest to streamline things even more to avoid cases like this (see [docs link](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/relation-queries)).

![image](https://user-images.githubusercontent.com/1567498/80360078-1b643e80-887f-11ea-8cc3-59302ed4c930.png)

Automation idea:
- [GitHub Prettier bot](https://github.com/marketplace/actions/prettier-action)
- Add prettier linter to build step
- Git Hooks via [Husky](https://github.com/typicode/husky)

**Comment by mhwelander** [comment]
Duplicate: #1215
