### ISSUE TITLE
Link checker doesn't ignore ordering prefixes (01-, 02-)

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#272]
Our pages are prefixed with 01-, 02- etc - however, the final output does not include those numbers, and neither do the links.

This means that the link checker looks at a link like "my-page" and assumes it doesn't exist because the file name is "03-my-page".

Is there any way to customize the link checker? 💚

**Comment by nilubava** [comment]
@mhwelander This is how the DevRel wanted it. The pages are numbered to order them.

**Comment by mhwelander** [comment]
@nilubava That I know - I meant that the link checker looks at a link (e.g. ../reference/tools-and-interfaces/prisma-schema/data-model) in an MDX file and says "that's broken" because the 'real' path is  ../01-reference/01-tools-and-interfaces/03-prisma-schema/02-data-model. But the link isn't broken at all, because the rendered HTML does't include 01-/02- etc.

Is there a way to extend the link checker to ignore prefixes in the format '0X-' when checking links. In other words, it sees this link in an MDX file: ../reference/tools-and-interfaces/prisma-schema/data-model --> and  understands that the link matches this page: ../**01-**reference/**01-**tools-and-interfaces/**03-**prisma-schema/**02-**data-model (using regex I guess?)

**Comment by nilubava** [comment]
@mhwelander Okay, now I get it. I will explore the link checker options and see what can be done

**Comment by nikolasburk** [comment]
1. try if adjusting the current link checker in separate plugin works
1. if no, we first remove the current link checker and re-evaluate this issue in the next sprint meeting
