### ISSUE TITLE
og:url URL does not match actual URL

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#276]
Example: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/generating-prisma-client

However, the `og:url` for this page is: https://www.prisma.io/docs/generating-prisma-client (and we don't have any redirects set up for this)

This causes broken links in external link checkers.

@nikolasburk Just to make sure - were there plans to set up redirects for all pages or is `og:url` incorrect right now?

**Comment by nikolasburk** [comment]
> Just to make sure - were there plans to set up redirects for all pages or is og:url incorrect right now?

I don't think there were any plans to set up these redirects 🤔

**Comment by nilubava** [comment]
@mhwelander @nikolasburk Must have to do with latest changes for SEO. I will check this

**Comment by nikolasburk** [comment]
Also fix canonical URLs
