### ISSUE TITLE
MDX code blocks & more

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#285]
https://www.notion.so/prismaio/Docs-MDX-Code-block-9af4545b78c6455aa70f2e596a639905

**Comment by nikolasburk** [comment]
- [x] Tabbed component for generic MDX content
- [x] Line highlights: red, green, neutral
- [x] File icons
- [x] Include terminal outputs in code block
- [x] Side-by-side code blocks
- [ ] Show hidden lines (top, middle, bottom of file)

**Comment by hrescak** [comment]
https://www.figma.com/proto/DChfqSLXxd77jJnG2xoM6d/Prisma-Docs-v2?node-id=452%3A1779&viewport=997%2C618%2C0.13714225590229034&scaling=min-zoom

^ This shows design for dark mode where the colors for terminal commands should come from.

**Comment by nikolasburk** [comment]
I'm closing this issue in favor of smaller, more targeted ones which I'm going to create.
