### ISSUE TITLE
Strategy for handling redirects on prisma.io/docs

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#289]
## Problem
When you delete, rename, or move a page, the URL changes - any external references to that URL (tweet, bookmark, etc) will break. This leads to unhappy users.

I would like some way to regularly, automatically compare snapshots of the doc site to make sure no pages were removed/renamed/moved without a redirect. For example (this is just an idea)

* On Monday at 00:00, the site is crawled by some kind of tool (not sure if we could use the Algolia index in some way?)
* On Monday at 09:00, I move two pages - and forget to create redirects for page A of those pages.
* On Tuesday at 00:00, the site is crawled and compared to Monday's crawl:
   * Page B is missing .. but the URL has been redirect ✔
    * Page A is missing ... and there is no redirect ❌

It would be great to receive an email / Slack notification / something of the broken URLs.

##  Notes

* Does not need to be part of build process - can be external tool that does not interfere with build.
* Should use server-side redirects (not JS redirects - although Google can follow those, a lot of crawler tools cannot)
* Documentation redirects should be (e.g. if Netlify _redirects file is used, store it in prisma2-docs repository and not with all other redirects for prisma.io)
* Need to confirm limitations of Netlify redirects, if any (e.g. how deep do redirects go)

**Comment by mhwelander** [comment]
Candidate to investigate: https://github.com/sw-yx/netlify-plugin-no-more-404

**Comment by janpio** [comment]
What is the strategy that makes this not necessary any more?
