### ISSUE TITLE
In-page anchor links going to /docs#[my-anchor]

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#302]
Click any title here: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/filtering
Click the 'not required' link here: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/filtering

Expected to stay on the page but jump to a different section - instead being redirected to the main /docs page.

**Comment by 2color** [comment]
Related: #301
