### ISSUE TITLE
Clarify relationship between docs and specs

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#306]
Based on this internal discussion:

![image](https://user-images.githubusercontent.com/4058327/80791646-9a64ba00-8b92-11ea-981b-e7bb1ea43ac5.png)

**Comment by janpio** [comment]
In their current state, the specs should probably not be documented at all.

**Comment by janpio** [comment]
This is probably obsolete soon as we are trying to work specs into the documentation.
