### ISSUE TITLE
Document JSON support

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#315]
as described here: https://github.com/prisma/prisma/issues/186#issuecomment-623413319

![image](https://user-images.githubusercontent.com/4058327/80962682-c475e080-8e0d-11ea-82bc-1a4bd1d44a7d.png)

**Comment by jeescu** [comment]
Anyone know what's the problem with this?

```
error: Type "Json" is neither a built-in type, nor refers to another model, custom type, or enum.
```

**Comment by andreyk-code** [comment]
Not sure if this is best place to post this, please let me know if this should be a separate issue.

Trying to use prisma client to seed a Json object into database. Receiving an error:

`
→  7   const instructor1 = await prisma.user.create(Error parsing GraphQL query: query parse error: Parse error at 13:11
Unexpected `"link"[StringValue]`
Expected `Name`, `:` or `}`
`

The seed config looks like this:

`
 const user1 = await prisma.user.create({
    data: {
      email: 'asdf@asdf.com',
      username: 'asdf',
      ...
      profile: {
        create: {
          type: 'profile-a',
          jsonObjectHere: {
            "link": "www.google.com",
            "profileButton": true,
          },
        }
      },
  `

Am I doing something wrong in my config or is prisma create not supporting JSON yet?

**Comment by mhwelander** [comment]
#444

**Comment by mhwelander** [comment]
Include JSON filtering examples: https://github.com/prisma/prisma/releases/tag/2.1.0

**Comment by janpio** [comment]
First introduced in beta.4: https://github.com/prisma/prisma/releases/tag/2.0.0-beta.4
Later versions added more functionality.
