### ISSUE TITLE
Make use of /index landing pages

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#317]
## Problem

Our documentation is quite deeply nested in places, but only the lowest level is exposed by navigation. For example, you can't see a 'Data import and export' overview page:

![image](https://user-images.githubusercontent.com/849648/80963317-fcc9ee80-8e0e-11ea-924e-b11f68e4ef87.png)

This means:

* We're losing out on a lot of tasty SEO-food landing pages where we can write overviews or link to other content - for example, 'Deploying Prisma'.
* Users can only navigate using side nav, which will be difficult if the content gets any more nested or a particular section becomes very big. 
* People who navigate by URL (e.g. by removing a section) will hit a lot of 404s.

## Suggestion

1) Redirect / to index pages. For example:

    * https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/ should always redirect to (and ideally *rewrite* because 'index' is not a nice name) to... 
    * https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/index 

2) If a page isn't a top-level page (e.g. Reference) or staticLink = true (e.g. Tools & Interfaces), take users to the actual page when they click a nav link rather than expanding the menu.  Behaviour should be: click text --> go to page, click arrow --> expand.

3) Create a component that lists the entire sub-tree of the section you are on (fully expanded). Make this an optional component that you add to the page in any location (e.g. `<Subsections Depth="2" />`

![image](https://user-images.githubusercontent.com/849648/81657255-04ede380-9438-11ea-8400-00ca0553203c.png)

4) Make **all** breadcrumb entries links - even 'Reference'. The way I can see an overview of what's contained in that entire section without having to use the nav, which is a bit small and cramped.

5) Make it possible to disable auto-generated ToC (e.g. by setting toc: false or sectionpage:true on the page):

![image](https://user-images.githubusercontent.com/849648/81657255-04ede380-9438-11ea-8400-00ca0553203c.png)

(remove `<hr />` and language switcher from underneath the title if toc:false/section:true - there's no in-page ToC so it's not required)

Related: https://github.com/prisma/prisma2-docs/issues/131

**Comment by nikolasburk** [comment]
Also related: https://github.com/prisma/prisma2-docs/issues/287

**Comment by nikolasburk** [comment]
- click on triangle: just expand
- click on title: expand and show index page
