### ISSUE TITLE
"Experimental" label overlap

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#322]
## Problem

Navigation labels (for example, [5 mins] on getting started) has some spacing issues:

1) Flush with scrollbar
![image](https://user-images.githubusercontent.com/849648/81067244-a9bf6c80-8ede-11ea-9c94-b0ada7a38b7b.png)

Suggest adding margin/border.

2) Overlaps title:

![image](https://user-images.githubusercontent.com/849648/81067414-ea1eea80-8ede-11ea-9a6e-40af53e73939.png)

Suggest adding max-width for title (to account for '999 hrs') and suggest conferring with design for 'Experimental' label. Tooltip and icon, maybe, and [Experimental] in the page title instead?

![image](https://user-images.githubusercontent.com/849648/81067795-8b0da580-8edf-11ea-88a4-046c19a7619b.png)

## Environment

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

**Comment by schickling** [comment]
cc @hrescak

**Comment by nilubava** [comment]
@hrescak Would it be better of we rethink the whole sidebar, since the fixed one with 'Experimental' or '5 min' tags looks a bit congested?

**Comment by hrescak** [comment]
@mhwelander and I talked about this potentially be solved by 14px sidebar items

**Comment by nikolasburk** [comment]
![image](https://user-images.githubusercontent.com/4058327/84773688-1436f280-afdd-11ea-85c7-5029a4631a4e.png)

**Comment by rahul3v** [comment]
I do have some suggestions, If you consider any one i can request a pull request with changes

![suuu](https://user-images.githubusercontent.com/24385409/85013077-9c55fd00-b181-11ea-8a0b-a2815ba83679.JPG)

1. A or B, !?

2. If not any then you have to add any related icons with little tooltip
