### ISSUE TITLE
Bring back ORM <> Prisma Client comparison pages

### ISSUE THREAD

**Issue by schickling** [prisma/web#324]
[In the Prisma 1 docs we had pages](https://v1.prisma.io/docs/1.34/understand-prisma/prisma-vs-traditional-orms/prisma-vs-typeorm-k9fh/) that compare Prisma Client with other existing ORMs. We should bring these pages back.

![image](https://user-images.githubusercontent.com/1567498/81177070-62041800-8fa6-11ea-8e8b-0e088feb4254.png)

**Comment by mhwelander** [comment]
https://www.prisma.io/docs/understand-prisma/api-comparisons
