### ISSUE TITLE
Document workaround for multiple .env files

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#328]
We should document how people can use multiple .env files as explained here: https://prisma.slack.com/archives/CKQTGR6T0/p1588854779489000?thread_ts=1588854278.488700&cid=CKQTGR6T0

![image](https://user-images.githubusercontent.com/4058327/81296030-92fd4f00-9071-11ea-9e97-3558bb03339e.png)

**Comment by mhwelander** [comment]
https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema#use-multiple-env-files-or-env-files-outside-the-prisma-folder

**Comment by janpio** [comment]
The linked document is unfortunately not correct. The `dotenv-cli` only needs to be installed if you want to use the `dotenv` command line tool (so for the last list item). The other list item probably works out of the box as Prisma comes with that dependency or needs to have the dependency installed via Npm.
