### ISSUE TITLE
Create a gatsby theme for docs projects

### ISSUE THREAD

**Issue by nilubava** [prisma/web#333]
- [x] Create the theme

- [ ] Push it to npm registry

- [ ] Pull it to `docs` project and adapt styles

- [ ] Pull it to `nexus-docs` project and adapt styles

- [ ] Pull it to `dataguide` project and adapt styles

Items to include in theme:

- [ ] Prisma icon (https://github.com/prisma/docs/pull/759)
- [ ] Tooltip from data guide
- [ ] Changes to highlighted nav item and h4: https://github.com/prisma/docs/pull/839

**Comment by hrescak** [comment]
We're going to put this on hold for various reasons
- Data guide is shaping up in a direction that is divergent from a 'documentation' website
- Nexus direction is still TBD
- Prisma Lens will take some responsibility of component sharing
