### ISSUE TITLE
Support 3rd level nesting (styling)

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#351]
## Problem

You can add a 3rd level to the navigation - however, the styling is slightly off (see left-hand grey border)

![image](https://user-images.githubusercontent.com/849648/82025565-d10dfa80-9691-11ea-8b5c-02a602637243.png)

## Suggestion / Request

Would like to be able to use this 3rd level of nesting for pages like this that are getting too long: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/crud

Can we revise the left-hand nav style to accomodate a 3rd level? Something like:

![image](https://user-images.githubusercontent.com/849648/82026194-b0927000-9692-11ea-9bcc-b0f0dfbd1e02.png)

**Comment by matthewmueller** [comment]
@mhwelander would section sub-headers also work? https://stripe.com/docs/issuing

Using the screenshot below, "Prisma Schema" would be "Issuing", "Data Model" would be "Cards"

<img width="251" alt="CleanShot 2020-05-19 at 14 27 52@2x" src="https://user-images.githubusercontent.com/170299/82326341-ef9b2b00-99dc-11ea-9244-e13a8dad023a.png">

**Comment by hrescak** [comment]
@matthewmueller and I talked about this and realized quickly we already have section titles 😂 
- Also something that can be much less pronounced problem when we use 14px default text here

**Comment by mhwelander** [comment]
@nilubava Notes for when we start this: implement as diagram in original post for now, but with the context page bold/black (like we have already on the site):

![image](https://user-images.githubusercontent.com/849648/85291723-214f5800-b49b-11ea-8b30-817f6c14d1a5.png)
