### ISSUE TITLE
Make Relations documentation easier to understand

### ISSUE THREAD

**Issue by ghost** [prisma/web#359]
Translated text in Google Translate:
I did not understand the topic that addresses the [relationship](https://github.com/prisma/docs/blob/master/content/03-reference/01-tools-and-interfaces/01-prisma-schema/06-relations.mdx)  between tables (many to many, one to many and one to one) is confused to understand.

Original text:
Eu não entendi o tópico que aborda sobre o [relacionamento](https://github.com/prisma/docs/blob/master/content/03-reference/01-tools-and-interfaces/01-prisma-schema/06-relations.mdx) entre tabela ( muitos para muitos, um para muitos e um para um ) está confuso de compreender.

**Comment by ghost** [comment]
Sorry, if I made this request in the wrong place.

**Comment by mhwelander** [comment]
Hi @Frotas101! Thanks for your feedback 🙏 - this is the correct place to report documentation issues. We've had similar feedback from others about this page and will look into making it easier to understand.

**Comment by shadoath** [comment]
I would second this. The [Many to Many relationships page](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations) needs to show more content on how to connect them.

**Comment by nikolasburk** [comment]
I'm closing this issue since we made some changes to the docs here recently. @shadoath in case you're still missing a specific example, feel free to open a new issue with some more details about what exactly you're missing 🙂
