### ISSUE TITLE
Investigate alexjs for catching insensitive language

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#362]
Slack: https://prisma-company.slack.com/archives/CD2HW8X2A/p1589789400418400?thread_ts=1589787541.416600&cid=CD2HW8X2A

https://alexjs.com/

**Comment by Jolg42** [comment]
Example
https://github.com/facebook/react-native-website/blob/master/.alexrc.js

The rules explanation
https://github.com/retextjs/retext-equality/blob/master/rules.md

**Comment by Jolg42** [comment]
You can run it like this `npx alex`

**Comment by janpio** [comment]
Some additional context that might be interesting: There recently were a few Twitter threads were some people expressed unhappiness with the broad strokes that alexjs uses - thing like `asian` being classified as possibly "profane" and the list of words just being taken from some source and not being tailored or customized. (Can't find an easy link to these discussions though - sorry)

Should be fine from our side though as long as we are aware of this.

**Comment by wooorm** [comment]
The stuff @janpio is calling attention to is https://wooorm.com/blog/alex/ (my side, linked at the bottom is that twitter thread).

**Comment by Jolg42** [comment]
Thanks @wooorm for the link!

I guess where alex could be useful here is to get a sense of what the current state is. Because it's a linter it can read all the text at once. Then we can decide what to update or not and ignore some rules.

So maybe more a one time use of the tool.
