### ISSUE TITLE
Show the same page only once in search results

### ISSUE THREAD

**Issue by sorenbs** [prisma/web#363]
Show the same page only once in search results, or maybe find a way to make secondary results less noisy

![image](https://user-images.githubusercontent.com/281337/82298610-ab943000-99b4-11ea-9b04-2376a6a5affc.png)

**Comment by nikolasburk** [comment]
We should follow up with. @hrescak to hear his thoughts on this one? I just de-duping pages in the search results fine or is there another way?

**Comment by hrescak** [comment]
While I'm taking a look at this, there also seems to be a different issue that the results are displayed twice? 
![image](https://user-images.githubusercontent.com/753458/82907010-105f0580-9f34-11ea-80a3-8731dcd55114.png)

**Comment by hrescak** [comment]
Additional Q: If we only did basic de-duplication based on target link, would that be a good start? It'd definitely prevent a full page of links to the same page - the slight downside is that you wouldn't be able to see all the snippets - this to me is a worthy tradeoff though.

**Comment by hrescak** [comment]
Did some quick design in the inspector:
![image](https://user-images.githubusercontent.com/753458/83653073-56961380-a589-11ea-9b10-eb7915abddc4.png)

it's a `<p>` with `margin-top:4px` with a span inside with these properties:
![image](https://user-images.githubusercontent.com/753458/83653206-79282c80-a589-11ea-934a-f287587976d6.png)

We probably have a better color for the background, I just tried to be quick

**Comment by janpio** [comment]
Is this information actually available via Algolia in the API we are using?

**Comment by rahul3v** [comment]
Well, the duplicate information is coming from **algolia API** (which you are using), **either** we have to **resolve the algolia API** or we have to  **create a client side re-filtering on algolia API response** to resolve the duplicates
