### ISSUE TITLE
Improve self relations example

### ISSUE THREAD

**Issue by maticzav** [prisma/web#371]
## Bug description

[Example](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#self-relations) in the docs suggests that self relations may be optional, but the types require the relation.

Am I missing something with the spec here? 😅 

Hope the reproduction helps! 🙂 

## How to reproduce

```prisma
datasource db {
    provider = "mysql"
    url      = env("DATABASE_URL")
}

generator client {
    provider = "prisma-client-js"
}

model User {
  id       Int      @id @default(autoincrement())
  name     String?
  husband  User      @relation("MarriagePartners", fields: [id], references: [id])
  wife     User?     @relation("MarriagePartners")
}
```

```ts
import { PrismaClient } from '@prisma/client'

const client = new PrismaClient()

client.user.create({
    data: {
        name: "George"
    }
})
```

https://github.com/maticzav/prisma-client--selfrelation-bug-reproduction

## Expected behaviour

Create method should have an optional `husband` field.

## Environment & setup

- OS: Mac OS
- Database: MySQL
- Prisma version: 
```
@prisma/cli          : 2.0.0-beta.2
Current platform     : darwin
Query Engine         : query-engine 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /Users/maticzav/Code/sandbox/prisma-client-self-relation-issue/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /Users/maticzav/Code/sandbox/prisma-client-self-relation-issue/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 76857c35ba1e1764dd5473656ecbbb2f739e1822 (at /Users/maticzav/Code/sandbox/prisma-client-self-relation-issue/node_modules/@prisma/cli/introspection-engine-darwin)
```
- Node.js version: v12.16.1

**Comment by mhwelander** [comment]
👋 Hi folks - the relations example has been updated: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#self-relations

(It includes example SQL that uses a unique constraint to create a 1-1 self-relation so that you can introspect.)

Thanks for raising the issue! 💚
