### ISSUE TITLE
Create CTA to create GH issue if search doesn't yield results

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#385]
Sometimes users search for something in the docs but get 0 results. In that case, we should create a CTA to create a feature request on GitHub so that users can request what they're looking for.

**Comment by nikolasburk** [comment]
Another idea could be a CTA to point people to Kappa instead. (Or both).

**Comment by jharrell** [comment]
This is blocked by https://github.com/facebook/docusaurus/issues/10737
