### ISSUE TITLE
Move images from imgur to self-hosted / strategy for hosting images

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#4]
![image](https://user-images.githubusercontent.com/4058327/77349307-1e798580-6d3b-11ea-9eed-88d7040200bd.png)

**Comment by janpio** [comment]
In regards to the blog this table contains a list of all the pages and images they contain: https://docs.google.com/spreadsheets/d/1rdLPd4QAPPCdl9YJSm-VaWuifyVIRcg8q5p78Xvi3Es/edit?usp=sharing

**Comment by Jolg42** [comment]
Could be done with Netlify Large Media maybe? (Requires Git LFS) https://www.netlify.com/blog/2019/02/26/manage-your-code-and-assets-together-with-netlify-large-media/

**Comment by Jolg42** [comment]
Something is happening 📸 😄

**Comment by thebiglabasky** [comment]
After discussing that today, we're considering going with Cloudinary to make it easier for the team going forward to manage assets while having a fair amount of capabilities which could prove useful down the road (transformations / optimizations mainly). Pricing is also gradually climbing reasonably so we should be good with that.
