### ISSUE TITLE
Discuss: Image optimization

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#411]
https://prisma-company.slack.com/archives/C5Z9TH6N9/p1591265569006800

**Comment by rahul3v** [comment]
@mhwelander, is there anyway that we can see the Images

**Comment by mhwelander** [comment]
We optimize images manually at the moment - the discussion is about investigating Netlify. :)

**Comment by meletj** [comment]
Discussing image storage and optimization within this newer https://github.com/prisma/docs/issues/3614
