### ISSUE TITLE
Fix Netlify /docs issue

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#422]
## Problem

Right now, no links on the doc site work as they all include '/doc', whereas the site (on Netlify) does not include the /doc subfolder.

Related:

* https://community.netlify.com/t/deploying-to-subdirectory/6957

**Comment by rahul3v** [comment]
Well, we can fix it by putting start page (index) in `src/pages` and generate all links to `/doc/content-links` and then deploy it on Netlify. So all content links can be accessed via `/docs/your-content-link`
