### ISSUE TITLE
Links do not render correctly on Windows

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#423]
## Problem

All links in MDX files render like this on Windows:

```
<a href="C:%5Cgetting-started%5Csetup-prisma%5Cadd-to-existing-project/">Add Prisma to an existing project</a>
```

**Comment by rahul3v** [comment]
I have fixed the issue, how can i push my code for this specific issue

**Comment by rahul3v** [comment]
The issue just resolved, you can close this now.!
