### ISSUE TITLE
Website is extremely slow/broken in Firefox

### ISSUE THREAD

**Issue by ghost** [prisma/web#425]
I'm not sure if this has been posted before, but prisma.io/docs is **extremely** slow in Chrome, and pretty much completely unresponsive in Firefox.

Like when I click the search bar, in Chrome it just takes very long for the search to appear - and the search is really slow, but at least it functions. In Firefox, when I get the search to appear by switching between tabs, the search gives 'not found' for every single thing I type.

Weird thing is, in Firefox actually nothing works. I can't click any link - heck, I can't click anything. I can scroll (only using the scroll wheel, the middle click scroll icon doesn't appear) but whenever I switch tabs and go back to the site, the scroll position is reset.

Eventually (still in Firefox) the "this page is slowing down your browser" appears.

I'm running Firefox 77.0 on Manjaro.

**Comment by Jolg42** [comment]
I'm curious if you can replicate this with Firefox in its Safe-Mode see https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode#w_how-to-start-firefox-in-safe-mode

Also do you have a lot of things open already / does your computer have available RAM and CPU?

**Comment by ghost** [comment]
I just checked again and it seems to be a lot better now, not sure why. I'm pretty sure when I tried it I had closed all other tabs and didn't really have too much else running in the background. I'll close this now.
