### ISSUE TITLE
Monitor search functionality

### ISSUE THREAD

**Issue by janpio** [prisma/web#427]
We had multiple cases where the Algolia search index was empty and search on the docs site was quietly failing until a team member noticed.

We should find a way to monitor either a) the content of the search index or b) the actual functionality of the search form on the site. Optimally we would get notified if something goes wrong.

**Comment by meletj** [comment]
related to https://github.com/prisma/docs/issues/467

**Comment by ankur-arch** [comment]
@jharrell is this still relevant?
