### ISSUE TITLE
Overlapping content on Website

### ISSUE THREAD

**Issue by ericsonluciano** [prisma/web#429]
#### Issue description
looks like the Explore the Prisma Client API menu is overlap on the bottom in Firefox Browser but both Safari and Chrome are working 
 I think it  should be a margin-top and bottom issue
```
.sidebar.jsx-964218087 {
    padding-top: 2rem;
    padding-bottom: 4rem;
}
```

#### Steps to reproduce the issue

1.  visited the site of prisma.io using firefox

#### What's the expected result?
![Imgur](https://i.imgur.com/H6Yu0Sw.png)

#### What's the actual result?
![Imgur](https://imgur.com/UawbRTw.png)

**Comment by rahul3v** [comment]
I think you have to update your Firefox browser, it works fine on the updated one (using Firefox version 76)

![prisma](https://user-images.githubusercontent.com/24385409/84471930-ff3c2580-aca3-11ea-8522-6a2b03f9cdc1.JPG)

**Comment by janpio** [comment]
I can not reproduce this any more. Let us know if you still can. Thanks.
