### ISSUE TITLE
Specifying options related to the `unique` attribute

### ISSUE THREAD

**Issue by ryands17** [prisma/web#434]
As per this [discussion](https://prisma.slack.com/archives/CKQTGR6T0/p1591796766313200) the `name` option that we can specify to give the constraint a specific name. Possible could be added [here](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/data-model#attributes)

- Also a point could be made that this is helpful when the field names are too long and the autogenerated name would give an error as the database only supports a limited amout of characters for a name. (The Slack discussion includes a specific example for this)

For e.g.

```prisma
model VeryLongModelName {
  id                      String @default(cuid()) @id
  longUsername            String
  emailIsToshort          String
  otherVeryImportantField String
  @@unique(fields: [longUsername, emailIsToshort, otherVeryImportantField], name: "unique_index")
}
```

**Comment by mhwelander** [comment]
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#unique-1
