### ISSUE TITLE
Document new raw features

### ISSUE THREAD

**Issue by timsuchanek** [prisma/web#441]
In Beta 6 we introduced 2 new `raw` features. We should document them:
https://github.com/prisma/prisma/releases/tag/2.0.0-beta.6

**Comment by Jolg42** [comment]
There is now documentation about queryRaw and executeRaw, so this could be closed maybe? @mhwelander 

https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/raw-database-access
