### ISSUE TITLE
Document Prisma Client as a shared private dependency

### ISSUE THREAD

**Issue by matthewmueller** [prisma/web#442]
Based on: https://github.com/prisma/prisma/issues/458 https://github.com/prisma/prisma/issues/1787

## Problem

It can be useful to share generated database clients across projects, maybe you've got many applications talking to the same database.

## Suggested Solution

Document this workflow: https://github.com/prisma/prisma/issues/1787#issuecomment-633881873

## Alternative Solution

Test and Document:

- [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)
- [git subtree](https://git.kernel.org/pub/scm/git/git.git/plain/contrib/subtree/git-subtree.txt)
- [npm private repo](https://docs.npmjs.com/creating-and-publishing-private-packages)

**Comment by nikolasburk** [comment]
Closing as not planned; we decided that this is not something that belongs into the Prisma docs.

**Comment by janpio** [comment]
I would disagree, this regularly comes up and some users are doing it - but we don't give users that can't figure it out themselves any guidance on how to achieve this.
