### ISSUE TITLE
Document PRISMA_BINARIES_MIRROR 

### ISSUE THREAD

**Issue by janpio** [prisma/web#447]
See https://github.com/prisma/prisma/issues/1333#issuecomment-607868654

Implemented a new ENV var `PRISMA_BINARIES_MIRROR` that also changes the download location that is used to get the binaries.

**Comment by Jolg42** [comment]
`PRISMA_BINARIES_MIRROR` default value is `https://binaries.prisma.sh` our AWS CloudFront endpoint for our binaries.

**Comment by mhwelander** [comment]
Related: #809

**Comment by Jolg42** [comment]
Interesting comments to understand which files the mirror can use
https://github.com/prisma/prisma/issues/3026#issuecomment-800144213
https://github.com/prisma/prisma/issues/3026#issuecomment-801719244

**Comment by molebox** [comment]
Related: #1425
