### ISSUE TITLE
Documentation for Introspection Warnings

### ISSUE THREAD

**Issue by janpio** [prisma/web#448]
`prisma introspect` recently added Introspection Warning messages to communicate to the user about guardrails that were applied during Introspection. This currently looks like this:

![image](https://user-images.githubusercontent.com/183673/77960325-64ed5800-72d8-11ea-9aba-ca08897451db.png)

We want to document these individually and offer workarounds. 
Additionally the error messages itself should be improved and link to the matching documentation.

PRs:
- Engine PR to change error message (with link): https://github.com/prisma/prisma-engines/pull/638
- Docs PR to add warning messages with description and workaround: https://github.com/prisma/prisma2-docs/pull/72
- Pris.ly PR to add short links for docs sections: https://github.com/prisma/pris.ly/pull/3

**Comment by janpio** [comment]
This would still be nice to have as people might wonder what these mean.

**Comment by mhwelander** [comment]
@janpio Error reference-style docs?

**Comment by janpio** [comment]
Maybe. Might also be enough to just mention Introspection Warnings, what they are and how they are output - and then possibly a few examples of the different "categories" and what you can/should do to work around these limitations.

**Comment by janpio** [comment]
Here is the list of warnings that can be generated, hopefully self documenting: https://github.com/prisma/prisma-engines/blob/master/introspection-engine/connectors/sql-introspection-connector/src/warnings.rs

**Comment by janpio** [comment]
Introspection Warning still exist and should be documented.

**Comment by Jolg42** [comment]
Related file: https://github.com/prisma/prisma-engines/blob/main/schema-engine/connectors/schema-connector/src/warnings.rs

**Comment by ruheni** [comment]
Related to: https://github.com/prisma/docs/issues/4758

**Comment by mhessdev** [comment]
Related PR https://github.com/prisma/docs/pull/4777

**Comment by ankur-arch** [comment]
@aqrln this is still the related file right? (prisma/prisma-engines@main/schema-engine/connectors/schema-connector/src/warnings.rs](https://github.com/prisma/prisma-engines/blob/main/schema-engine/connectors/schema-connector/src/warnings.rs)

**Comment by aqrln** [comment]
Yes. Line ranges https://github.com/prisma/prisma-engines/blob/main/schema-engine/connectors/schema-connector/src/warnings.rs#L59-L136 and https://github.com/prisma/prisma-engines/blob/main/schema-engine/connectors/schema-connector/src/warnings.rs#L186-L412 are the useful parts.

**Comment by nikolasburk** [comment]
Closing this as not planned for now 🙏
