### ISSUE TITLE
We should highlight that using prisma.raw() with parameters is not secure and recommend using prisma.raw``

### ISSUE THREAD

**Issue by Jolg42** [prisma/web#449]
## Problem
Users are using `prisma.raw()` like
```js
const data = await prisma.raw(
  `SELECT * FROM "ProviderItemAttribute" WHERE "provider_item" = ${root.id} AND "user" = ${auth.user.id} limit 1;`,
);
```

This example is using `prisma.raw()` the pure text version so there is no security around parameters.

Only raw`` is secure because it's using https://github.com/blakeembrey/sql-template-tag

## Solution
In this case it would be recommended to do 
```js
const data = await prisma.raw`
	SELECT * FROM "ProviderItemAttribute" WHERE "provider_item" = ${root.id} AND "user" = ${auth.user.id} limit 1;
`;
```

This should be highlighted in the docs (and examples?)
We also can think about how to warn users that are using `prisma.raw()` or even disable it under a flag?

*Note prisma.raw`` parameters do not work as of today with PostgreSQL see https://github.com/prisma/prisma-client-js/issues/595*

**Comment by steebchen** [comment]
I still have concerns that it's way too easy to accidentally use parentheses when you actually don't want to. Would it be possible to maybe introduce a second method which just allows template literal inputs (e.g. ``raw`SELECT 1` ``) which disallows using parentheses (e.g. ``raw(`SELECT 1`)``, and a **new** method which just allows passing in data unescaped via a string `rawWithoutEscape` (similar to react's `dangerouslySetInnerHtml`.

**Comment by steebchen** [comment]
IMO, this is not just a docs issue – highlighting it in the docs is NOT enough. In fact, the current docs are long outdated, which shows how many users actually read them before using a feature. It's not enough.

**Comment by steebchen** [comment]
I just realised that when you let autocompletion do its job, it will default to the parentheses method, which means no escaping will be done. That's very dangerous

**Comment by janpio** [comment]
Then please open an issue in the appropriate place instead of talking to yourself in the docs repo @Luca :D

**Comment by steebchen** [comment]
Could we just transfer it back to prisma/prisma? You moved it here in the first place.

edit: although @Jolg42's original issue was not really clear that it's not just a docs issue:

> We also can think about how to warn users that are using prisma.raw() or even disable it under a flag?

I created a new issue to clarify the concerns: https://github.com/prisma/prisma-client-js/issues/727

**Comment by janpio** [comment]
I moved it here as it was tagged as devrel  + docs (I assume, that is why things are moved here), and thus belongs here.

**Comment by mhwelander** [comment]
Include: https://prisma-company.slack.com/archives/C4GCG53BP/p1593513246334300

**Comment by Jolg42** [comment]
Docs are ✨ 

https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/raw-database-access
