### ISSUE TITLE
Docs for library authors

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#450]
Library authors sometimes need access to lower-level functionality of Prisma Client that's not available via the "official" Prisma Client API.

Often this involves access to the private `dmmf` property of Prisma Client. When documenting this, we have to make sure that it's clear that this is an "unofficial API" that might break in any release and should therefore be used with great care.

**Comment by tanberry** [comment]
Hullo, the Prisma Docs team is closing older tickets that might be stale or no longer relevant. If you feel we have closed this Issue in error, please feel free to re-open it, or create a new Issue to update the topic. Thank you for being involved in our docs!
