### ISSUE TITLE
Docs for CI/CD workflows

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#458]
This issues persists a docs requests from [Slack](https://prisma.slack.com/archives/CKQTGR6T0/p1574868511482700?thread_ts=1574796772.460900&cid=CKQTGR6T0):

> In Prisma 1 there is not a lot of information about deployment. Specifically for creating a CI/CD workflow. For instance creating a staging and production environments and rolling out incremental updates. I would love to see more information around production best practices with Prisma 2. As well as more options/info about deployments.

**Comment by mhwelander** [comment]
Example: GH actions

**Comment by mhwelander** [comment]
* Regular ol' node module
* `prisma migrate deploy` - where to run it

Googlable page

**Comment by tanberry** [comment]
Hullo, the Prisma Docs team is closing older tickets that might be stale or no longer relevant. If you feel we have closed this Issue in error, please feel free to re-open it, or create a new Issue to update the topic. Thank you for being involved in our docs!
