### ISSUE TITLE
Able to connect to multiple records during `create()`?

### ISSUE THREAD

**Issue by heymartinadams** [prisma/web#460]
Documentation only ever shows ability to connect to a single record during `create()`, e.g.

```js
// Create a new user
const newUser = await photon.users.create({
  data: {
    name: 'Alice',
    email: 'alice@prisma.io',
    posts: {
      connect: {
        title: 'hello world'
      }
    }
  },
})
```

Is it possible to connect a new author to several posts all at once?

**Comment by mhwelander** [comment]
This is on the nested writes page and now linked from here: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/crud#nested-writes
