### ISSUE TITLE
Boilerplate for using Prisma Client JS with Scripts

### ISSUE THREAD

**Issue by do4gr** [prisma/web#461]
In order for scripts to disconnect the Photon client, some boilerplate is needed. This should be documented. 

```ts
import { Photon } from '@generated/photon'

const photon = new Photon()

async function main() {
  const result = await photon.flats.findMany()
  console.log(result)
}

main()
  .catch(e => console.log(e))
  .finally(() => photon.disconnect())
```

**Comment by janpio** [comment]
Is this really still necessary or does Prisma Client clean up after itself?

**Comment by tanberry** [comment]
Hullo, the Prisma Docs team is closing older tickets that might be stale or no longer relevant. If you feel we have closed this Issue in error, please feel free to re-open it, or create a new Issue to update the topic. Thank you for being involved in our docs!
