### ISSUE TITLE
Foreign Key fields in database don't show up on Type

### ISSUE THREAD

**Issue by nlarusstone** [prisma/web#462]
prisma2@2.0.0-preview-10, binary version: 1b0c271f14ca00606f56c93717e228fe48c5603c
MacOS 10.13.6

Here's my `schema.prisma` file:
```
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  post  Post
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}
```

Which generates the following type in `index.d.ts`:
```
export declare type User = {
    id: string;
    email: string;
    name: string | null;
};
```
Despite there being a `post` field in the database, it doesn't exist in the generated type.

**Comment by tanberry** [comment]
Hullo, the Prisma Docs team is closing older tickets that might be stale or no longer relevant. If you feel we have closed this Issue in error, please feel free to re-open it, or create a new Issue to update the topic. Thank you for being involved in our docs!
