### ISSUE TITLE
docs page generating high CPU usage

### ISSUE THREAD

**Issue by nangyal** [prisma/web#464]
the docs page generating high CPU usage and even  freeze the site for few seconds

https://www.prisma.io/docs/

on the console, the following error message appeared

https://www.prisma.io/docs/page-data/reference/tools-and-interfaces/prisma-client/api/page-data.json net::ERR_ABORTED 404

Regards
Norbert

**Comment by vuki656** [comment]
Exact same here. 

Site freezes and then crashes few seconds after.

**Comment by janpio** [comment]
Sorry about this, we are working on it.

**Comment by janpio** [comment]
This should now be fixed. Seems a configuration change on Algolia, our search provider, lead to a pretty confusing regression. We will investigate next week how that could happen and how we can avoid that in the future.
