### ISSUE TITLE
Overlapping of inline codes

### ISSUE THREAD

**Issue by rahul3v** [prisma/web#472]
You can see one of the problem at [https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/generating-prisma-client#the-prisma-client-npm-module](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/generating-prisma-client#the-prisma-client-npm-module)

Currently it's overlapping
![Now](https://user-images.githubusercontent.com/24385409/84603000-c0c38800-aea8-11ea-897d-264372334db3.JPG)

**Comment by AryanJ-NYC** [comment]
![Screen Shot 2020-06-16 at 8 53 45 PM](https://user-images.githubusercontent.com/8263430/84842580-80344d80-b013-11ea-9bba-6ae3bb88c967.png)
I'm not getting the same overlap: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/generating-prisma-client#generating-prisma-client-in-the-postinstall-hook-of-prismaclient

**Comment by mhwelander** [comment]
Thanks @rahul3v for submitting a pull request to fix 💚
