### ISSUE TITLE
Fix 92 broken links (Netlify build logs shows broken links)

### ISSUE THREAD

**Issue by Jolg42** [prisma/web#485]
Thread discussed with @mhwelander @nilubava @janpio 
https://prisma-company.slack.com/archives/C5Z9TH6N9/p1592476676060100

Example build
https://app.netlify.com/sites/prisma2/deploys/5eeb43876c6531000770c863
<img width="989" alt="Screen Shot 2020-06-18 at 14 18 03" src="https://user-images.githubusercontent.com/1328733/85019101-8d198400-b16e-11ea-9079-f79f7876475d.png">

Related https://github.com/prisma/docs/issues/483

**Comment by rahul3v** [comment]
Maximum of the warning links will come just **because of using some 'redirects' and avoiding '/index' link format**. So, it's not an issue, I was seeing the same issue while i was fixing #463, but the link works fine
`/prisma-schema-file` is using redirects
`'/index'` we are not using  this format


**But I see some of the warning links here as an issue** because of little incorrectly resolving the paths (see warnings like: 21:364, 136:3, 137:3) in above image,

**Comment by janpio** [comment]
> Maximum of the warning links will come just **because of using some 'redirects' and avoiding '/index' link format**. So, it's not an issue, I was seeing the same issue while i was fixing #463, but the link works fine
> `/prisma-schema-file` is using redirects
> `'/index'` we are not using this format

That is also a problem - and either the link checker needs to be fixed or the links need to be adapted to not warn any more in some way.

**Comment by rahul3v** [comment]
Well, I do have fix it upto **14 warn errors**, Just finding to fix it till 0

**Comment by rahul3v** [comment]
@mhwelander , I want you to confirm , where exactly you wanted to point this links to in that specific files
```
warn 1 broken links found on /getting-started/setup-prisma/add-to-existing-project\
warn 594:94   #nested-writes      (there are two more in other files, but one can help)

warn 1 broken links found on /reference/tools-and-interfaces/prisma-schema/data-model\
warn 251:36   #fields
⠀
warn 1 broken links found on /reference/tools-and-interfaces/prisma-client/filtering\
warn 186:134  #no-and
```

**I have fixed this issue** just need to confirm some confusing **non-linking warning links**

**Comment by mhwelander** [comment]
@rahul3v Fixed the links in your list - thanks for pointing them out, and for all the time and effort you are putting into improving all things link-related on the Prisma doc site!

**Comment by rahul3v** [comment]
You are welcome @mhwelander, but **still not find any fixes regarding the non-linking warning links**, Should I upload the fix, And you can fix the 5 links later, as mentioned above in my comment

I have just left with **5 warn errors** . So what you say....!,

**Comment by rahul3v** [comment]
Sorry @mhwelander, my bad, **Found the** non-linking warning links **fix**, will send the pull request with the fix , might take some time, I think @nilubava made some changes, so I have to check that first and figure things out a little!

But the good news is, finally got the info **No broken links found**

**Comment by mhwelander** [comment]
See: #506 - local shows 0 broken links.
