### ISSUE TITLE
prisma-binding-argument-transform NPM package

### ISSUE THREAD

**Issue by braska** [prisma/web#491]
I saw some mentions about prisma-binding-argument-transform package in docs here: https://www.prisma.io/docs/guides/upgrade-from-prisma-1/upgrading-prisma-binding-to-sdl-first#31-migrate-graphql-queries

But looks like there no such package in NPM. Is it outdated documentation? Or opposite this documentation is ahead and there is only plans to publish such package?

**Comment by janpio** [comment]
Hey, a bit late, but this is a tiny typo. The package lives here: https://www.npmjs.com/package/@prisma/binding-argument-transform

I opened a PR to fix this: https://github.com/prisma/docs/pull/2278
