### ISSUE TITLE
Diff block does not work on Prisma schema

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#497]
https://github.com/prisma/docs/pull/492/files/d2e06c0cff37cd71d7a6dfb25b94d8542e699aa8#r443673384

![image](https://user-images.githubusercontent.com/849648/85310332-19e87880-b4b4-11ea-9ac3-27ffa9afe7bb.png)

**Comment by nilubava** [comment]
@janpio Codeblocks doesn't need `diff` to be specified explicitly. We just need to add '+' or '-' for adding/deleting lines.
