### ISSUE TITLE
Option to add note, warning, important and choose style

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#503]
Default note:

![image](https://user-images.githubusercontent.com/849648/85378676-295ed480-b53b-11ea-849f-d11f999b9e57.png)

We don't have a variety of admonitions at the moment - and the default 'note' is not very eye-catching, which means it doesn't work well for warnings.

I would like the option to specify:

* Warning
* Important
* Note
* Tip

**Comment by mhwelander** [comment]
One for design! @hrescak

**Comment by zachtil** [comment]
Requirements: https://www.notion.so/Admonitions-overview-and-future-requirements-7a96ed82ea724adebd57a00fe2f90be8

**Comment by meletj** [comment]
Related to https://github.com/prisma/docs/issues/3394

**Comment by meletj** [comment]
Admonitions options have been updated incl. different styling based on the type.
