### ISSUE TITLE
Generator: `output` is relative to `./prisma`

### ISSUE THREAD

**Issue by janpio** [prisma/web#5051]
If you have a generator in your `schema.prisma` like this:

```
generator testutils {
  provider = "./node_modules/prisma-test-utils/dist/generator.js"
  output = "./node_modules/@generated/prisma-test-utils"
}
```

The output is actually generated in `./prisma/node_modules/@generated/prisma-test-utils`:

```
✔ Generated Prisma Test Utils to .\prisma\node_modules\@generated\prisma-test-utils in 3.95s
```

That was unexpected to me.

Changing `output` to use `../node_modules...` fixes the problem.

(Could potentially also be the fault of the generator I am trying to use.)

**Comment by ankur-arch** [comment]
Closing this as we do [document](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/generating-prisma-client#using-a-custom-output-path) how a custom generation works.
