### ISSUE TITLE
Strategy to avoid duplication in version controlling migrations

### ISSUE THREAD

**Issue by tvvignesh** [prisma/web#5053]
Hi. In the microservices setup I have, so far, I have been having the migrations generated and kept along with my service code. But, to have better separation of concerns and have a proper CI/CD pipeline, I want to separate out the service as well as the database migrations to 2 repos.

The only problem I have is that, both the service and the database uses `schema.prisma` file. Service for running `prisma2 generate` and DB for running `prisma2 migrate` and thus, if I change the schema.prisma file, I have to change in 2 places leading to duplication and possible mistakes.

Is there any way to avoid this or any better strategy to separate it? With service in 1 repo and migrations in another repo with their own CI/CD pipelines.

**Comment by floelhoeffel** [comment]
We believe this should be solved with tooling and probably we could have some best practices documented around that.

**Comment by ankur-arch** [comment]
Hey 👋 thanks for opening this issue! I'm aware that it has been around for a while but we're only now getting to a major cleanup of the docs repo, so apologies for the delay 🙏

> The only problem I have is that, both the service and the database uses schema.prisma file. Service for running prisma2 generate and DB for running prisma2 migrate and thus, if I change the schema.prisma file, I have to change in 2 places leading to duplication and possible mistakes.

There's a write-up on that maybe helpful in resolving this. @tvvignesh could you let me know if this would help you solve the problem?
 
https://medium.com/@nolawnchairs/sharing-prisma-between-multiple-applications-5c7a7d131519

**Comment by tvvignesh** [comment]
> Hey 👋 thanks for opening this issue! I'm aware that it has been around for a while but we're only now getting to a major cleanup of the docs repo, so apologies for the delay 🙏
> 
> > The only problem I have is that, both the service and the database uses schema.prisma file. Service for running prisma2 generate and DB for running prisma2 migrate and thus, if I change the schema.prisma file, I have to change in 2 places leading to duplication and possible mistakes.
> 
> There's a write-up on that maybe helpful in resolving this. @tvvignesh could you let me know if this would help you solve the problem?
> 
> https://medium.com/@nolawnchairs/sharing-prisma-between-multiple-applications-5c7a7d131519

Hi. Thanks for your reply. From what I understand, the suggestion given is to make it a package and import it to solve the duplication issue - makes a lot of sense - will need to give it a thought on how it will affect the CI/CD pipelines (I mean if the CI/CD pipeline on one repo applies the migrations and its using the latest version while the other repo is using the older version of the package, the migrations will be different and generated files will be different) unless both repos (package and service maintain the same version everytime

**Comment by ankur-arch** [comment]
> will need to give it a thought on how it will affect the CI/CD pipelines (I mean if the CI/CD pipeline on one repo applies the migrations and its using the latest version while the other repo is using the older version of the package, the migrations will be different and generated files will be different) unless both repos (package and service maintain the same version everytime

Thanks for getting back 😄 . Could you try it out and let me know if that works? Then it could be worth documenting.

**Comment by tvvignesh** [comment]
> > will need to give it a thought on how it will affect the CI/CD pipelines (I mean if the CI/CD pipeline on one repo applies the migrations and its using the latest version while the other repo is using the older version of the package, the migrations will be different and generated files will be different) unless both repos (package and service maintain the same version everytime
> 
> Thanks for getting back 😄 . Could you try it out and let me know if that works? Then it could be worth documenting.

We don't use microservices anymore - we prefer monoliths now unless really required - so, dont have a real usecase but if I manage to find sometime, will definitely give it a try

**Comment by ankur-arch** [comment]
Thanks for getting back @tvvignesh, I'm closing this issue for now.
