### ISSUE TITLE
Binary Query Engine keeps running even after the parent process is killed when using `migrate reset` or `db seed`

### ISSUE THREAD

**Issue by bencun** [prisma/web#5054]
### Bug description

The issue is in that the query engine processes keep the connection pool open even when the parent Node process crashes/is killed. This means massive memory and connection leaks in production if your application is known to crash and is restored automatically by some other entity.
This usually results in too many open connections and your DB rejecting any additional connection requests and 

On my MBP `query-engine-darwin` keeps running long after my NestJS app process is gone. It even happens after running some of the migrations related stuff, e.g. `prisma migrate reset --preview-feature`.

Caching the Prisma instance resolves this only for use cases described in prisma/prisma#1983, e.g. hot reloading in Node apps such as NestJS.

### How to reproduce

Run `prisma migrate reset --preview-feature` multiple times and check the running processes on your system.
Make sure to have a seed file that establishes a connection to the database.

### Expected behavior

All native processes should end after the parent Node process has quit.

### Prisma information

Any schema connecting to the PostgreSQL DB in a container.

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 14.16.1
- Prisma version: 2.22.1

```
prisma               : 2.22.1
@prisma/client       : 2.22.1
Current platform     : darwin
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
```

**Comment by klausbadelt** [comment]
Manually disconnecting i.e. adding `.finally(async () => prisma.$disconnect())` solved it for us. Here's a much simplified version of our `seed.js`:
```js
const { PrismaClient } = require('@prisma/client')
const userSeeds = require('./seeds/users')

const prisma = new PrismaClient({ log: ['query', 'warn', 'error'] })
const truncateDb = async () => prisma.$executeRaw`TRUNCATE TABLE users CASCADE`
const seedUsers = async () => prisma.users.createMany({ data: userSeeds })

const seed = async () => {
  truncateDb()
    .then(seedUsers)
    .catch(console.error)
    .finally(async () => prisma.$disconnect())
}

module.exports = {
  seed,
  default: seed,
}
```

**Comment by Jolg42** [comment]
Changed issue to docs issue since it's working as expected and adding `.finally(async () => await prisma.$disconnect())` is what needs to be done during seeding to stop Prisma Engine.

**Comment by bencun** [comment]
@Jolg42 This doesn't seem to be a seed issue only. Please, pay attention to the original comment: this is also relevant in any other use case, not just the seeding. In our case it was a NestJS app that had a proper `$disconnect()` call when an app is destroyed. That call did nothing on our end and, therefore, even after our app exits properly we still get a hanging query engine process. Mac only, on Windows there's no such issue.

**Comment by janpio** [comment]
Note: binary query engine is not super relevant any more, so could potentially be skipped.

**Comment by craig-pyrra** [comment]
I'm seeing this issue, too, with my unit tests running with Vitest. Currently I am (very hackily, because I don't have time to look into the problem) running `exec('killall query-engine-darwin-arm64')` in a global teardown function. @janpio what did you mean by

> Note: binary query engine is not super relevant any more, so could potentially be skipped.

**Comment by janpio** [comment]
> @janpio what did you mean by
> 
> > Note: binary query engine is not super relevant any more, so could potentially be skipped.

Prisma Client does not run the binary engine as default any more since a long time. We have only a few users still using it. If you are using it, you should have a _very_ good reason. It is inferior in many ways to the default engine that Prisma runs for normal usage.

**Comment by craig-pyrra** [comment]
Ok, thanks, I was unaware the binary engine was not recommended. I don't remember why I was using it (something to do with building AMD64 Docker containers on Apple silicon?) but I'll get rid of it.

**Comment by craig-pyrra** [comment]
Ok, thanks, I was unaware the binary engine was not recommended. I don't remember why I was using it (something to do with building AMD64 Docker containers on Apple silicon?) but I'll get rid of it.

**Comment by craig-pyrra** [comment]
Ok, thanks. I have `engineType = binary` in my Prisma schema, I don't remember why I put there but I'll see if I can get rid of it.

**Comment by badoet** [comment]
hi, we running into the same issue as well,
mind sharing how to not run this binary engine and use the library instead?
is it by default running library engine instead of binary engine?

**Comment by janpio** [comment]
That is the default behavior of using Prisma Client in any recent version. There should be no running `query-engine` binary engine.
