### ISSUE TITLE
Vercel deployment behaves suboptimal when deploying multiple functions

### ISSUE THREAD

**Issue by janpio** [prisma/web#5056]
In our Vercel deployment guide we recommend putting `prisma generate` in a `postinstall` script, and any Migrations via `prisma migrate deploy` into the `vercel-build` script:

https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-vercel#vercel-specific-notes

It seems that when your application is deploying multiple functions, some possibly that do not use Prisma, both these scripts are executed _for each function_ instead of once per deployment. 

The theory is that Vercel installs dependencies for each serverless function individually instead of just once (to optimize the deployment size of each serverless function), and also executes these scripts each time.

(Reported via private Slack Direct Message)

On the other hand: Both `prisma migrate` and `prisma generate` are idempotent usually, so there is no _real_ negative effect of running these multiple times. We should still understand.

**Comment by grokpot** [comment]
@janpio 
The docs page you've linked no longer mentions anything about migrate, I think it should (currently working on that and a bit confused).
Things which aren't clear to me, which you might want to make clear:
1. Should I run `migrate` or `generate` first?
2. I found a [SO Post](https://stackoverflow.com/questions/70745094/how-to-deploy-to-vercel-with-dynamically-generated-package-from-prisma) mentioning `vercel-build`, but I think that script is now just `build`
3. Should I run `prisma migrate deploy` in `build` or in `postinstall` ?

What's working for me (Nuxt + Prisma + Vercel):
```
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare && prisma migrate deploy && prisma generate"
  },
  ```
  Relevant: 
- [What postinstall does](https://github.com/vercel/turbo/discussions/3932)
- [Page 1](https://www.prisma.io/docs/orm/prisma-migrate/workflows/development-and-production) which could mention this trouble
- [Page 2](https://www.prisma.io/docs/orm/prisma-client/deployment/deploy-database-changes-with-prisma-migrate) which could mention this trouble

**Comment by ankur-arch** [comment]
> Should I run prisma migrate deploy in build or in postinstall ?

Just generate so that the types are picked up. 

> I found a [SO Post](https://stackoverflow.com/questions/70745094/how-to-deploy-to-vercel-with-dynamically-generated-package-from-prisma) mentioning vercel-build, but I think that script is now just build

The steps are documented here:
https://www.prisma.io/docs/orm/prisma-client/deployment/serverless/deploy-to-vercel#cicd-workflows
