### ISSUE TITLE
Link checker does not support HTML anchor links

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#508]
For example: `<a id="my-anchor"></a>`

**Comment by rahul3v** [comment]
Well, **It's working fine locally**, you just forget to put **filenames along with anchor-id** to use anchor-id as link

=========================
As you can have both options open to use as mentioned it before, 
- Can use short custom links for any headers, Just provide it with custom-id, like `### header {#custom-id}` and use it like `[Mylink](#custom-id)`
- Can use `<a id="link-id"/>` and use it like `[Mylink](page-name#link-id)`

**Comment by mhwelander** [comment]
@rahul3v Perfect 🚀 😀

**Comment by janpio** [comment]
There might be a functional difference between #bar and foo#bar though. One will probably get the fully rendered URL in the HTML, the other is really a local anchor link.
