### ISSUE TITLE
Document supported date formats

### ISSUE THREAD

**Issue by pimeys** [prisma/web#520]
SQLite is very forgiving about datetimes; it actually doesn't have a real datetime type at all!

So what it supports then is either a string, or an integer. The integer is easy, it's just seconds from 1.1.1970 midnight, but the string is more complex.

Right now we support only the standard datetime strings:

- [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) (`1996-12-19T16:39:57-08:00`)
- [RFC 2822](https://tools.ietf.org/html/rfc2822#section-3.3) (`Tue, 1 Jul 2003 10:52:37 +0200`)

So if one is using an existing database in SQLite, the stringified dates need to follow one of these formats, or exist as integers.

**Comment by pimeys** [comment]
Issue from a user https://github.com/prisma/prisma/issues/2786

**Comment by internalfx** [comment]
@pimeys Shouldn't prisma support default values for `CURRENT_TIMESTAMP`?

```
sqlite> .mode column
sqlite> .headers on

sqlite> CREATE TABLE date_test ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "name" TEXT, "created_at" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP);

sqlite> INSERT INTO date_test (name) VALUES ("bob");

sqlite> SELECT * from date_test;

id          name        created_at         
----------  ----------  -------------------
1           bob         2020-07-17 21:56:16
```

As it stands now reading this data in prisma causes a crash.
