### ISSUE TITLE
Diff block doesn't highlight first line

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#526]
![image](https://user-images.githubusercontent.com/849648/85836414-d97c4980-b796-11ea-92fd-ad46a755028e.png)

````
```diff
expect(persistedData).toMatchInlineSnapshot(`
+   Array [
+     Object {
+       "body": "...",
+       "id": 1,
+       "published": true,
+       "title": "Nexus",
+     },
+   ]
  `)
```
````

![image](https://user-images.githubusercontent.com/849648/85848504-88c21c00-b7a9-11ea-83b0-b67108273016.png)

````
```diff
// api/app.ts

- import { schema, use } from 'nexus'
+ import { use } from 'nexus'
  import { prisma } from 'nexus-plugin-prisma'
- import { db } from './db'

  use(prisma())

- schema.addToContext(() => {
-   return {
-     db,
-   }
- })
```
````

**Comment by nilubava** [comment]
@mhwelander Can you try without the `diff` keyword?

**Comment by rahul3v** [comment]
Can you share the page link using `diff` keyword ?

**Comment by mhwelander** [comment]
Regular code blocks work fine:

![image](https://user-images.githubusercontent.com/849648/86004816-215bd480-ba14-11ea-8f1a-61444c8d51bb.png)

'diff' block adds coloured text to the first line that is highlighted, but does not put  in the background (number of spaces after + or - makes no difference)

![image](https://user-images.githubusercontent.com/849648/86004959-4d775580-ba14-11ea-94b1-1db3121d20d9.png)

Adding discussion tag to this so we can consider deprecating 'diff', I'm not sure why we need it.

**Comment by nilubava** [comment]
@mhwelander We don't need this. Confirmed with @nikolasburk too. We just need to add '+' or '-' on lines for addition/deletion. Closing this issue.
