### ISSUE TITLE
Style external links

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#530]
With the usual 'external link' icon (maybe we have something on prisma.io?)

**Comment by nilubava** [comment]
Something like this for external links:

![Image](https://user-images.githubusercontent.com/8801572/226611336-ef7c2b63-29c7-43bb-9d96-3750b3a119e9.png)

**Comment by nilubava** [comment]
Waiting for confirmation from Docs team

**Comment by nilubava** [comment]
@meletj to check with Doc writers for feedback

**Comment by meletj** [comment]
I'm going through these - there were a few pages where we need to update the content so it's not overwhelming with a long list of external links.

**Comment by nilubava** [comment]
@meletj to check Percy/LP again
