### ISSUE TITLE
Test transactions API / verify docs

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#543]
https://github.com/prisma/prisma/releases/tag/2.1.0

- [ ] Link to blog post when it's available
- [ ] Possible FAQs? e.g. short summary of why we aren't supporting long-running transactions

**Comment by thebiglabasky** [comment]
**Reason for candidate:** this is a new experimental feature and we need to get it exposed to understand whether people find it helpful to cope with the bulk of transactional support problems they had, so we can decide on the priority to make it stable earlier than others.
This would likely consist in fixing the speedy change I pushed earlier today.

**Comment by mhwelander** [comment]
Covered by: https://www.prisma.io/docs/guides/prisma-guides/prisma-client-transactions-guide
