### ISSUE TITLE
Remove Imgur images

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#553]
Not available in some countries.

**Comment by nikolasburk** [comment]
+ move all local images to self-hosted

**Comment by nikolasburk** [comment]
related: https://github.com/prisma/docs/issues/4

**Comment by nikolasburk** [comment]
(also do this for the `prisma-blog` repoi)

**Comment by nikolasburk** [comment]
Seems like there are still a bunch of imgur links in the docs, should this be reopened? @mhwelander 

![image](https://user-images.githubusercontent.com/4058327/107645659-3de20f80-6c79-11eb-91a6-ccf65e4eff2c.png)
