### ISSUE TITLE
Rework the sidebar scrolling logic

### ISSUE THREAD

**Issue by hrescak** [prisma/web#557]
I was FINALLY able to find an example of a sidebar behavior that i was looking for. The requirements were:
- Behave consistently no matter the length of article content
- Always scroll with content - people should never have to go to the sidebar to discover there's more content there. This has the lovely side-effect of never showing a scrollbar on the sidebar

Here's the example => http://jsfiddle.net/n2m3hwkq/1/. The behavior is pretty simple:
- if there's content in the sidebar hidden in the direction of scrolling, scroll with content. if not, stay fixed on the page.
- if the sidebar is taller than the content, behave like a normal element with height (try deleting all but one paragraphs in the jsFiddle.

The fiddle itself is written with jQuery but the logic can probably be lifted into react pretty effortlessly. I tried to replicate the behavior with just CSS with position:sticky - i failed in reasonable time but if it *might* be possible.

**Comment by hrescak** [comment]
This would also fix #322

**Comment by hrescak** [comment]
@nilubava I had a chance to take a look at this and I am SO EXCITED!!!!! This is amazing. I found one nit / edge case - when you click on an anchor link (like https://deploy-preview-878--prisma2-docs.netlify.app/reference/understand-prisma/under-the-hood#using-custom-engine-binaries), the sidebar has some unexpected behavior (scrolls to different positions), and when I clicked again, the sidebar disappeared completely until I scrolled the page

**Comment by hrescak** [comment]
Ah just saw that's basically #894

**Comment by mhwelander** [comment]
Have also reviewed - created a feedback ticket about the left-hand nav juddering (does not do that in prototype once you scroll past the end of the nav but the content keeps going)
