### ISSUE TITLE
sidebar labels and inline code lost background

### ISSUE THREAD

**Issue by hrescak** [prisma/web#558]
![image](https://user-images.githubusercontent.com/753458/86262815-5ee46d00-bb8e-11ea-9d19-a9e8e99ef62c.png)
I'm assuming this was during the brightening of the code blocks - IIRC this should have onlyh been for big code blocks and not inline code or sidebar labels

**Comment by janpio** [comment]
Ha, on my screen I can juuuuust slightly see the pill form still ;)
