### ISSUE TITLE
Enum CRUD and filtering examples

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#561]
## Context

https://prisma.slack.com/archives/CKQTGR6T0/p1591617431211600

## Suggested action

Update some CRUD examples to include how to set / update an enum

**Comment by meletj** [comment]
Covered by: 
https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#defining-enums
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#enum
