### ISSUE TITLE
Engines diagram update

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#562]
## Context

https://prisma-company.slack.com/archives/C5Z9TH6N9/p1589389315232000

**Comment by meletj** [comment]
@nikolasburk I see from the Slack thread, this was then assigned to DevRel. Can you confirm if this still need to be done/updated?

**Comment by nikolasburk** [comment]
Thanks for the ping, looking into this! I'll decide later whether this should be closed or whether we want to update anything 👍

**Comment by nikolasburk** [comment]
Personally I find the diagram clear enough, so probably wouldn't change anything actually.
