### ISSUE TITLE
Hint for queryRaw with PostgreSQL: Postgres lowercases without double quotes + have to prefix table with schema name

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#570]
Users that are not used to querying PostgreSQL directly but need to use `queryRaw` for some reason can easily get confused because of some Postgres behaviour, here is an example of that confusion: https://github.com/prisma/prisma/discussions/2664

It would be nice to have a section in the docs that quickly mentions these "gotchas" when querying Postgres with raw SQL.

**Comment by janpio** [comment]
A more elaborate version of that would be a great thing for the dataguide possibly.

**Comment by nikolasburk** [comment]
Add to: https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#considerations
