### ISSUE TITLE
Query Engine: Size of connection pool

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#575]
## Suggested action

Add note to Query Engine docs that size of connection pool can be logged with logging/debugging options (probably `prisma:engine` or just `*`)

**Comment by nikolasburk** [comment]
Add a 3rd section to: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool#connection-pool-size (e.g. called "Viewing the connection pool size" and explain how to do this with [logging](https://www.prisma.io/docs/concepts/components/prisma-client/debugging) and with metrics)
