### ISSUE TITLE
UI glitch: Reduce size of "Experimental" - releveant for Prisma Migrate

### ISSUE THREAD

**Issue by Jolg42** [prisma/web#591]
Happens on Firefox and Chrome on macOS

<img width="286" alt="Screen Shot 2020-07-03 at 15 24 53" src="https://user-images.githubusercontent.com/1328733/86474000-3a30f680-bd42-11ea-84cd-643e6e085eb4.png">

**Comment by nilubava** [comment]
@Jolg42 : Isn't this a duplicate of #322?

**Comment by Jolg42** [comment]
Yes indeed, closing :)
