### ISSUE TITLE
Update SQLite connect details  to include sqlite://

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#597]
The error for invalid “DATABASE_URL” for SQLite from the engines is:
`… must start with the protocol sqlite://`
From
https://github.com/prisma/prisma-engines/blob/c29fbcd0f57c67e11722e479b9d135b346767e69/libs/datamodel/core/src/configuration/source/builtin_datasource_providers.rs#L29-30
Though it should probably be `… must start with the protocol sqlite:// or file:`
It’s confusing as … must start with the protocol `sqlite://` is not mentioned anywhere in the docs, only `file:./dev.db`
https://www.prisma.io/docs/reference/database-connectors/sqlite#connection-details

**Comment by Jolg42** [comment]
[Closing after internal discussion](https://prisma-company.slack.com/archives/CEYCG2MCN/p1594035056381100?thread_ts=1594026418.374700&cid=CEYCG2MCN)
