### ISSUE TITLE
Example CI / CD pipeline

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#606]
## Suggested action

Create a CI / CD landing page under Guides > Deployment with a brief description of the CI workflow (that you use `prisma migrate deploy` for test databases)

Mostly Google food - can include a guide for how to set up Prisma with CircleCI or similar.

**Comment by mhwelander** [comment]
Related: #458

**Comment by nikolasburk** [comment]
We have recently published an article about this topic here: https://www.prisma.io/blog/testing-series-5-xWogenROXm
