### ISSUE TITLE
Deployment guide: Digital Ocean App Platform

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#611]
A deployment guide for Digital Ocean, similar to the guides that we already have.

**Comment by Jolg42** [comment]
We could focus here on a deployment guide for their "App Platform"
https://www.digitalocean.com/products/app-platform
Which uses serverless functions
https://www.digitalocean.com/products/functions

**Comment by nikolasburk** [comment]
We're currently not planning to add this to our docs but people who need this can find a deployment guide here: https://www.digitalocean.com/community/tutorials/how-to-build-a-graphql-api-with-prisma-and-deploy-to-digitalocean-s-app-platform
