### ISSUE TITLE
Relay connections with Prisma Client

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#615]
## Context

https://prisma-company.slack.com/archives/CD2HW8X2A/p1592380447122400

## Suggested action

This could be added as a sub-page under Prisma Client > Pagination

**Comment by nikolasburk** [comment]
There's a [library that implements Relay pagination with Prisma,](https://github.com/devoxa/prisma-relay-cursor-connection#readme) we don't want to document it further in our docs.
