### ISSUE TITLE
Simplify documentation header

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#621]
:wave: Hi design team!

In addition to #557 (scrollbar), I would really like to simplify the Prisma docs header by:

* Moving the search bar to the top right
* Making the content block flush with the header rather than overlapping
* Generally reducing the size of the header

Something like this:

![image](https://user-images.githubusercontent.com/849648/86758870-6f8c5b80-c044-11ea-8678-ebdf8c49ba34.png)

Creating this issue as a starting point for discussion.

**Comment by mhwelander** [comment]
Related: I'd like the ability to differentiate between key navigation items and less key navigation items. For example: docs, quickstart, and reference are key, community/prisma1/faq/blog are less important. Here is my crude mockup 

![image](https://user-images.githubusercontent.com/849648/86762660-1540ca00-c047-11ea-8186-b93ff74d8e1e.png)

**Comment by hrescak** [comment]
I'm a bit worried about us having duplicate navigation for these elements in sidebar and header. We should probably reconcile that?

**Comment by mhwelander** [comment]
> I'm a bit worried about us having duplicate navigation for these elements in sidebar and header. We should probably reconcile that?

How about:

![image](https://user-images.githubusercontent.com/849648/87129746-1d407a00-c292-11ea-9586-2416ee9fb8bc.png)

I imagined API reference sitting in its own tree rather than being part of the main docs (Discussion: #637)

![image](https://user-images.githubusercontent.com/849648/87129829-3ea16600-c292-11ea-9e58-151ef29fe9a6.png)
