### ISSUE TITLE
Ability to exclude a heading from the TOC

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#629]
For example, in the following TOC for API ref docs, I want to exclude 'Examples' and 'Remarks' headings:

![image](https://user-images.githubusercontent.com/849648/86900086-2eab4a00-c10b-11ea-8323-622d2136dd11.png)

Could be something like:

```
## My cool heading {exclude-toc}
```

**Comment by janpio** [comment]
Temporary workaround (which unfortunately makes it impossible to link to the heading) is to just bold the text instead of making it a headline.

**Comment by meletj** [comment]
Stale
