### ISSUE TITLE
Prisma CLI and .env file loading (from 2.3.0)

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#638]
Internal context: https://prisma-company.slack.com/archives/CEYCG2MCN/p1594304960437800

**Comment by Jolg42** [comment]
Subscribing to the issue :)

**Comment by janpio** [comment]
https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema#using-env-files 

For 2.3.0 this should probably be rewritten that we look "besides your Prisma Schema" file (which can be in `./prisma/schema.prisma` or defined via the `--schema` CLI parameter for all commands) and fall back to `./prisma/schema.prisma` if we can not find any there.

**Comment by Jolg42** [comment]
This new implementation is currently waiting in a PR https://github.com/prisma/prisma/pull/2979 and will be merged for 2.3.0
