### ISSUE TITLE
Clean up .env sections

### ISSUE THREAD

**Issue by janpio** [prisma/web#639]
1. https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema#defining-environment-variables-with-the-env-function `env()` is not for "defining environment variables", but to access them in the schema.
3. "If you want environment variables to be evaluated at runtime ..." should be extracted into a new headline "Using your environment variables in your code" as the other part only defines how `.env` files are loaded in the CLI. (This needs clarification if that loads from the same locations as the CLI @Jolg42)
4. https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema#use-multiple-env-files-or-env-files-outside-the-prisma-folder is a bit confusing: You _either_ use `dotenv` in your code - OR you install and use `dotenv-cli` - so the full section should be split into "via command line tool" or "via your application code" or similar.

**Comment by Jolg42** [comment]
@janpio what kind of clarification are we talking about here?

**Comment by janpio** [comment]
@Jolg42 See the code example under "If you want environment variables to be evaluated at runtime" on https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema. Does that code snippet automatically load from the same locations as the CLI or what exactly does that do?

**Comment by janpio** [comment]
Interesting suggestion from a user:
Besides using `dotenv` in code or `dotenv-cli` you can _also_ make it work by adding a symlink between you custom `.env` file location and `/prisma/.env`: https://prisma.slack.com/archives/CKQTGR6T0/p1594635028120700?thread_ts=1594401216.096200&cid=CKQTGR6T0

**Comment by janpio** [comment]
> Interesting suggestion from a user:
> Besides using `dotenv` in code or `dotenv-cli` you can _also_ make it work by adding a symlink between you custom `.env` file location and `/prisma/.env`: [prisma.slack.com/archives/CKQTGR6T0/p1594635028120700?thread_ts=1594401216.096200&cid=CKQTGR6T0](https://prisma.slack.com/archives/CKQTGR6T0/p1594635028120700?thread_ts=1594401216.096200&cid=CKQTGR6T0)
