### ISSUE TITLE
NestJS integration documentation

### ISSUE THREAD

**Issue by esistgut** [prisma/web#643]
NestJS provides an example for the old prisma1 using prisma-binding (https://github.com/nestjs/nest/tree/master/sample/22-graphql-prisma).
Can you provide a new sample integration for prisma2? The part I find most lacking is the `@ResolveProperty()` implementation as this is something usally done with a dataloader but I can't get what is the best practice when using prisma2.

**Comment by mhwelander** [comment]
@jasonkuhrt Does this belong in the Nexus repo?

**Comment by jasonkuhrt** [comment]
@mhwelander nope

**Comment by janpio** [comment]
If I understood this correct, it might actually be transferred to  https://github.com/prisma/prisma-examples - I moved it here earlier as it was labelled with `kind/docs` in `prisma/prisma`.

**Comment by tanberry** [comment]
Hullo, the Prisma Docs team is closing older tickets that might be stale or no longer relevant. If you feel we have closed this Issue in error, please feel free to re-open it, or create a new Issue to update the topic. Thank you for being involved in our docs!
