### ISSUE TITLE
CRUD example is missing `main` invocation, is TypeScript only (but not labeled) and no output

### ISSUE THREAD

**Issue by janpio** [prisma/web#644]
https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/api.md#crud

To be able to run this the `main` invocation is missing, it is in TypeScript which might not be obvious (it was not to me...), and there is no `console.log` or similar to output the returned data.

**Comment by mhwelander** [comment]
This will be fixed when we split API ref and docs -- docs will be copy-paste-able.
