### ISSUE TITLE
Docker on Monorepo

### ISSUE THREAD

**Issue by yovanoc** [prisma/web#646]
Hello, I'm working on a monorepo with yarn workspaces and I would like to use Docker for alternate with dev and prod mode and it feels a little bit complicated.

![image](https://user-images.githubusercontent.com/7302317/63581440-577c2c80-c597-11e9-9df4-8ce3aed555cf.png)

This is the architecture of the project. And I was telling me that it would be great to have an example to make this working because a lot of people could be interested.

Thanks

**Comment by tanberry** [comment]
Hullo, the Prisma Docs team is closing older tickets that might be stale or no longer relevant. If you feel we have closed this Issue in error, please feel free to re-open it, or create a new Issue to update the topic. Thank you for being involved in our docs!
