### ISSUE TITLE
docmentation about prisma constructor( datasources?:) may need to be fixed

### ISSUE THREAD

**Issue by hmjia** [prisma/web#651]
on documentation: Prisma Client=>Constructor=> datasources=>
2. Instantiate a client and override the connection string of the my_database datasource:

**should read as below**

`const prisma = new PrismaClient({
  datasources: {
   db:'file:./dev_qa.db'
   }
  },
})`

**Because :**

`export type Datasources = {
  db?: string
}`

**If use the current documentation suggestion:**
`const prisma = new PrismaClient({
  datasources: {
   my_database: {
     url: 'file:./dev_qa.db'
   }
  },
})`

**will get invalid prisma.() invocation error**

**Comment by janpio** [comment]
What version of Prisma CLI and Client are you using? The current documentation should actually work, and the one you suggested should not work any more. `db` and `my_database` are the names of the `datasource` in the `schema.prisma` file and would of course need to be adapted to your case.

**Comment by hmjia** [comment]
> What version of Prisma CLI and Client are you using? The current documentation should actually work, and the one you suggested should not work any more. `db` and `my_database` are the names of the `datasource` in the `schema.prisma` file and would of course need to be adapted to your case.

Hi Janpio, 
I am using  "@prisma/client": "^2.0.0-beta.5". 
and also I noticed another issue with findMany(). 

I can't use 'take' filter:
``await prisma.client.product.findMany({
          skip:0,
          take: 100,
        });``

but I can use 'first' filter:
`await prisma.client.product.findMany({
          skip:0,
          first: 100,
        });`

**Comment by janpio** [comment]
> I am using "@prisma/client": "^2.0.0-beta.5".

That is really old - and as the name says from the "beta" phase of Prisma.

You should really update to a newer 2.x.x version or Prisma that is a lot more stable and properly documented.

**Comment by hmjia** [comment]
Thank you. update to newer version fix all problems. 

> > I am using "@prisma/client": "^2.0.0-beta.5".
> 
> That is really old - and as the name says from the "beta" phase of Prisma.
> 
> You should really update to a newer 2.x.x version or Prisma that is a lot more stable and properly documented.
