### ISSUE TITLE
DB icon has lower opacity than other icons

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#656]
![image](https://user-images.githubusercontent.com/4058327/87299702-ce524900-c50c-11ea-99ea-42a70fc752ef.png)

https://www.prisma.io/docs/more/style-guide/mdx-examples

**Comment by nilubava** [comment]
https://prisma-company.slack.com/archives/C5Z9TH6N9/p1594727371005400?thread_ts=1594715898.001700&cid=C5Z9TH6N9
