### ISSUE TITLE
Heroku deployment - cannot download example files

### ISSUE THREAD

**Issue by jeremysouthon** [prisma/web#664]
Hi there I was trying to follow the Deploying to Heroku guide but was stuck at the first point of downloading the example.

It says to run: `curl https://codeload.github.com/prisma/prisma-examples/tar.gz/heroku | tar -xz --strip=3 prisma-examples-heroku/deployment-platforms/heroku/` 

but this results in this error for me:
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     57      0 --:--:-- --:--:-- --:--:--    57
tar: Unrecognized archive format
tar: prisma-examples-heroku/deployment-platforms/heroku: Not found in archive
tar: Error exit delayed from previous errors.
```

Just wanted to start this to see if anyone else had this issue and solved it.

**Comment by 2color** [comment]
Thanks for pointing this out @jeremysouthon. It has been corrected. 

The correct command is: 
```
curl https://codeload.github.com/prisma/prisma-examples/tar.gz/master | tar -xz --strip=3 prisma-examples-master/deployment-platforms/heroku
```
