### ISSUE TITLE
Copying example code also copies the line numbers

### ISSUE THREAD

**Issue by do4gr** [prisma/web#665]
It would be much nicer if the line numbers were not copied.

**Comment by nilubava** [comment]
@do4gr Can you point me to the exact page where you faced this problem?

**Comment by do4gr** [comment]
Sorry, saw this only now. Here is one: 

https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-prisma-migrate-typescript-postgres#write-your-first-query-with-prisma-client
