### ISSUE TITLE
Clicking on some links is sometimes really slow

### ISSUE THREAD

**Issue by Jolg42** [prisma/web#666]
It happens to me sometimes that I click on in the sidebar menu on a link and it takes “a while” to update the page, see example recording:

![22f0bc0a48768854c664a89181c763e3](https://user-images.githubusercontent.com/1328733/87542208-dfcd5980-c6a2-11ea-90ac-52cca0f931fb.gif)

- I click on some links it works fast enough for me until…
- I click on “REST API”, only once (timestamp 8sec)
- And wait for rendering… 7 seconds later :slow-parrot:

This happens kind of randomly but only once per link, looking at the Dev Tools I see it loads:
`/docs/page-data/app-data.json`
`/docs/page-data/guides/upgrade-guides/upgrade-from-prisma-1/upgrading-a-rest-api/page-data.json`

I forgot to open Dev Tools to record what was happening, it could be Netlify slow response or client side rendering taking a long time somehow?

Tested on Firefox Developer Edition 79.0b3 (64-bit) on macOS Catalina

**Comment by nikolasburk** [comment]
Some additional info: https://github.com/prisma/docs/issues/774

**Comment by nikolasburk** [comment]
More info: https://github.com/prisma/docs/issues/810
