### ISSUE TITLE
Supply .env file via symlink

### ISSUE THREAD

**Issue by janpio** [prisma/web#685]
Interesting suggestion from a user:
Besides using `dotenv` in code or `dotenv-cli` you can _also_ make it work by adding a symlink between you custom `.env` file location and `/prisma/.env`: https://prisma.slack.com/archives/CKQTGR6T0/p1594635028120700?thread_ts=1594401216.096200&cid=CKQTGR6T0

_Originally posted by @janpio in https://github.com/prisma/docs/issues/639#issuecomment-657500037_

**Comment by keinsell** [comment]
@janpio Symlinks doesn't work at all, I was trying to add `.env` to my `prisma` package with following content which points to my main `.env` and it doesn't see variables defined in my root.

```
# .env
./../../.env
```

Nevermind, like... I was doing this `.env` by hand instead to actually use `ln -s ../../.env packages/prisma-db/.env`. It works perfectly 😃

**Comment by nikolasburk** [comment]
Is this still relevant since we don't have `prisma/.env` any more, @janpio?

**Comment by janpio** [comment]
I would assume that also works with the main `.env` file.
Not sure if it is worth documenting though necessarily.

**Comment by nikolasburk** [comment]
In that case, we'll close this for now 👍
