### ISSUE TITLE
Unnecessary scrollbar on "Share on Twitter"-button

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#697]
After sharing 👍 feedback on a page, we show a CTA to share the docs page on Twitter. Right now the button has a weird scrollbar on the right.

![image](https://user-images.githubusercontent.com/4058327/88278336-7c66ab80-cce2-11ea-9def-e6c20dcf8fdd.png)

**Comment by luisejrobles** [comment]
Hi @nikolasburk , I might can do it :rocket:

**Comment by luisejrobles** [comment]
could you please assign this to me

**Comment by luisejrobles** [comment]
fixed in Pull request  #721

**Comment by luisejrobles** [comment]
PR already merged, you might want to close this issue @nikolasburk
