### ISSUE TITLE
[docs] Return value of CRUD operations

### ISSUE THREAD

**Issue by kenptr** [prisma/web#708]
The official docs (https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/crud#update) doesn't say what's the return value of CRUD operations.

For example, in case of `update` on item, does it throw an error or return `null` if the object was not found?

**Comment by divyenduz** [comment]
@kenptr Thanks for raising this, `update` throws an error when an object to be updated is not found

![image](https://user-images.githubusercontent.com/746482/88557034-59702a80-d047-11ea-995e-af583a06eba2.png)

This issue tracks updating the docs to reflect this :)

**Comment by mhwelander** [comment]
Covered in #773

**Comment by mhwelander** [comment]
All return types now documented in tables like this in reference docs: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#return-type
