### ISSUE TITLE
All datamodels in Prisma schema examples should be orderd by the order the columns (would probably) have in the database

### ISSUE THREAD

**Issue by janpio** [prisma/web#715]
2.3.0 changed Introspection to keep the order of the fields identical to what is discovered in the database. (Before the fields were ordered alphabetically). We should update all datamodels in the documenation to adhere to that to avoid confusion for our users.

**Comment by nikolasburk** [comment]
@janpio do you still think this one is relevant / worth the effort? I haven't seen people confused around column/field orderings in the last 4 years.

**Comment by janpio** [comment]
It is inconsistent to how the Introspection result would _really_ look like, so reproducing the examples from the docs manually would lead to different results to what we document.

Indeed not something we will hear a lot of complaints though, but just a general thing that will make beginner's life slightly more confusing.

**Comment by ankur-arch** [comment]
Closing this as it's outdated.
