### ISSUE TITLE
Link to Re-Introspection documentation in "Renaming Relation Fields"

### ISSUE THREAD

**Issue by janpio** [prisma/web#727]
https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/configuring-the-prisma-client-api#renaming-relation-fields

Context: https://twitter.com/i/web/status/1289660815549718530

**Comment by ruheni** [comment]
This seems to be the default behavior during re-introspection and no update is required

https://github.com/prisma/prisma/issues/2829

**Comment by janpio** [comment]
Would still be nice to mention that here explicitly, and link to a location that explains that things liek the relation names are kept on Introspection with an existing schema file (Re-Introspection )
