### ISSUE TITLE
Icon for "edit" line highlight are not rendered

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#740]
When the edit highlight is used, the line should be prefixed with a `✎` character (similar to `+` and `-` for adding and removing lines).

![image](https://user-images.githubusercontent.com/4058327/89270913-4b6c6c00-d63c-11ea-96f4-38d6f0c18755.png)

**Comment by nilubava** [comment]
@nikolasburk Can you check if its resolved now?

**Comment by nikolasburk** [comment]
![image](https://user-images.githubusercontent.com/4058327/92242083-8ffb5980-eebf-11ea-85e3-ba1a5784b193.png)


Looks good ✅ (the icon feels a bit subtle but I think it's fine)

**Comment by rahul3v** [comment]
@nikolasburk The highlighted color is bit darker i believe, don't you think  (compare to the ones used for `+` and `-`), it would be batter to make it little lighter
