### ISSUE TITLE
Update orderBy syntax

### ISSUE THREAD

**Issue by pantharshit00** [prisma/web#760]
We changed the type of orderBy to be an array instead of an object when you want to provide multiple attributes. Docs are now out of date because of this change.

See: https://github.com/prisma/prisma/releases/tag/2.4.1

Docs link: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/sorting/#sort-user-by-multiple-fields---email-and-role

**Comment by mhwelander** [comment]
@pantharshit00 Hmm.. 🤔  This was fixed: https://github.com/prisma/docs/pull/749/files I shall investigate. 🔍

**Comment by mhwelander** [comment]
It was a build issue, fixed by #762
