### ISSUE TITLE
Docs are crashing

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#774]
Moving the discussion from the main `prisma/prisma` to here. (https://github.com/prisma/prisma/discussions/3356)

![image](https://user-images.githubusercontent.com/4058327/90755955-0f900280-e2dc-11ea-97ed-800cc63126d9.png)

**Comment by mhwelander** [comment]
Decision: Review use of `Downshift`

**Comment by nikolasburk** [comment]
Closing as duplicate of https://github.com/prisma/docs/issues/666
