### ISSUE TITLE
Add troubleshooting section to Studio docs to delete the `~/.cache/prisma` folder

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#775]
I had continuous issues with Prisma Studio on my machine, it would basically never work because it seemed for some reason it was using an old version of a query engine. The reason apparently was that there were caching issues with the `~/.cache/prisma` folder. Once I entirely deleted the folder, everything was working properly.

**Comment by sdnts** [comment]
To be more specific, the folder to delete would be `~/.cache/prisma/studio` (on macOS & Linux), and `%appdata%\ Prisma Studio` on Windows

**Comment by janpio** [comment]
That Windows path does not exist on my Windows machine, although I used Studio before.
`%AppData%/Prisma/Studio` does exist though.

**Comment by sdnts** [comment]
Oh whoops, that 's what I meant!
