### ISSUE TITLE
Remove inlinecode when indexing headings

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#776]
Index contains `inlinecode @default inlinecode` instead of `@default`

Affects ranking of page:

![image](https://user-images.githubusercontent.com/849648/90876352-d7072c00-e3a2-11ea-9084-864eb22b845f.png)

**Comment by ankur-arch** [comment]
@carlagn do we still get this in index headings? AFAIK we don't use the inlinecode component anymore.

**Comment by jharrell** [comment]
@ankur-arch no longer an issue (see screenshot) 
<img width="857" alt="image" src="https://github.com/user-attachments/assets/b5af4d99-407e-4d56-a275-9084e81d85d3">

closing.
