### ISSUE TITLE
Batching behaviour not documented

### ISSUE THREAD

**Issue by ForbesLindesay** [prisma/web#798]
I'm setting up a new GraphQL server and using Prisma for the data access layer. I tried reading in https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/connection-management but I couldn't find any documentation about the N+1 query problem and what was needed to resolve it.

From reading the source of https://github.com/prisma/prisma/blob/master/src/packages/client/src/runtime/getPrismaClient.ts and https://github.com/prisma/prisma/blob/9de058ae2482aa6f4d59418f93479f9c8d3633c6/src/packages/client/src/runtime/Dataloader.ts it looks like this is already handled, providing all queries happen in the same tick. That doesn't appear to be documented anywhere though.

It also appears that unlike setups using https://www.npmjs.com/package/dataloader there is no deduping of requests, or way to cache across the lifecycle of a GraphQL request. Is that correct?

In any case, all this should exist somewhere in the documentation.

**Comment by nikolasburk** [comment]
Hey @ForbesLindesay, thank you so much for raising these questions! We're indeed behind on the documentation for this and will tackle it soon 🙏 

In the meantime, you might be interested in the talk ["How Prisma Solves the N+1 Problem in GraphQL Resolvers"](https://www.youtube.com/watch?v=7oMfBGEdwsc) by our lead TS engineer where he discusses a few of the questions you raised in your comment. Hope that helps and thanks again for pointing this out, let me know if we can assist you with anything else for the time being! 🙂

**Comment by mhwelander** [comment]
Covered here: https://www.prisma.io/docs/guides/prisma-guides/query-optimization-performance
