### ISSUE TITLE
Clarify when Prisma queries are run (PrismaPromise behavior)

### ISSUE THREAD

**Issue by matthewmueller** [prisma/web#800]
@Sytten brought up a good point in Slack that we don't really talk about when queries are executed.

In this example:

```js
import { User } from '@prisma/client'

export default async (app: Application, { id }: DeleteInput): Promise<User> => {
  const operations: Promise<any>[] = []

  // Delete onboarding
  operations.push(app.prisma.onboarding.deleteMany({ where: { userId: id } }))

  // Delete availability application
  const availabilityApp = await app.models.availabilityApp.findOne({ userId: id })

  if (availabilityApp) {
    operations.push(
      app.prisma.availabilityTemplate.deleteMany({
        where: { appId: availabilityApp.id },
      }),
      app.prisma.availabilityApp.delete({ where: { id: availabilityApp.id } })
    )
  }

  // Delete user
  const user = await app.prisma.user.findOne({ where: { id } })
  operations.push(app.prisma.user.delete({ where: { id } }))

  // Execute all operations
  await app.prisma.transaction(operations)
  return user!
}
```

You might expect the operations to run in the order that they appear, but this is not the case. They run more like this:

```js
await app.models.availabilityApp.findOne({ userId: id })
await app.prisma.user.findOne({ where: { id } })

// batched together at the end
app.prisma.onboarding.deleteMany({ where: { userId: id } })
app.prisma.availabilityTemplate.deleteMany({
  where: { appId: availabilityApp.id },
}),
app.prisma.availabilityApp.delete({ where: { id: availabilityApp.id } })
app.prisma.user.delete({ where: { id } })
```

This is because Prisma queries are then-ables, meaning they only execute when you call `await` or `.then()` or `.catch()`. This is called lazy evaluation. This is different then a regular promise which starts executing immediately. This would be called eager evaluation or immediate evaluation.

This was an understandable source of confusion for @Sytten because most libraries using promises eagerly evaluate. For example:

```js
const fs = require('fs/promises')
fs.readFile("./test.txt") // starts reading the file immediately!
```

But in the Prisma client:

```js
const deleteOperation = app.prisma.onboarding.deleteMany({ where: { userId: id } }) // doesn't do anything
// ...
deleteOperation.then() // now it executes
// or..
await deleteOperation // now it executes.
```

**Comment by alan345** [comment]
Thanks for the clarification.

What would be the best solution to execute Prisma request but being asynchronous?

```
// do some stuff
app.prisma.onboarding.deleteMany({ where: { userId: id } }) // DeleteManyAction doesn't do anything

await doOtherStuffsRightNow()

// DeleteManyAction when node is available
```

**Comment by Sytten** [comment]
Just call then/catch on it and it will start executing if I am not mistaken

**Comment by JJWesterkamp** [comment]
Out of curiosity, is there a section in the documentation that explains this design decision? I can imagine enough good reasons to use lazy promises, but it would help a lot if that is explained somewhat. Because at the same time I can imagine reasons to **not** lazily evaluate. For example when you call `delete()` and only care about potential errors, but already have a generic catch clause in place in some enclosing scope/context:
```typescript

/*
 * Just as an example, this may be some composition of concurrent tasks:
 */
async function doSomethingWith(user: User): Promise<void> {
    try {
        await Promise.all([
            deleteUser(user.id),
            someOtherConcurrentTaskWith(user),
        ])
    catch (anyError: unknown) {
        // Handle all errors the same regardless of its source...
    }
}
/**
 * Now this can be a regular function.
 */
function deleteUser(id: number) {
    return app.prisma.user.delete({ where: { id } })
}
```

---

I feel that calling `.then()` or `.catch()` without providing callbacks is an anti-pattern similar to, for instance, the noop-subscribe pattern with RxJS observables (there's even [an ESLint rule](https://github.com/cartant/eslint-plugin-rxjs/blob/main/docs/rules/no-ignored-subscribe.md) for this).

Would it be a good addition to be able to 'toggle' eager evaluation for certain situations? For instance:

```typescript
// a) Through a dedicated method maybe?
app.prisma.user.deleteNow({ where: { id } })

// b) Through an additional option flag?
app.prisma.user.delete({
    where: { id },
    eager: true,
})
```

**Comment by Jolg42** [comment]
Note we currently have the following documented 

https://www.prisma.io/docs/concepts/components/prisma-client#3-use-prisma-client-to-send-queries-to-your-database

> Note that queries will only run if used with await or chained with .then(). 
> When using $transaction's this makes it possible for the client to pass all the queries on to the query engine as a transaction.

> The client methods are "thenable", they return a PrismaPromise which is implemented like a JavaScript Promise, except for the query to be executed they need to be awaited or chained with .then().

@JJWesterkamp So this lazy promise makes it possible to have transactions like this
```js
const [posts, totalPosts] = await prisma.$transaction([
  prisma.post.findMany({ where: { title: { contains: 'prisma' } } }),
  prisma.post.count(),
])
```

It can be indeed confusing.

Calling then, catch or awaiting the promise will execute the query.

**Comment by nhhockeyplayer** [comment]
Be nice to see an ORM thats Observable based and ditch promises forever. Sacred nature is calling for it.

**Comment by Jolg42** [comment]
Note for Docs team
- we need to fix what is currently documented and add `or chained with .catch().` as well
- decide if where it's currently documented is the right place?
- anything else? should we add an example?

**Comment by shadoath** [comment]
An update to the [Transaction](https://www.prisma.io/docs/concepts/components/prisma-client/transactions#the-transaction-api) documentation. 

I'm still wrapping my head around this one. It sounds like if I'm running a loop over several items, I can run the standard await syntax on each one in my loop. Or I can keep an array of the 'then-able' promises (without await) and then call an `await prisma.$transaction([promiseArrayItems]) and then each will be executed. 
It would seem the latter way is more efficient. Is that correct?

**Comment by Jolg42** [comment]
@shadoath Yes that should be faster, though in the transaction queries will be executed sequentially. 
Another option would be to use `Promise.all()` or `Promise.allSettled()` to run all the queries at the same time, like
```js
const queries = [
    prisma.user.findUnique({ where: { id: 1 } }),
    prisma.user.findUnique({ where: { id: 2 } }),
  ]
const users = await Promise.all(queries)
```

**Comment by bennettdams** [comment]
Maybe I'm misunderstanding the examples in this issue, but how would one do "fire-and-forget" queries?

Example: I have a simple API endpoint where some "post" data is returned. For each request, I also want to increment the view counter of that post. Something like:


```ts
async function foo(postId: string) {
  // increment post views
  prisma.post.update({
    where: { id: postId },
    data: { noOfViews: { increment: 1 } },
    select: null,
  });
  
  // find post data
  return await prisma.post.findUnique({
    where: { id: postId },
    select: defaultPostSelect,
  });
}

```

I don't care about the result of the `update` query, so I also don't want to wait for it at all, as otherwise each request for "post" data will have to wait until the "increment view" operation is finished first.

There's a [similar discussion](https://github.com/prisma/prisma/discussions/3781) for this use case, but it's from 2020, so I'm not sure if it is still relevant.

**Comment by WayneEllery** [comment]
> Maybe I'm misunderstanding the examples in this issue, but how would one do "fire-and-forget" queries?

To do that you could use use `.then` on it:

```JavaScript
async function foo(postId: string) {
  // increment post views
  prisma.post.update({
    where: { id: postId },
    data: { noOfViews: { increment: 1 } },
    select: null,
  }).then(() => {});
  
  // find post data
  return await prisma.post.findUnique({
    where: { id: postId },
    select: defaultPostSelect,
  });
}
```

**Comment by tremby** [comment]
@Jolg42's link to the docs above is now broken; it looks like the relevant part has moved to one of these:

- https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/introduction#4-use-prisma-client-to-send-queries-to-your-database
- https://www.prisma.io/docs/orm/reference/prisma-client-reference#prismapromise-behavior
