### ISSUE TITLE
A deployment guide for Azure Web Apps

### ISSUE THREAD

**Issue by ryands17** [prisma/web#807]
As per [this](https://github.com/prisma/prisma/discussions/3463) discussion, it would be great to have a deployment guide for Azure Web Apps as well.

**Comment by meletj** [comment]
https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-azure-functions

**Comment by janpio** [comment]
Azure Web Apps are probably a different thing: https://azure.microsoft.com/en-us/products/app-service/web/

**Comment by Jolg42** [comment]
From what I understand, Azure Web Apps can use serverless functions
https://learn.microsoft.com/en-us/azure/app-service/overview
<img width="708" alt="Screenshot 2022-12-05 at 10 57 06" src="https://user-images.githubusercontent.com/1328733/205608242-58c05564-3f68-405a-aeab-634594b30841.png">

**Comment by janpio** [comment]
App Service is a higher level service that pulls in different other lower level services of Azure. My comment was regarding the link that @meletj posted to make sure it is clear that App Servicea and Azure Functions are different things.

**Comment by nikolasburk** [comment]
Currently not planned, we might consider this in the future as we rethink our deployment guides.
