### ISSUE TITLE
0000-00-00 00:00:00 not supported 

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#812]
## Context

https://prisma-company.slack.com/archives/CEYCG2MCN/p1599028199053500?thread_ts=1598976531.037800&cid=CEYCG2MCN

## Suggested action

* Update `DateTime` section in schema reference
* Create a 'Working with DateTime' page similar to 'Working with JSON' - can be a difficult field type

Related: #548

**Comment by matthewmueller** [comment]
I'm not sure that this needs to be considered a limitation since it's not supported in Javascript either

```
> new Date("0000-00-00 00:00:00.000")
Invalid Date
```

```
> new Date("0000-01-01 00:00:00.000")
1999-12-31T23:00:00.000Z // works but produces garbage
```

```
> new Date("0000-01-01T00:00:00.00Z")
0000-01-01T00:00:00.000Z // works and the earliest possible time.
```

**Comment by janpio** [comment]
This is in context of the expectations of MySQL users (and their databases): https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
