### ISSUE TITLE
Design update feedback

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#816]
- [x] Add identation if ToC goes to more than one level - for example; everything under 'Attributes' should be slightly indented.

![image](https://user-images.githubusercontent.com/849648/92213163-5f052f80-ee93-11ea-9fcb-4ae894889fc3.png)

<hr />
 
- [x] Left-hand navigation resets to top when you use the ToC:

1. Visit https://deploy-preview-806--prisma2-docs.netlify.app/guides/database-workflows/import-and-export-data/postgresql - the left hand nav has automatiically scrolled down to highlight the current item
2. Click on anything in the RIGHT hand nav - left-hand nav either disappears or jumps back to the top (extension of @janpio 's issue where left-hand nav disappears):

![image](https://user-images.githubusercontent.com/849648/92214413-421d2c00-ee94-11ea-919d-c0f9b40b042c.png)

<hr />

- [x] This is more of a feature request, but I think we should make right-hand ToC 'sticky' - should follow you when you a) scroll down the page and b) get to the page via an anchor link.

<hr />

- [x] Remove styling from `TopBlock` element:

![image](https://user-images.githubusercontent.com/849648/92216655-ddaf9c00-ee96-11ea-93b8-c1715d6582da.png)

**Comment by mhwelander** [comment]
- [ ] This is more of a feature request, but I think we should make right-hand ToC 'sticky' - should follow you when you a) scroll down the page and b) get to the page via an anchor link.

**Comment by thebiglabasky** [comment]
> This is more of a feature request, but I think we should make right-hand ToC 'sticky' - should follow you when you a) scroll down the page and b) get to the page via an anchor link.

+1. This makes helps accepting the reduction of the main content's space.

**Comment by thebiglabasky** [comment]
Clicking the "API Reference" sub-menu brings you to the main nav's sub-menu. This is highly confusing to me.
I was expecting the top bar submenu to be highlighted and have its own left-hand navigation.

**Comment by hrescak** [comment]
I'd really like to unify the headers across all of our properties. I'm ok with replacing this header with a common one. If you click through the other header items from here the headers across the website, docs and blog are all slightly different which I'd like to avoid

**Comment by rahul3v** [comment]
Well, the design is batter, but needs much improvement as per the preview link provided above, few one that i found
 - on the right **content** field on the docs are not sticky,
 - the serach-bar icons used are too small and are not appropriate

**Comment by hrescak** [comment]
Thank you for your feebdak @rahul3v - they're both great suggestions. we'll keep improving the docs both before and after launching this.
