### ISSUE TITLE
Searching for CLI commands and flags (e.g. --schema or --watch) returns no results

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#817]
Present here: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-cli/command-reference#overview

**Comment by ankur-arch** [comment]
@jharrell the issue might be due to special characters not being picked up by algolia, such as `--` in this case. Is this easy to resolve?

**Comment by ankur-arch** [comment]
Closing this as this is outdated.
