### ISSUE TITLE
Page for cascading deletes has wrong preview content

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#821]
This link: https://www.prisma.io/docs/guides/database-workflows/cascading-deletes/postgresql#9-validate-the-deletion-behavior-in-a-nodejs-script

Shows the following wrong preview when unfurled:

![image](https://user-images.githubusercontent.com/4058327/92358797-5ce8de00-f0ea-11ea-8faf-011ac2b7d33f.png)

**Comment by janpio** [comment]
The page `<title>` is also wrong.

This is weird, as the mdx file on Github has the correct content and "Import" does not appear once in that page.

**Comment by mhwelander** [comment]
@janpio @nikolasburk I think it's because the name of the page isn't unique across  the entire site - there are multiple pages named 'postgres' in different sections. Suggest changing this to a website bug /cc @nilubava

**Comment by mhwelander** [comment]
Fixed by Daniel
