### ISSUE TITLE
PostgreSQL database docs are outdated

### ISSUE THREAD

**Issue by MatthewCaseres** [prisma/web#823]
In "9.2 Validating CASCADE" I believe the field "anotherPost" in prisma.anotherUser.create should be "AnotherPost".
In "9.3 Validating NO ACTION" I believe the $oneMoreUser should be oneMoreUser.
I changed the default value from 42 to 2 when creating the table for SET DEFAULT, along with a couple of changes in the javascript to make it so that the code throws an error upon the first run of "node index.js" but has the default value upon the second run of "node index.js".

The style isn't consistent with the rest of the docs across most of the database section, it seems like it was written a while ago.

**Comment by ruheni** [comment]
The guides have been moved from the docs and likely live in the prisma.io/dataguide.
