### ISSUE TITLE
Page UI related : UI modification needed for search bar

### ISSUE THREAD

**Issue by rahul3v** [prisma/web#840]
Well, the **search bar** should be **showing all the time some were on scree**n, either onScrollUp, populate it or, should stick the search bar somewhere on top or bottom as you like onPageScroll

**Issue** : user need to scrollUp first, to search something 
**concern** : if user is in the middle of the page and wanted to search something, then user has  to go up to the top to do the search.

Well it's ok for small page length but not for the **bigger** ones 
like https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/crud#delete

**Comment by meletj** [comment]
Fixed as the search bar is not part of the sticky nav.
