### ISSUE TITLE
How does Prisma work with Relay?

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#848]
[People sometimes wonder](https://github.com/prisma/prisma/discussions/3613) how to implement a GraphQL server that implements the [Relay spec](https://relay.dev/docs/en/graphql-server-specification.html) with Prisma. One important thing to be aware of in this context is that the GraphQL server implementation is independent from using Prisma, meaning Prisma only takes care of sending database queries but the GraphQL schema is modeled/implemented independently from that.

For a quick win, we can add this info as an [FAQ](https://www.prisma.io/docs/more/faq) to the docs.

**Comment by alaadotsol** [comment]
Hey! Any updates on this? I am building a library (and a prisma generator) to give users a set of relay/prisma/typegraphql helpers to make building relay-compliant APIs easier, but it seems like the query batching (n+1 problem) is a bit of a challenge with relay edges/nodes, would love to see if there is some internal discussion on this!

**Comment by yf-hk** [comment]
Any updates?
