### ISSUE TITLE
Suggest that .env should be placed in .gitignore

### ISSUE THREAD

**Issue by matthewmueller** [prisma/web#864]
Right now we don't suggest that `.env` should be in `.gitignore`. I think this should be the default recommendation.

More context on the problem: https://www.notion.so/prismaio/Environment-Management-71e0177bf2cc422290aeb8733e322d46#7bee87e9b4694b36ae8fe57060e60f36

Open issues that may affect this

- https://github.com/prisma/prisma/issues/3720
- https://github.com/prisma/prisma/issues/3721

**Comment by nikolasburk** [comment]
Let's add a note to the Getting Started from scratch guides: https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/
