### ISSUE TITLE
Add a recommended way to instantiate PrismaClient

### ISSUE THREAD

**Issue by ryands17** [prisma/web#879]
As per this discussion: https://github.com/prisma/prisma/discussions/3776

It would be great to add a recommended way on how to instantiate Prisma on long running servers (i.e. 1 instance for the entire app preferably) and also a small note for Serverless apps where we still need to perform more tests.

**Comment by mhwelander** [comment]
Related: #822

**Comment by mhwelander** [comment]
Documented: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/instantiate-prisma-client#use-a-single-shared-instance-of-prismaclient
