### ISSUE TITLE
Feedback: Header requires slightly more padding to match blog / homepage

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#901]
![image](https://user-images.githubusercontent.com/849648/95428331-2c929a80-0949-11eb-9412-2d5be493e947.png)

**Comment by hrescak** [comment]
I've updated all the repositories to have a skinnier header, and updated the lens repo to make sure header menus have consistent line-height. I had to be very forceful to trigger the lens update in my repo and netlify didn't pick the update up even on clean deploy so we might want to look into some sort of versioning for prisma lens. @nilubava

**Comment by hrescak** [comment]
Note to self : nix yarn.lock and re-deploy
