### ISSUE TITLE
Clarify Node version requirements

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#913]

**Comment by Jolg42** [comment]
Node `>=10` is currently the minimum to use Prisma CLI and Client, the source of truth is currently:
https://github.com/prisma/prisma/blob/master/src/packages/cli/package.json#L33
https://github.com/prisma/prisma/blob/master/src/packages/client/package.json#L25

It's likely this will be updated to `>=10.4` for BigInt support.

We should document that Prisma is supported on `>=10` and that it's recommended to use a LTS version, currently v12 or v14 see https://nodejs.org/en/about/releases/

"Less important" fact [from this issue.](https://github.com/prisma/prisma/issues/4179#issuecomment-725537892)
Node `>=10.13.0` is currently required to develop

**Comment by mhwelander** [comment]
https://www.prisma.io/docs/reference/system-requirements
