### ISSUE TITLE
Filter by 0 relations

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#917]
https://prisma-company.slack.com/archives/C5Z9TH6N9/p1602854686016200

**Comment by nikolasburk** [comment]
Just adding this link for some public context for what this is issue is about as well: https://github.com/prisma/prisma/issues/3888

**Comment by mhwelander** [comment]
Documented: https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#filter-on-presence-of-related-records
