### ISSUE TITLE
SPEC: Binaries

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#925]
See: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1603187090042800?thread_ts=1602848895.004500&cid=C5Z9TH6N9

<img width="777" alt="image" src="https://github.com/prisma/docs/assets/4058327/ca3b6236-6fff-41ce-8bff-cc32e8d9dda0">

* [x] Binaries URL schema
* [x] OpenSSL justification
* [x] Protocols
* [ ] Move engines list to a more obvious place
* [ ] Better use cases for binaryTargets

https://github.com/prisma/specs/tree/master/binaries

**Comment by janpio** [comment]
No 4 and 5 are not done yet, and might actually be useful and improve the current state.

**Comment by jharrell** [comment]
👋 we're cleaning up our backlog of issues and are closing everything older than two years. If you still feel that this issue is relevant, please feel free to re-open and our team will take a look. Thank you!
