### ISSUE TITLE
SPECS: Generator extensibility (document `generator` API)

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#930]
https://prisma-company.slack.com/archives/C5Z9TH6N9/p1602848920005200

**Comment by nikolasburk** [comment]
More context: https://prisma-company.slack.com/archives/C5Z9TH6N9/p1613642188205100

![image](https://user-images.githubusercontent.com/4058327/108340226-a0d32980-71d8-11eb-92eb-27c5d00053b4.png)

**Comment by nikolasburk** [comment]
When we talk about the generator API, we should also highlight the community generators that already exist: https://github.com/prisma/docs/issues/856

**Comment by Jolg42** [comment]
Here is the most up-to-date content done by Tim https://www.notion.so/prismaio/Prisma-Generators-a2cdf262207a4e9dbcd0e362dfac8dc0
