### ISSUE TITLE
Feedback: Left-hand nav sidebar 'judders'

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#931]
https://www.loom.com/share/e20cb3ddb90b4e68b0103c26f7a2935f

Left-hand nav keeps shaking as you scroll through content that is longer than the left-hand nav.

Related: #1178

**Comment by mhwelander** [comment]
Related: #557

**Comment by hrescak** [comment]
Wow I couldn't see that - what OS & browser combo are you using?

**Comment by nilubava** [comment]
@mhwelander Can't seem to reproduce this. Can you point me to the right page?

**Comment by mhwelander** [comment]
Moving this to 'prioritize after release' and changed to 'on Windows', as I still see the shaking.

**Comment by hrescak** [comment]
specificially on chrome on windows, when zoomed in too.
