### ISSUE TITLE
Feedback about the documentation

### ISSUE THREAD

**Issue by zoultrex** [prisma/web#946]
Hey guys, I'd like to share a feedback from me and my colleague who have started using Prisma1 this year.

The initial setup examples and documentation are good, they successfully help us get started and understand the basics of the proposed workflow.

But we find hard and not obvious what needs to be done every time we need to add new schemas, or edit the schemas after you got it running for the first time.
In my case specifically, every time I need to edit an existing model/schema, like adding a new property to a user, a bunch of errors show up and It's not obvious what I have done wrong or what I missed while doing a task like that...

It's too bad that also the courses that I have purchased that rely on Prisma1 for the backend were setup in a way that they first defined all the models/schemas and after that they built the server, so again, the "next steps" on working with Prisma 1 daily were missing how to add new / edit things. Personally I feel like I went through a building course that you can only build one exact project, and have not learned how to do whatever I want with it. 
I also see that there are quite a few advanced topics to do other things on the docs, but the daily chores like mentioned just above, if present, are missing from my attention.
(courses: https://advancedreact.com/ - https://www.udemy.com/course/graphql-bootcamp/ ... also, I have purchased those courses with the sole purpose of working with Prisma, why don't you guys make courses like that, put a price on it and I'd happily pay for it... who better than you guys to make a course like that? or a partnership with an instructor like that?)

PS, I'm mostly a frontend dev with 10y experience, going into fullstack so I'm new to a lot of the concepts used, that of course makes things harder, but my parter on the project is a senior dev with over 15 years of experience working with backend, and even for him it's not a walk in the park on how to keep growing a prisma project.

All I have mentioned is mostly our experience with Prisma 1, but after checking the Prisma2 docs I feel similar, where is the part of the docs (if it's there it did not became obvious) that tell me how to grow my project after it's all set up? I wonder why I have such a difficulty. 
So since I plan on migrating from Prisma 1 to 2, I plan on keep trying to do those things and gather more feedback on those for you guys. But in case of Prisma 2, I feel like it can be even more difficult to get unstuck in those situations because I have not found a single course out there that gives me more information on how to work with version 2. But well see after I get started...

Thanks for the awesome work though, even though it's hard for me to understand those new conpcepts and everything I really like Prisma and how it helps me build a great backend

**Comment by ruheni** [comment]
Hey 👋

We appreciate your feedback. We have improved our docs and would like to know if you're experiencing any rough edges with Prisma.

Here are a few resources 
- [Learn Prisma](https://www.prisma.io/learn) — tutorials, videos, and guides we've created at Prisma + Community guides here to help you on your journey
- We have extensive guides here on Prisma that you may also find helpful on this page: https://www.prisma.io/docs/guides
- https://prisma.io/dataguide — on how to work with databases in general
- I would also recommend https://howtoprisma.com/production-ready-prisma/ by Ryan Chenkie

In the meantime, I'll go ahead and close the issue. Feel free to reopen it if you have any other suggestions. 🙂
