### ISSUE TITLE
Mentioning partial indices

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#947]
## Context 

https://github.com/prisma/docs/pull/942#pullrequestreview-517726120

**Comment by ruheni** [comment]
We're currently documenting the list of unsupported features, including partial indices on this page in our docs: https://www.prisma.io/docs/guides/migrate/developing-with-prisma-migrate/include-unsupported-database-features#:~:text=Views-,Partial%20indexes,-To%20add%20an
