### ISSUE TITLE
Capitalization consistency for product maturity stages

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#948]

**Comment by nikolasburk** [comment]
Shouldn't they be capitalized?

![image](https://user-images.githubusercontent.com/4058327/98366693-b14e0280-2034-11eb-9857-c5bc37950ca4.png)

 
![image](https://user-images.githubusercontent.com/4058327/98366675-a98e5e00-2034-11eb-9bc0-0cc6cf6af0ae.png)

**Comment by mhwelander** [comment]
@nikolasburk Right you are! Fixed in #996
