### ISSUE TITLE
Document limitation of missing primary keys in join tables when using implicit relations and corresponding workaround

### ISSUE THREAD

**Issue by albertoperdomo** [prisma/web#958]
Join tables created by Prisma through implicit relation syntax do not have primary keys.

Databases can be configured to enforce the existence of primary keys in all tables. This is true for some cloud providers like DigitalOcean.

We should document this limitation and suggest an available workaround, which is using the explicit relation syntax, creating the join model and making sure this join model has a primary key.

Context: https://github.com/prisma/migrate/issues/596#issuecomment-701487236

**Comment by janpio** [comment]
This limitation came up on Slack again: https://prisma.slack.com/archives/CA491RJH0/p1625592140192700

**Comment by pavelruzicka** [comment]
I have just recently run into this issue again using a managed database provided by DigitalOcean. Obviously the workaround is clear in switching from implicit to explicit relation syntax, however the docs are still yet to mention this limitation and I had to come across these two issue discussion in order to realize what the issue was.

**Comment by tanberry** [comment]
Notes for working this Issue: 
--docs that likely need to be modified include:
1. https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#rules-for-defining-an-implicit-m-n-relation
2. https://www.prisma.io/docs/concepts/components/prisma-schema/relations/troubleshooting-relations#how-to-use-a-relation-table-with-a-many-to-many-relationship (DONE, PR #2468)
3. https://www.prisma.io/docs/guides/migrate-to-prisma/migrate-from-typeorm#implicit-many-to-many-relations (Done, PR #2469)
4. https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations/#conventions-for-relation-tables-in-implicit-m-n-relations

**Comment by tanberry** [comment]
Hi @pavelruzicka and @albertoperdomo. I created [PR #2468](https://github.com/prisma/docs/pull/2468) to add info about this issue to the troubleshooting doc; feedback/tweaks welcome! I will add the same content to other areas in the docs, so look for more PRs on this.

**Comment by mhessdev** [comment]
Closing because PR from @tanberry
