### ISSUE TITLE
Top-level landing page summaries

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#985]
## Context

Some of the top-level landing pages don't have an intro (Concepts, Components..) - suggest adding at least a sentence.

**Comment by grpatel** [comment]
Added a [task](https://www.notion.so/prismaio/Docs-Brainstorm-plan-to-add-summaries-to-top-level-landing-pages-0cc59a9ae6754b79ad1bb3bc553be106?pvs=4) to the DevAdv task board to brainstorm a plan for this
