### ISSUE TITLE
Back to top on a per-section basis

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#987]
Needs to be discussed first! My thinking is:

* Enable with a flag (e.g. enableBackToTop) because we don't want it on all pages
* Possibly choose at which level it exists - at h3 by default maybe?

**Comment by hrescak** [comment]
Hervé can I get some more context on this one?

**Comment by hrescak** [comment]
@thebiglabasky

**Comment by thebiglabasky** [comment]
In the API reference section when you go down pretty low, after clicking around in the auto-scrolling, to go back to top you need to take your keyboard and Cmd+Up as it otherwise is quite cumbersome to scroll all the way back up to see the top-level navigation

**Comment by ankur-arch** [comment]
Closing due to being outdated.
