### ISSUE TITLE
Search icons on Firefox aren't sized correctly

### ISSUE THREAD

**Issue by sdnts** [prisma/web#992]
Search magnifying glass icon, as well as the `/` shortcut icon should be wider (to match Chromium)

This is Firefox:
![Screenshot 2020-11-05 at 15 46 12](https://user-images.githubusercontent.com/7689783/98255785-1561bf80-1f7e-11eb-9a87-38e78ec20879.png)

And this is Chromium:
![Screenshot 2020-11-05 at 15 46 19](https://user-images.githubusercontent.com/7689783/98255816-1e529100-1f7e-11eb-8a13-b6261c3de442.png)

Couldn't resist debugging a little, so:
The search icon `svg` has a `16px` width and height, but because its parent is `flex`, you'll need to add a `flex-shrink: 0` to the SVG as well to ensure that the `<input />` sibling does not shrink it. IDK what the flex spec says is "correct", but adding that line to the CSS fixes this issue for me in Firefox :D

**Comment by janpio** [comment]
Can confirm on Windows.
