### ISSUE TITLE
Noticeable delay between clicking the search input and seeing the search box

### ISSUE THREAD

**Issue by sdnts** [prisma/web#993]
Little nitpicky, so please feel free to close.

After clicking on the search input, I see a noticable 1 second delay, only after which the search box opens. I've recorded a GIF:
![Screen-Recording-2020-11-05-at-1](https://user-images.githubusercontent.com/7689783/98257857-75f1fc00-1f80-11eb-87f0-22203ed20603.gif)

In here, the circle around my cursor appears when I click. That should make it easy for you to see the delay I'm seeing.
I'm seeing this on Firefox, Chromium, as well as private windows (with no extensions etc.).

**Comment by sdnts** [comment]
Oops, should have searched before opening an issue. Please close if this is the same as https://github.com/prisma/docs/issues/980 (I'm not sure)

**Comment by janpio** [comment]
Switcher is actually a dropdown on the getting started pages.
